<div class=Section1>

<p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
normal'><a name="_GoBack"><span lang=EN-US style='font-size:12.0pt;font-family:
"Times New Roman","serif"'>1 СТУДЕНЧЕСКИЙ ЧЕМПИОНАТ МИРА 1984</span></a></p>

<table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 width="100%"
 style='width:100.0%'>
 <tr>
  <td style='padding:1.5pt 1.5pt 1.5pt 1.5pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  lang=EN-US style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1
  СТУДЕНЧЕСКИЙ ЧЕМПИОНАТ МИРА 1984<br>
  САН ПАУЛО, БРАЗИЛИЯ.<br>
  <br>
  <br>
  --------------------------------------------------------------------------------<br>

  <br>
  Итоговая классификация:<br>
  <br>
  1. Бразилия<br>
  2. Парагвай<br>
  3. Испания</span></b></p>
  </td>

 </tr>
</table>

<p class=MsoNormal><span lang=EN-US>&nbsp;</span></p>

</div>
