<div class=Section1>

<p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
normal'><a name="_GoBack"><span lang=EN-US style='font-size:12.0pt;font-family:
"Times New Roman","serif"'>2 СТУДЕНЧЕСКИЙ ЧЕМПИОНАТ МИРА 1990</span></a></p>

<table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 width="100%"
 style='width:100.0%'>
 <tr>
  <td style='padding:1.5pt 1.5pt 1.5pt 1.5pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2 СТУДЕНЧЕСКИЙ
  ЧЕМПИОНАТ МИРА</span></b></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1-9 сентября
  1990 года</span></b></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'>ИТАЛИЯ,ПАРМА</span></b></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><span lang=EN-US><a
  href="http://futsal.ucoz.ru/_pu/2/25350386.jpg"
  title="&quot;Нажмите, для просмотра в полном размере...&quot; t "><b><span
  lang=RU style='font-size:12.0pt;font-family:"Times New Roman","serif";
  text-decoration:none'><img border=0 width=400 height=299 id="Рисунок 2"
  src="2%20____________%20_________%20____%201990.files/image001.jpg"
  alt="http://futsal.ucoz.ru/_pu/2/s25350386.jpg"></span></b></a></span></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><span lang=EN-US style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'>&nbsp;</span></p>

  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'>ИТАЛИЯ</span></b></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'><br>
  Группа </span></b><b><span lang=EN-US style='font-size:12.0pt;font-family:
  "Times New Roman","serif"'>A</span></b></p>
  <div align=center>
  <table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 width="100%"
   style='width:100.0%;border-collapse:collapse'>
   <tr>
    <td style='border:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>м</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>сборная</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>1</span></p>

    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>4</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>мячи</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>о</span></p>

    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>Италия</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>4:2</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3:1</span></p>
    </td>

    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>11:0</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>18-3</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>6</span></p>

    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>Бельгия</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2:4</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3:2</span></p>
    </td>

    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>6:1</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>11-7</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>4</span></p>

    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>Великобритания</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>1:3</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2:3</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>

    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>6:1</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>9-7</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2</span></p>

    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>4</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>Сан Марино</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>0:11</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>1:6</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>1:6</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2-23</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>0</span></p>

    </td>
   </tr>
  </table>
  </div>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><span style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'><br>
  <br>
  <br>
  <b>Группа </b></span><b><span lang=EN-US style='font-size:12.0pt;font-family:
  "Times New Roman","serif"'>B</span></b></p>

  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span style='font-size:12.0pt;
  font-family:"Times New Roman","serif";color:red'>Болгария-СССР 2:2</span></b></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span style='font-size:12.0pt;
  font-family:"Times New Roman","serif";color:red'>Испания-СССР 3:2<br>
  Голы Чельцов, Тарасов</span></b></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span style='font-size:12.0pt;
  font-family:"Times New Roman","serif";color:red'>СССР-Алжир 2:0</span></b></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span style='font-size:12.0pt;
  font-family:"Times New Roman","serif";color:red'>Голы: Кузьмичев, Арефьев</span></b></p>
  <div align=center>

  <table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 width="100%"
   style='width:100.0%;border-collapse:collapse'>
   <tr>
    <td style='border:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>м</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>сборная</span></p>
    </td>

    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>

    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>4</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>мячи</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>о</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>Испания</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3:2</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>5:2</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>4:0</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>12-4</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>6</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif";color:red'>СССР</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2:3</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2:2</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2:0</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>6-5</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>Болгария</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2:5</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2:2</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2:1</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>6-8</span></p>
    </td>

    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>4</span></p>
    </td>

    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>Алжир</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>0:4</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>0:2</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>1:2</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>1-8</span></p>
    </td>

    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>0</span></p>
    </td>
   </tr>
  </table>
  </div>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><span style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'><br>
  <br>

  <b>ЗА 5-8 МЕСТА<br>
  <br>
  БОЛГАРИЯ-САН-МАРИНО 10-5<br>
  ВЕЛИКОБРИТАНИЯ-АЛЖИР 4-2<br>
  <br>
  ПОЛУФИНАЛЫ:<br>
  <br>

  ИСПАНИЯ-БЕЛЬГИЯ 5-4 </b></span><b><span lang=EN-US style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'>&nbsp;</span></b><b><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'>по пенальти<br>
  <span style='color:red'>ИТАЛИЯ-СССР 3-1</span></span></b></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span style='font-size:12.0pt;
  font-family:"Times New Roman","serif";color:red'>Гол: Ульянов</span></b></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'><br>
  ФИНАЛЫ:</span></b></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'><br>

  МАТЧ ЗА </span></b><b><span lang=EN-US style='font-size:12.0pt;font-family:
  "Times New Roman","serif"'>&nbsp;</span></b><b><span style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'>7 МЕСТО:<br>
  <br>
  АЛЖИР-САН-МАРИНО 5-1<br>
  <br>
  МАТЧ ЗА 5 МЕСТО:<br>
  <br>
  БОЛГАРИЯ-ВЕЛИКОБРИТАНИЯ 5-0<br>

  <br>
  МАТЧ ЗА 3 МЕСТО:<br>
  <br>
  <span style='color:red'>БЕЛЬГИЯ-СССР 4-5</span></span></b></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span style='font-size:12.0pt;
  font-family:"Times New Roman","serif";color:red'>Голы: Кузьмичев-2,Ульянов-2,
  Арефьев<br>
  </span></b><b><span style='font-size:12.0pt;font-family:"Times New Roman","serif"'><br>
  ФИНАЛ:<br>

  <br>
  ИТАЛИЯ-ИСПАНИЯ 0:0 по пенальти 5-4<br>
  <br>
  </span></b><b><span lang=EN-US style='font-size:14.0pt;font-family:"Times New Roman","serif"'><a
  href="http://futsal.ucoz.ru/SESON-1990-1991/SChM-1990.pdf"><span lang=RU>СТАТИСТИКА<br>
  </span></a></span></b><b><span style='font-size:12.0pt;font-family:"Times New Roman","serif"'><br>
  Сборную </span></b><b><span lang=EN-US style='font-size:12.0pt;font-family:
  "Times New Roman","serif"'>СССР представлялклубТорпедо (Москва)</span></b></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><span lang=EN-US style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'>&nbsp;</span></p>

  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><span lang=EN-US><a
  href="http://futsal.ucoz.ru/_pu/2/86937729.jpg"
  title="&quot;Нажмите, для просмотра в полном размере...&quot; t "><span
  lang=RU style='font-size:12.0pt;font-family:"Times New Roman","serif";
  text-decoration:none'><img border=0 width=400 height=292 id="Рисунок 1"
  src="2%20____________%20_________%20____%201990.files/image002.jpg"
  alt="http://futsal.ucoz.ru/_pu/2/s86937729.jpg"></span></a></span></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><span lang=EN-US style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'>&nbsp;</span></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'>Состав: Игошин, Арефьев, Кобзев,
  Табунов, Тарасов, Талалаев, Борисов, Чельцов, Кузьмичев, Ульянов. </span></b><b><span
  lang=EN-US style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Тренер:
  Миронов</span></b></p>
  </td>
 </tr>
</table>

<p class=MsoNormal><span lang=EN-US>&nbsp;</span></p>

</div>
