<body lang=RU>

<div class=Section1>

<p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
normal'><a name="_GoBack"><span lang=EN-US style='font-size:12.0pt;font-family:
"Times New Roman","serif"'>5 СТУДЕНЧЕСКИЙ ЧЕМПИОНАТ МИРА 1996</span></a></p>

<table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 width="100%"
 style='width:100.0%'>
 <tr>
  <td style='padding:1.5pt 1.5pt 1.5pt 1.5pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  style='font-size:14.0pt;font-family:"Times New Roman","serif"'>5 СТУДЕНЧЕСКИЙ
  ЧЕМПИОНАТ МИРА</span></b></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'>11-18 августа
  1996 года</span></b></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'>ФИНЛЯНДИЯ, ЯВАСКУЛА</span></b></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><span lang=EN-US style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'>&nbsp;</span></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><span style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'><img width=176 height=225
  id="Рисунок 1"
  src="5%20____________%20_________%20____%201996.files/image001.jpg"
  alt="http://futsal.ucoz.ru/_pu/2/78560.jpg"></span></p>

  <div align=center>
  <table class=MsoNormalTable border=1 cellpadding=0 width="100%"
   style='width:100.0%;border:outset black 1.5pt'>
   <tr>
    <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:18.0pt;font-family:"Times New Roman","serif";color:crimson'>Групповые
    турниры</span><span lang=EN-US style='font-size:12.0pt;font-family:"Times New Roman","serif"'><br>
    </span><span lang=EN-US style='font-size:14.0pt;font-family:"Times New Roman","serif";
    color:blue'>Группа А</span></p>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span></p>
    <div align=center>

    <table class=MsoNormalTable border=1 cellpadding=0 width="50%"
     style='width:50.0%;border:outset blue 1.5pt'>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>М</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Команда</span></b></p>
      </td>

      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></b></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Мячи</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>О</span></b></p>
      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Бельгия</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'></td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3:6</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3:1</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1:0</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>7-7</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>6</span></p>
      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Финляндия</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>6:3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'></td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2:2</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2:2</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>10-8</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>5</span></p>
      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Израиль</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1:3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2:2</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'></td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>6:3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>9-8</span></p>
      </td>

      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
      </td>

      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>США</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0:1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2:2</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3:6</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'></td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>5-9</span></p>
      </td>

      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
     </tr>
    </table>
    </div>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'><br>
    </span></b><b><span lang=EN-US style='font-size:14.0pt;font-family:"Times New Roman","serif";
    color:blue'>Группа B</span></b></p>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span></p>
    <div align=center>
    <table class=MsoNormalTable border=1 cellpadding=0 width="50%"
     style='width:50.0%;border:outset blue 1.5pt'>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>М</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Команда</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></b></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Мячи</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>О</span></b></p>
      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Россия</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'></td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4:1</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>7:2</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>14:2</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>25-5</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>9</span></p>
      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Португалия</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1:4</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'></td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4:3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>17:1</span></p>
      </td>

      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>22-8</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>6</span></p>
      </td>
     </tr>
     <tr>

      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Хорватия</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2:7</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3:4</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'></td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>14:4</span></p>
      </td>

      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>19-15</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
     </tr>
     <tr>

      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Польша</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2:14</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1:17</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4:14</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'></td>

      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>7-45</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>
     </tr>
    </table>

    </div>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:14.0pt;font-family:"Times New Roman","serif";color:blue'>&nbsp;</span></b></p>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:14.0pt;font-family:"Times New Roman","serif";color:blue'>Группа
    C</span></b></p>
    <div align=center>
    <table class=MsoNormalTable border=1 cellpadding=0 width="50%"
     style='width:50.0%;border:outset blue 1.5pt'>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>М</span></b></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Команда</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></b></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Мячи</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>О</span></b></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Испания</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'></td>

      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2:1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3:2</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>19:1</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>24-4</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>9</span></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Украина</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1:2</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'></td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2:2</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>20:2</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>23-5</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Югославия</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2:3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2:2</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'></td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>15:3</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>19-8</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Кипр</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1:19</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2:20</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3:15</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'></td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>6-54</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>

     </tr>
    </table>
    </div>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:14.0pt;font-family:"Times New Roman","serif";color:blue'>&nbsp;</span></b></p>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:14.0pt;font-family:"Times New Roman","serif";color:blue'>Группа
    D</span></b></p>
    <div align=center>
    <table class=MsoNormalTable border=1 cellpadding=0 width="50%"
     style='width:50.0%;border:outset blue 1.5pt'>
     <tr>

      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>М</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Команда</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></b></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Мячи</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>О</span></b></p>

      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Италия</span></b></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'></td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4:2</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>5:0</span></p>
      </td>

      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4:1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>13-3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>9</span></p>

      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Бразилия</span></b></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2:4</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'></td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>11:5</span></p>
      </td>

      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>5:0</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>18-9</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>6</span></p>

      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Иран</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0:5</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>5:11</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'></td>

      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4:3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>9-19</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>

      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Словакия</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1:4</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0:5</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3:4</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'></td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4-13</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>

      </td>
     </tr>
    </table>
    </div>
    </td>
   </tr>
   <tr>
    <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>ЧЕТВЕРТЬФИНАЛЫ:</span></b><span
    lang=EN-US style='font-size:12.0pt;font-family:"Times New Roman","serif"'><br>

    9-16 места:<br>
    Кипр&nbsp;-&nbsp;Иран - 1:4<br>
    Хорватия&nbsp;- США -12:0<br>
    Югославия&nbsp;- Словакия - 5:1<br>
    Израиль -&nbsp;Польша 5:3</span></p>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span></p>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1-8 места:<br>
    Россия -&nbsp;Финляндия - 7:1<br>
    Бельгия&nbsp;-&nbsp;Портгуалия - 2:3<br>
    Италия&nbsp;-&nbsp;Украина - 2:5<br>

    Испания -&nbsp;Бразилия - 0:3</span></b><span lang=EN-US style='font-size:
    12.0pt;font-family:"Times New Roman","serif"'>&nbsp;<br>
    <br>
    <b>ПОЛУФИНАЛЫ:</b><br>
    за 13-16 места</span></p>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Польша&nbsp;-&nbsp;Словакия
    - 5:6 в доп. время<br>

    США&nbsp;-&nbsp;Кипр - 5:9</span></p>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>за 9-12
    места<br>
    Югославия&nbsp;-&nbsp;Израиль - 4:1<br>
    Хорватия&nbsp;-&nbsp;Иран - 6:1</span></p>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>за 5-8 места<br>
    Бельгия&nbsp;-&nbsp;Испания - 2:5<br>
    Италия&nbsp;-&nbsp;Финляндия - 7:3</span></p>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>за 1-4 места<br>
    Бразилия&nbsp;-&nbsp;Португалия - 3:2<br>

    Украина&nbsp;-&nbsp;Россия - 2:3</span></b></p>
    </td>
   </tr>
   <tr>
    <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>ФИНАЛЫ:</span></b><span
    lang=EN-US style='font-size:12.0pt;font-family:"Times New Roman","serif"'><br>
    <span style='color:crimson'>Матч за 15-16 места</span><br>

    <b>Польша&nbsp;-&nbsp;США 4:2</b><br>
    <span style='color:crimson'>Матч за 13-14 места</span><br>
    <b>Словакия&nbsp;-&nbsp;Кипр -9:8 </b><br>
    <span style='color:crimson'>Матч за 11-12 места</span><br>
    <b>Израиль -&nbsp;Иран - 2:0 (Иран снялся)</b><br>

    <span style='color:crimson'>Матч за 9-10 места</span><br>
    <b>Хорватия&nbsp;-&nbsp;Югославия - 6:0</b><br>
    <span style='color:crimson'>Матч за 7-8места</span><br>
    <b>Бельгия&nbsp;-&nbsp;Финляндия - 4:2 </b><br>
    <span style='color:crimson'>Матч за 5-6 места</span><br>

    <b>Италия&nbsp;-&nbsp;Испания 1:0 в доп. время&nbsp;</b><br>
    <span style='color:crimson'>Матч за 3-4 места</span><br>
    <b>Украина&nbsp;-&nbsp;Португалия - 9:5 </b><br>
    <span style='color:crimson'>Матч за 1-2 места</span><br>
    <b>Россия&nbsp;-&nbsp;Бразилия - 5:6 в доп. время</b></span></p>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:18.0pt;font-family:"Times New Roman","serif";color:crimson'>Итоговый
    результат</span></p>
    <div align=center>
    <table class=MsoNormalTable border=1 cellpadding=0 width="25%"
     style='width:25.0%;background:gainsboro;border:outset black 1.5pt'>

     <tr>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Место</span></p>
      </td>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Страна</span></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Бразилия</span></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
      </td>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Россия</span></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Украина</span></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
      </td>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Португалия</span></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>5</span></p>
      </td>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Италия</span></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>6</span></p>
      </td>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Испания</span></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>7</span></p>
      </td>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Бельгия</span></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>8</span></p>
      </td>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Финляндия</span></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>9</span></p>
      </td>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Хорватия</span></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>10</span></p>
      </td>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Югославия</span></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>11</span></p>
      </td>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Израиль</span></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>12</span></p>
      </td>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Иран</span></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>13</span></p>
      </td>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Словакия</span></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>14</span></p>
      </td>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Кипр</span></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>15</span></p>
      </td>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Польша</span></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>16</span></p>
      </td>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>США</span></p>
      </td>
     </tr>

    </table>
    </div>
    </td>
   </tr>
  </table>
  </div>
  </td>
 </tr>
</table>

<p class=MsoNormal><span lang=EN-US>&nbsp;</span></p>

</div>
