<div class=Section1>

<p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
normal'><a name="_GoBack"><span lang=EN-US style='font-size:12.0pt;font-family:
"Times New Roman","serif"'>6 СТУДЕНЧЕСКИЙ ЧЕМПИОНАТ МИРА 1998</span></a></p>

<table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 width="100%"
 style='width:100.0%'>
 <tr>
  <td style='padding:1.5pt 1.5pt 1.5pt 1.5pt'>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span style='font-size:14.0pt;
  font-family:"Times New Roman","serif"'>6 СТУДЕНЧЕСКИЙ ЧЕМПИОНАТ МИРА 1998</span></b></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><span lang=EN-US style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'>&nbsp;</span></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'>ПОРТУГАЛИЯ, БРАГА</span></b></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><span lang=EN-US style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'>&nbsp;</span></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'>19-26 сентября 1998 года</span></b></p>

  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><span lang=EN-US style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'>&nbsp;</span></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><span style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'><img width=93 height=165 id="Рисунок 2"
  src="6%20____________%20_________%20____%201998.files/image001.gif"
  alt="http://futsal.ucoz.ru/_pu/2/78110.gif"></span><span lang=EN-US
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;<br>
  &nbsp;<br>
  </span><span lang=EN-US><a href="http://futsal.ucoz.ru/_pu/2/49521292.jpg"
  title="&quot;Нажмите, для просмотра в полном размере...&quot; t "><span
  lang=RU style='font-size:12.0pt;font-family:"Times New Roman","serif";
  color:blue;text-decoration:none'><img border=0 width=400 height=257
  id="Рисунок 1"
  src="6%20____________%20_________%20____%201998.files/image002.jpg"
  alt="http://futsal.ucoz.ru/_pu/2/s49521292.jpg"></span></a></span></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><span lang=EN-US style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'>&nbsp;</span></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span lang=EN-US style='font-size:
  12.0pt;font-family:"Times New Roman","serif"'>Россиястуденческая</span></b></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><span lang=EN-US style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'>&nbsp;</span></p>
  <div align=center>

  <table class=MsoNormalTable border=1 cellpadding=0 width="100%"
   style='width:100.0%;border:outset black 1.5pt'>
   <tr>
    <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:18.0pt;
    font-family:"Times New Roman","serif";color:crimson'>Групповые турниры</span><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'><br>
    </span><b><span lang=EN-US style='font-size:14.0pt;font-family:"Times New Roman","serif";
    color:blue'>&nbsp;</span></b></p>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    14.0pt;font-family:"Times New Roman","serif";color:blue'>Группа А</span></b><b><span
    lang=EN-US style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span></b></p>
    <div align=center>
    <table class=MsoNormalTable border=1 cellpadding=0 width="50%"
     style='width:50.0%;border:outset blue 1.5pt'>

     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>М</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>Команда</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>1</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>2</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>3</span></b></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>4</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>Мячи</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>О</span></b></p>
      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>Португалия</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'></td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>1:0</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>6:2</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>11:0</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>18-2</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>6</span></p>
      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>Хорватия</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>0:1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'></td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>4:2</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>7:2</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>13-5</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>Израиль</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>2:6</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>2:4</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'></td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>4:2</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>8-12</span></p>
      </td>

      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
      </td>

      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>Кипр</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>0:11</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>2:7</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>2:4</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'></td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>4-22</span></p>
      </td>

      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>
     </tr>
    </table>
    </div>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'><br>
    </span><b><span style='font-size:14.0pt;font-family:"Times New Roman","serif";
    color:blue'>Группа </span></b><b><span lang=EN-US style='font-size:14.0pt;
    font-family:"Times New Roman","serif";color:blue'>B</span></b></p>

    <div align=center>
    <table class=MsoNormalTable border=1 cellpadding=0 width="50%"
     style='width:50.0%;border:outset blue 1.5pt'>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>М</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>Команда</span></b></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>1</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>2</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>3</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>Мячи</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>О</span></b></p>

      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>Бразилия</span></b></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'></td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>10:3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>14:1</span></p>
      </td>

      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>24-4</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
      </td>
     </tr>
     <tr>

      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>Казахстан</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>3:10</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'></td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>5:3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>8-13</span></p>
      </td>

      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>

      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>Финляндия</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>1:14</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>3:5</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'></td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>4-19</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>

     </tr>
    </table>
    </div>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span></p>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    14.0pt;font-family:"Times New Roman","serif";color:blue'>Группа </span></b><b><span
    lang=EN-US style='font-size:14.0pt;font-family:"Times New Roman","serif";
    color:blue'>C</span></b></p>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    12.0pt;font-family:"Times New Roman","serif"'><br>
    <span style='color:red'>Россия-Ангола 11:3</span></span></b></p>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    12.0pt;font-family:"Times New Roman","serif";color:red'>Голы: Фадеев-2,Баранов-2,Малышев,Яшин-2,Григорьев-3,Иванов</span></b></p>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif";color:red'>&nbsp;</span></b></p>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    12.0pt;font-family:"Times New Roman","serif";color:red'>Россия-Польша 15:1</span></b></p>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    12.0pt;font-family:"Times New Roman","serif";color:red'>Голы:
    Баранов-2,Григорьев-2,Яшин,Купецков-2,Агафонов-3,</span></b></p>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    12.0pt;font-family:"Times New Roman","serif";color:red'>Малышев-4,Фадеев.</span></b></p>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif";color:red'>&nbsp;</span></b></p>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    12.0pt;font-family:"Times New Roman","serif";color:red'>Россия-Испания 3:2</span></b></p>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    12.0pt;font-family:"Times New Roman","serif";color:red'>Голы: Фадеев-2,Яшин</span></b></p>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span></b></p>
    <div align=center>
    <table class=MsoNormalTable border=1 cellpadding=0 width="50%"
     style='width:50.0%;border:outset blue 1.5pt'>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>М</span></b></p>
      </td>

      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>Команда</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>1</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>2</span></b></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>3</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>4</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>Мячи</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>О</span></b></p>
      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif";color:red'>Россия</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'></td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>3:2</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>15:1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>11:3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>29-6</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>6</span></p>
      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>Испания</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>2:3</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'></td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>14:1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>8:3</span></p>
      </td>

      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>24-7</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
      </td>
     </tr>
     <tr>

      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>Польша</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>1:15</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>1:14</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'></td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>4:2</span></p>
      </td>

      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>6-31</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
      </td>
     </tr>
     <tr>

      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>Ангола</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>3:11</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>3:8</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>2:4</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'></td>

      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>8-23</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>
     </tr>
    </table>

    </div>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span></p>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    14.0pt;font-family:"Times New Roman","serif";color:blue'>Группа </span></b><b><span
    lang=EN-US style='font-size:14.0pt;font-family:"Times New Roman","serif";
    color:blue'>D</span></b></p>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span></p>
    <div align=center>
    <table class=MsoNormalTable border=1 cellpadding=0 width="50%"
     style='width:50.0%;border:outset blue 1.5pt'>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>М</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Команда</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></b></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Мячи</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>О</span></b></p>
      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Украина</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'></td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>5:3</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>6:1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>11-4</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>6</span></p>
      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Венгрия</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3:5</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'></td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>5:5</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>8-10</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Италия</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1:6</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>5:5</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'></td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>6-11</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
     </tr>
    </table>
    </div>
    </td>

   </tr>
   <tr>
    <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    12.0pt;font-family:"Times New Roman","serif"'>ЧЕТВЕРТЬФИНАЛЫ:</span></b><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'><br>
    9-14 места:<br>
    Кипр</span><span lang=EN-US style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>-</span><span
    lang=EN-US style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Финляндия -
    3:4<br>

    Ангола</span><span lang=EN-US style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>-</span><span
    lang=EN-US style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Италия -3:8</span></p>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    12.0pt;font-family:"Times New Roman","serif"'>1-8 места:<br>
    Хорватия</span></b><b><span lang=EN-US style='font-size:12.0pt;font-family:
    "Times New Roman","serif"'>&nbsp;</span></b><b><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>-</span></b><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span></b><b><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Бразилия -
    3:3</span></b><b><span lang=EN-US style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span></b><b><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>по пенальти
    7:8</span></b></p>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    12.0pt;font-family:"Times New Roman","serif"'><br>
    <span style='color:red'>Россия</span></span></b><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif";color:red'>&nbsp;</span></b><b><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif";color:red'>-</span></b><b><span
    lang=EN-US style='font-size:12.0pt;font-family:"Times New Roman","serif";
    color:red'>&nbsp;</span></b><b><span style='font-size:12.0pt;font-family:
    "Times New Roman","serif";color:red'>Венгрия - 4:0</span></b></p>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    12.0pt;font-family:"Times New Roman","serif";color:red'>Голы:
    Малышев-2,Купецков,Панько</span></b></p>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    12.0pt;font-family:"Times New Roman","serif"'><br>
    Испания</span></b><b><span lang=EN-US style='font-size:12.0pt;font-family:
    "Times New Roman","serif"'>&nbsp;</span></b><b><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>-</span></b><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span></b><b><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Украина -
    4:4 по пенальти 9:10<br>
    Казахстан</span></b><b><span lang=EN-US style='font-size:12.0pt;font-family:
    "Times New Roman","serif"'>&nbsp;</span></b><b><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>- Португалия - 1:4</span></b></p>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span></p>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    12.0pt;font-family:"Times New Roman","serif"'>ПОЛУФИНАЛЫ:</span></b><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'><br>

    за 13-14 места<br>
    Кипр</span><span lang=EN-US style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>-</span><span
    lang=EN-US style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Ангола - 5:7
    после пенальти</span></p>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>за 9-12 места<br>
    Финляндия</span><span lang=EN-US style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>-</span><span
    lang=EN-US style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Италия - 2:7<br>
    Израиль</span><span lang=EN-US style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>-</span><span
    lang=EN-US style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Польша - 7:4</span></p>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>за 5-8 места<br>
    Хорватия</span><span lang=EN-US style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>-</span><span
    lang=EN-US style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Венгрия -
    6:8 после пенальти<br>
    Казахстан</span><span lang=EN-US style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>-</span><span
    lang=EN-US style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Испания -
    1:6</span></p>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    12.0pt;font-family:"Times New Roman","serif"'>за 1-4 места<br>
    Португалия</span></b><b><span lang=EN-US style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>&nbsp;</span></b><b><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>-</span></b><b><span
    lang=EN-US style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span></b><b><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Украина -
    1:6</span></b></p>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    12.0pt;font-family:"Times New Roman","serif"'><br>
    <span style='color:red'>Россия -</span></span></b><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif";color:red'>&nbsp;</span></b><b><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif";color:red'>Бразилия
    - 8:1</span></b></p>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    12.0pt;font-family:"Times New Roman","serif";color:red'>Голы: Малышев,Купецков,Яшин,Панько-3,Иванов-2</span></b></p>
    </td>
   </tr>
   <tr>
    <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    12.0pt;font-family:"Times New Roman","serif"'>ФИНАЛЫ:</span></b><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'><br>
    <br>
    <span style='color:crimson'>Матч за 11-12 места</span><br>
    <b>Финляндия</b></span><b><span lang=EN-US style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>&nbsp;</span></b><b><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>-</span></b><b><span
    lang=EN-US style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span></b><b><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Польша - 5:3</span></b><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'><br>
    <span style='color:crimson'>Матч за 9-10 места</span><br>
    <b>Италия</b></span><b><span lang=EN-US style='font-size:12.0pt;font-family:
    "Times New Roman","serif"'>&nbsp;</span></b><b><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>-</span></b><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span></b><b><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Израиль -
    1:5</span></b><span style='font-size:12.0pt;font-family:"Times New Roman","serif"'><br>

    <span style='color:crimson'>Матч за 7-8места</span><br>
    <b>Хорватия</b></span><b><span lang=EN-US style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>&nbsp;</span></b><b><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>-</span></b><b><span
    lang=EN-US style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span></b><b><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Казахстан -
    10:0 </span></b><span style='font-size:12.0pt;font-family:"Times New Roman","serif"'><br>
    <span style='color:crimson'>Матч за 5-6 места</span><br>
    <b>Венгрия</b></span><b><span lang=EN-US style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>&nbsp;</span></b><b><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>-</span></b><b><span
    lang=EN-US style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span></b><b><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Испания 1:4 </span></b><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'><br>
    <span style='color:crimson'>Матч за 3-4 места</span><br>

    <b>Португалия</b></span><b><span lang=EN-US style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>&nbsp;</span></b><b><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>-</span></b><b><span
    lang=EN-US style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span></b><b><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Бразилия -
    1:5 </span></b><span style='font-size:12.0pt;font-family:"Times New Roman","serif"'><br>
    <span style='color:crimson'>Матч за 1-2 места</span><br>
    <b><span style='color:red'>Россия</span></b></span><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif";color:red'>&nbsp;</span></b><b><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif";color:red'>-</span></b><b><span
    lang=EN-US style='font-size:12.0pt;font-family:"Times New Roman","serif";
    color:red'>&nbsp;</span></b><b><span style='font-size:12.0pt;font-family:
    "Times New Roman","serif";color:red'>Украина - 2:3 в доп.время</span></b></p>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif";color:red'>Голы:&nbsp;Фадеев,Панько</span></b></p>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:18.0pt;font-family:"Times New Roman","serif";color:crimson'>Итоговыйрезультат</span></p>
    <div align=center>
    <table class=MsoNormalTable border=1 cellpadding=0 width="25%"
     style='width:25.0%;background:gainsboro;border:outset black 1.5pt'>

     <tr>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Место</span></p>
      </td>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Страна</span></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Украина</span></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
      </td>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif";color:red'>Россия</span></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Бразилия</span></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
      </td>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Португалия</span></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>5</span></p>
      </td>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Испания</span></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>6</span></p>
      </td>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Венгрия</span></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>7</span></p>
      </td>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Хорватия</span></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>8</span></p>
      </td>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Казахстан</span></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>9</span></p>
      </td>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Израиль</span></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>10</span></p>
      </td>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Италия</span></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>11</span></p>
      </td>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Финляндия</span></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>12</span></p>
      </td>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Польша</span></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>13</span></p>
      </td>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Ангола</span></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>14</span></p>
      </td>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Кипр</span></p>
      </td>
     </tr>

    </table>
    </div>
    </td>
   </tr>
  </table>
  </div>
  </td>
 </tr>
</table>

<p class=MsoNormal><span lang=EN-US>&nbsp;</span></p>

</div>
