<div class=Section1>

<p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
normal'><a name="_GoBack"><span lang=EN-US style='font-size:12.0pt;font-family:
"Times New Roman","serif"'>8 СТУДЕНЧЕСКИЙ ЧЕМПИОНАТ МИРА 2002</span></a></p>

<table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 width="100%"
 style='width:100.0%'>
 <tr>
  <td style='padding:1.5pt 1.5pt 1.5pt 1.5pt'>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span lang=EN-US style='font-size:
  14.0pt;font-family:"Times New Roman","serif"'>СТУДЕНЧЕСКИЙ ЧЕМПИОНАТ МИРА
  2002</span></b></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><span lang=EN-US style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'>&nbsp;</span></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span lang=EN-US style='font-size:
  12.0pt;font-family:"Times New Roman","serif"'>Венгрия</span></b></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><span lang=EN-US style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'>&nbsp;</span></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><span style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'><img width=216 height=115
  id="Рисунок 1"
  src="http://futsal.ucoz.ru/_pu/2/90158.jpg"
  alt="http://futsal.ucoz.ru/_pu/2/90158.jpg"></span></p>

  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><span lang=EN-US style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'>&nbsp;</span></p>
  <div align=center>
  <table class=MsoNormalTable border=1 cellpadding=0 width="100%"
   style='width:100.0%;border:outset black 1.5pt'>
   <tr>
    <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:18.0pt;
    font-family:"Times New Roman","serif";color:crimson'>Групповые турниры</span><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'><br>
    </span><span style='font-size:14.0pt;font-family:"Times New Roman","serif";
    color:blue'>Группа А</span></p>
    <div align=center>

    <table class=MsoNormalTable border=1 cellpadding=0 width="50%"
     style='width:50.0%;border:outset blue 1.5pt'>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>М</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>Команда</span></b></p>
      </td>

      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>1</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>2</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>3</span></b></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>Мячи</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>О</span></b></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>Венгрия</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'></td>

      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>3:3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>20:0</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>23-3</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>2</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>Украина</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>3:3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'></td>

      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>19:2</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>22-5</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>4</span></p>

      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>Турция</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>0:20</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>2:19</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'></td>

      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>2-39</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>
     </tr>
    </table>

    </div>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    12.0pt;font-family:"Times New Roman","serif"'><br>
    </span></b><b><span style='font-size:14.0pt;font-family:"Times New Roman","serif";
    color:blue'>Группа </span></b><b><span lang=EN-US style='font-size:14.0pt;
    font-family:"Times New Roman","serif";color:blue'>B</span></b></p>
    <div align=center>
    <table class=MsoNormalTable border=1 cellpadding=0 width="50%"
     style='width:50.0%;border:outset blue 1.5pt'>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>М</span></b></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>Команда</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>1</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>2</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>3</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>Мячи</span></b></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>О</span></b></p>
      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>1</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>Италия</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'></td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>5:4</span></p>
      </td>

      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>9:2</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>14-6</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>6</span></p>

      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>Югославия</span></b></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>4:5</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'></td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>7:3</span></p>
      </td>

      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>11-8</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
     </tr>
     <tr>

      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>Польша</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>2:9</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>3:7</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'></td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>5-16</span></p>
      </td>

      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>
     </tr>
    </table>
    </div>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:14.0pt;font-family:"Times New Roman","serif";color:blue'>&nbsp;</span></b></p>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    14.0pt;font-family:"Times New Roman","serif";color:blue'>Группа </span></b><b><span
    lang=EN-US style='font-size:14.0pt;font-family:"Times New Roman","serif";
    color:blue'>C</span></b></p>

    <div align=center>
    <table class=MsoNormalTable border=1 cellpadding=0 width="50%"
     style='width:50.0%;border:outset blue 1.5pt'>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>М</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>Команда</span></b></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>1</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>2</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>3</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>Мячи</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>О</span></b></p>

      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>Россия</span></b></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'></td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>4:2</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>21:1</span></p>
      </td>

      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>25-3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>6</span></p>
      </td>
     </tr>
     <tr>

      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>Испания</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>2:4</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'></td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>12:1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>14-5</span></p>
      </td>

      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>

      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>Кипр</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>1:21</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>1:12</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'></td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>2-33</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>

     </tr>
    </table>
    </div>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:14.0pt;font-family:"Times New Roman","serif";color:blue'>&nbsp;</span></b></p>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    14.0pt;font-family:"Times New Roman","serif";color:blue'>Группа </span></b><b><span
    lang=EN-US style='font-size:14.0pt;font-family:"Times New Roman","serif";
    color:blue'>D</span></b></p>
    <div align=center>
    <table class=MsoNormalTable border=1 cellpadding=0 width="50%"
     style='width:50.0%;border:outset blue 1.5pt'>
     <tr>

      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>М</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Команда</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></b></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Мячи</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>О</span></b></p>
      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Португалия</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'></td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2:1</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>6:0</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>8-1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>6</span></p>
      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Израиль</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1:2</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'></td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>8:1</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>9-3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Казахстан</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0:6</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1:8</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'></td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1-14</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>
     </tr>
    </table>
    </div>
    </td>

   </tr>
   <tr>
    <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    12.0pt;font-family:"Times New Roman","serif"'>ЧЕТВЕРТЬФИНАЛЫ:</span></b><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'><br>
    9-12 места:<br>
    Турция -</span><span lang=EN-US style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Казахстан -
    4:6<br>
    Польша</span><span lang=EN-US style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>-</span><span
    lang=EN-US style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Кипр 11:2</span></p>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    12.0pt;font-family:"Times New Roman","serif"'>1-8 места:<br>
    Россия -</span></b><b><span lang=EN-US style='font-size:12.0pt;font-family:
    "Times New Roman","serif"'>&nbsp;</span></b><b><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>Югославия - 4:0<br>
    Португалия</span></b><b><span lang=EN-US style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>&nbsp;</span></b><b><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>- Украина -
    1:2<br>
    Италия</span></b><b><span lang=EN-US style='font-size:12.0pt;font-family:
    "Times New Roman","serif"'>&nbsp;</span></b><b><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>-</span></b><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span></b><b><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Испания -
    2:2 по пенальти 2:1<br>
    Венгрия</span></b><b><span lang=EN-US style='font-size:12.0pt;font-family:
    "Times New Roman","serif"'>&nbsp;</span></b><b><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>-</span></b><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span></b><b><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Израиль - 3:2</span></b></p>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'><br>
    <b>ПОЛУФИНАЛЫ:</b><br>
    за 9-12 места<br>
    Кипр</span><span lang=EN-US style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>-</span><span
    lang=EN-US style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Турция - 8:3</span></p>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>за 5-8 места<br>
    Испания</span><span lang=EN-US style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>- Португалия
    - 2:1<br>

    Израиль</span><span lang=EN-US style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>-</span><span
    lang=EN-US style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Югославия -
    1:5</span></p>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    12.0pt;font-family:"Times New Roman","serif"'>за 1-4 места<br>
    Венгрия</span></b><b><span lang=EN-US style='font-size:12.0pt;font-family:
    "Times New Roman","serif"'>&nbsp;</span></b><b><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>-</span></b><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span></b><b><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Россия - 0:2<br>
    Украина</span></b><b><span lang=EN-US style='font-size:12.0pt;font-family:
    "Times New Roman","serif"'>&nbsp;</span></b><b><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>-</span></b><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span></b><b><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Италия - 2:4</span></b></p>

    </td>
   </tr>
   <tr>
    <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    12.0pt;font-family:"Times New Roman","serif"'>ФИНАЛЫ:</span></b><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'><br>
    <span style='color:crimson'>Матч за 9-10 места</span><br>
    <b>Турция</b></span><b><span lang=EN-US style='font-size:12.0pt;font-family:
    "Times New Roman","serif"'>&nbsp;</span></b><b><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>-</span></b><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span></b><b><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Польша -
    3:21</span></b></p>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif";color:crimson'>Матч
    за 7-8 места</span><span lang=EN-US style='font-size:12.0pt;font-family:
    "Times New Roman","serif"'><br>
    <b>Португалия -&nbsp;Израиль - 6:3 </b><br>
    <span style='color:crimson'>Матч за 5-6 места</span><br>
    <b>Югославия&nbsp;-&nbsp;Испания 2:1 </b><br>
    <span style='color:crimson'>Матч за 3-4 места</span><br>

    <b>Венгрия&nbsp;-&nbsp;Украина - 3:5 </b><br>
    <span style='color:crimson'>Матч за 1-2 места</span><br>
    <b>Россия&nbsp;-&nbsp;Италия - 4:1</b></span></p>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span></p>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US><a
    href="http://www.rusfutsal.ru/CTUD_CHEMP_MIRA/SChM-2002-Vengrija.txt"><b><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>СТАТИСТИКА
    ТУРНИРА</span></b></a></span></p>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:18.0pt;font-family:"Times New Roman","serif";color:crimson'>Итоговый
    результат</span></p>
    <div align=center>
    <table class=MsoNormalTable border=1 cellpadding=0 width="25%"
     style='width:25.0%;background:gainsboro;border:outset black 1.5pt'>

     <tr>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Место</span></p>
      </td>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Страна</span></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Россия</span></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
      </td>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Италия</span></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Украина</span></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
      </td>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Венгрия</span></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>5</span></p>
      </td>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Югославия</span></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>6</span></p>
      </td>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Испания</span></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>7</span></p>
      </td>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Португалия</span></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>8</span></p>
      </td>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Израиль</span></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>9</span></p>
      </td>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Польша</span></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>10</span></p>
      </td>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Кипр</span></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>11</span></p>
      </td>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Турция</span></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>12</span></p>
      </td>
      <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Казахстан</span></p>
      </td>
     </tr>

    </table>
    </div>
    </td>
   </tr>
  </table>
  </div>
  </td>
 </tr>
</table>

<p class=MsoNormal><span lang=EN-US>&nbsp;</span></p>

</div>
