<div class=Section1>

<p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
normal'><a name="_GoBack"><span lang=EN-US style='font-size:12.0pt;font-family:
"Times New Roman","serif"'>10 СТУДЕНЧЕСКИЙ ЧЕМПИОНАТ МИРА 2006</span></a></p>

<table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 width="100%"
 style='width:100.0%'>
 <tr>
  <td style='padding:1.5pt 1.5pt 1.5pt 1.5pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  style='font-size:14.0pt;font-family:"Times New Roman","serif"'>10
  СТУДЕНЧЕСКИЙ ЧЕМПИОНАТ МИРА</span></b></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'>ПОЛЬША,
  ПОЗНАНЬ</span></b></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'>28 августа-2
  сентября 2006</span></b></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'><img
  width=216 height=239 id="Рисунок 1"
  src="http://futsal.ucoz.ru/_pu/2/86026.jpg"
  alt="http://futsal.ucoz.ru/_pu/2/86026.jpg"></span></b></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'>ФИНАЛ:</span></b></p>

  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Россия-Бразилия
  4:1</span></b></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Матч за 3
  место:</span></b></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Польша-Украина
  1:5</span></b></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Матч за 5
  место:</span></b></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Словения-Сербия
  и Черногория 4:4 по пенальти 1:4</span></b></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Матч за 7 место:</span></b></p>

  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Португалия-Чехия
  4:4 по пенальти 4:3</span></b></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Матч за 9
  место:</span></b></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Хорватия-Кыргызстан
  1:8</span></b></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Матч за 11
  место:</span></b></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Казахстан-Словакия
  7:9</span></b></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Матч за 13
  место:</span></b></p>

  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Марокко-Великобритания
  13:2</span></b></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Матч за 15
  место:</span></b></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Тайвань-Китай
  6:5</span></b></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'>ПОЛУФИНАЛЫ:</span></b></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Россия-Польша
  10:3</span></b></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Бразилия-Украина
  7:2</span></b></p>

  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'>ЧЕТВЕРТЬФИНАЛЫ:</span></b></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Россия-Словения
  5:1</span></b></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Сербия и
  Черногория-Украина 3:7</span></b></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Чехия-Бразилия
  1:5</span></b></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Польша-Португалия
  4:3</span></b></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'>ГРУППОВОЙ ЭТАП</span></b></p>

  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Группа А</span></b></p>
  <div align=center>
  <table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 width="100%"
   style='width:100.0%;border-collapse:collapse'>
   <tr>
    <td style='border:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>м</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>команда</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2</span></p>

    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>4</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>мячи</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>о</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>Польша</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>6:5</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>4:3</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>7:2</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>17-10</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>9</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>Сербия и Черногория</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>5:6</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>11:2</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>4:1</span></p>
    </td>

    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>20-9</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>6</span></p>
    </td>
   </tr>
   <tr>

    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>Казахстан</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3:4</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2:11</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>5:0</span></p>
    </td>

    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>10-15</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
   </tr>
   <tr>

    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>4</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>Тайвань</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2:7</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>1:4</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>0:5</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>

    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3-16</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>0</span></p>
    </td>
   </tr>
  </table>

  </div>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Группа В</span></b></p>
  <div align=center>
  <table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 width="100%"
   style='width:100.0%;border-collapse:collapse'>
   <tr>
    <td style='border:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>м</span></p>
    </td>

    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>команда</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>

    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>мячи</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>о</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Бразилия</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1:1</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>7:3</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>9:0</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>17-4</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>7</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Словения</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1:1</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1:1</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>12:4</span></p>
    </td>

    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>14-6</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>5</span></p>
    </td>
   </tr>
   <tr>

    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Словакия</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3:7</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1:1</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>15:2</span></p>
    </td>

    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>19-10</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>4</span></p>
    </td>
   </tr>
   <tr>

    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>4</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>Великобритания</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>0:9</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>4:12</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2:15</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>

    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>6-36</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>0</span></p>
    </td>
   </tr>
  </table>

  </div>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Группа С</span></b></p>
  <div align=center>
  <table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 width="100%"
   style='width:100.0%;border-collapse:collapse'>
   <tr>
    <td style='border:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>м</span></p>
    </td>

    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>команда</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2</span></p>

    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>4</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>мячи</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>о</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>Россия</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>5:3</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>21:3</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>15:4</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>41-10</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>9</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>Чехия</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3:5</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>6:3</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>6:2</span></p>
    </td>

    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>15-10</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>6</span></p>
    </td>
   </tr>
   <tr>

    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>Хорватия</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3:21</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3:6</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>7:6</span></p>
    </td>

    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>13-33</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
   </tr>
   <tr>

    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>4</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>Марокко</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>4:15</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2:6</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>6:7</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>

    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>12-28</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>0</span></p>
    </td>
   </tr>
  </table>

  </div>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Группа </span></b><b><span
  lang=EN-US style='font-size:12.0pt;font-family:"Times New Roman","serif"'>D</span></b></p>
  <div align=center>
  <table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 width="100%"
   style='width:100.0%;border-collapse:collapse'>
   <tr>
    <td style='border:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>м</span></p>

    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>команда</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></p>

    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>мячи</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>о</span></p>
    </td>
   </tr>

   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Украина</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>

    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>5:3</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>10:0</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>16:3</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>31-6</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>9</span></p>
    </td>
   </tr>

   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Португалия</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3:5</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>5:0</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>6:2</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>14-7</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>6</span></p>
    </td>
   </tr>

   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Кыргызстан</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0:10</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0:5</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4:4</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4-19</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
    </td>
   </tr>

   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Китай</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3:16</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2:6</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4:4</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>9-26</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
    </td>

   </tr>
  </table>
  </div>
  </td>
 </tr>
</table>

<p class=MsoNormal><span lang=EN-US>&nbsp;</span></p>

</div>
