<div class=Section1>

<p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
normal'><a name="_GoBack"><span lang=EN-US style='font-size:12.0pt;font-family:
"Times New Roman","serif"'>11 СТУДЕНЧЕСКИЙ ЧЕМПИОНАТ МИРА 2008</span></a></p>

<table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 width="100%"
 style='width:100.0%'>
 <tr>
  <td style='padding:1.5pt 1.5pt 1.5pt 1.5pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  style='font-size:14.0pt;font-family:"Times New Roman","serif"'>11
  СТУДЕНЧЕСКИЙ ЧЕМПИОНАТ МИРА 2008</span></b></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'>24-31 августа
  2008 года</span></b></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'>СЛОВЕНИЯ, КОПЕР</span></b></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><span lang=EN-US style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'>&nbsp;</span></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><span style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'><img width=152 height=199
  id="Рисунок 1"
  src="http://futsal.ucoz.ru/_pu/2/21508.jpg"
  alt="http://futsal.ucoz.ru/_pu/2/21508.jpg"></span></p>

  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'>ПОРТУГАЛИЯ-Чемпион</span></b></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'>ФИНАЛ:</span></b></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'>ПОРТУГАЛИЯ-УКРАИНА 5:1</span></b></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'><br>
  МАТЧ ЗА 3 МЕСТО:<br>
  СЕРБИЯ-СЛОВЕНИЯ 8:1<br>

  <br>
  ПОЛУФИНАЛЫ:<br>
  </span></b><b><span lang=EN-US style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span></b><b><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'><br>
  СЕРБИЯ-ПОРТУГАЛИЯ 1:7<br>
  СЛОВЕНИЯ-УКРАИНА 1:3<br>
  <br>
  ЧЕТВЕРТЬФИНАЛЫ:<br>

  </span></b><b><span lang=EN-US style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span></b><b><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'><br>
  УКРАИНА-ЧЕХИЯ 6:2<br>
  СЛОВЕНИЯ-УРУГВАЙ 5:3<br>
  БРАЗИЛИЯ-ПОРТУГАЛИЯ 0:1</span></b></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'>СЕРБИЯ-КИТАЙ 5:0</span></b></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'>ГРУППОВОЙ ЭТАП</span></b></p>

  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'>Группа А</span></b></p>
  <div align=center>
  <table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 width="100%"
   style='width:100.0%;border-collapse:collapse'>
   <tr>
    <td style='border:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>м</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>команда</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>

    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>мячи</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>о</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Словения</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>5:3</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4:3</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>5:0</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>14-6</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>9</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Китай</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3:5</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>5:5</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>9:1</span></p>
    </td>

    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>17-11</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
    </td>
   </tr>
   <tr>

    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Казахстан</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3:4</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>5:5</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>12:6</span></p>
    </td>

    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>20-15</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
    </td>
   </tr>
   <tr>

    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Великобритания</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0:5</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1:9</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>6:12</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>

    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>7-26</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
    </td>
   </tr>
  </table>

  </div>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span lang=EN-US style='font-size:
  12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span></b></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span lang=EN-US style='font-size:
  12.0pt;font-family:"Times New Roman","serif"'>Группа В</span></b></p>
  <div align=center>
  <table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 width="100%"
   style='width:100.0%;border-collapse:collapse'>
   <tr>
    <td style='border:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>м</span></p>

    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>команда</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></p>

    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>мячи</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>о</span></p>
    </td>
   </tr>

   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Бразилия</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>

    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>7:2</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3:2</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>23:1</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>33-5</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>9</span></p>
    </td>
   </tr>

   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Чехия</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2:7</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>8:6</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>14:1</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>24-14</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>6</span></p>
    </td>
   </tr>

   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Израиль</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2:3</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>6:8</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>13:0</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>21-11</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
    </td>
   </tr>

   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Малайзия</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1:23</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1:14</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0:13</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1-27</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
    </td>

   </tr>
  </table>
  </div>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span lang=EN-US style='font-size:
  12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span></b></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span lang=EN-US style='font-size:
  12.0pt;font-family:"Times New Roman","serif"'>Группа С</span></b></p>
  <div align=center>
  <table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 width="100%"
   style='width:100.0%;border-collapse:collapse'>
   <tr>

    <td style='border:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>м</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>команда</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>

    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>мячи</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>о</span></p>

    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Украина</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4:2</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4:1</span></p>
    </td>

    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4:0</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>12-3</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>9</span></p>

    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Португалия</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2:4</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1:1</span></p>
    </td>

    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4:0</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>7-5</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></p>

    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Словакия</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1:4</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1:1</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>

    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1:1</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3-6</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>

    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Кыргызстан</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0:4</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0:4</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1:1</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1-9</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>

    </td>
   </tr>
  </table>
  </div>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span lang=EN-US style='font-size:
  12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span></b></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span lang=EN-US style='font-size:
  12.0pt;font-family:"Times New Roman","serif"'>Группа D</span></b></p>
  <div align=center>
  <table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 width="100%"
   style='width:100.0%;border-collapse:collapse'>

   <tr>
    <td style='border:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>м</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>команда</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>

    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>мячи</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>о</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Сербия</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>7:1</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4:1</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>8:2</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>19-4</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>9</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Уругвай</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1:7</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3:2</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>6:5</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>10-14</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>6</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Франция</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1:4</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2:3</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>8:3</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>11-10</span></p>
    </td>

    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
    </td>

    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Турция</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2:8</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>5:6</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3:8</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>10-22</span></p>
    </td>

    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
    </td>
   </tr>
  </table>
  </div>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span lang=EN-US style='font-size:
  12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span></b></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span lang=EN-US style='font-size:
  12.0pt;font-family:"Times New Roman","serif"'><br>

  Классификация:<br>
  <br>
  1. Португалия<br>
  <br>
  2. Украина<br>
  <br>
  3. Сербия<br>

  <br>
  4. Словения<br>
  <br>
  5. Бразилия<br>
  <br>
  6. Чехия<br>
  <br>

  7. Китай<br>
  <br>
  8. Уругвай<br>
  <br>
  9. Словакия<br>
  <br>
  10. Израиль<br>

  <br>
  11. Франция<br>
  <br>
  12. Казахстан<br>
  <br>
  13. Турция<br>
  <br>

  14. Кыргызстан<br>
  <br>
  15. Великобритания<br>
  <br>
  16. Малайзия</span></b></p>
  </td>
 </tr>

</table>

<p class=MsoNormal><span lang=EN-US>&nbsp;</span></p>

</div>
