<div class="news_block_element">
	<h4 class="newshead">
		<span>Правила</span>
	</h4>
	<div class="grid_4">
		<a class="rules-link menutype-button" href="/rules">Правила футзала</a>
	<?php
		foreach($this->rules as $rule)
		{
	?>
			<a class="rules-link menutype-button" href="/rules/show/rule/<?php echo $rule->link ?>"><?php echo $rule->name ?></a>
	<?php
		}
	?>
	</div>
	<div class="grid_7">
		<h1>Правила футзала</h1>
		<p>
		<span style="font-size: 10pt; font-family: Verdana;">Целью этих дополнительных инструкций для арбитров, вторых арбитров, третьих арбитров и хронометристов является единообразное применение Правил игры в футзал.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-weight: 700;"><span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">Футзал</span></span><span style="font-size: 10pt; font-family: Verdana;"> &ndash; это спортивн</span><span style="font-size: 10pt; font-family: Verdana;">Целью этих дополнительных инструкций для арбитров, вторых арбитров, третьих арбитров и хронометристов является единообразное применение Правил игры в футзал.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-weight: 700;"><span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">Футзал</span></span><span style="font-size: 10pt; font-family: Verdana;"> &ndash; это спортивное соревнование и физический контакт между футболистами является нормальной и приемлемой частью игры. Однако футболисты должны играть в рамках Правил игры и соблюдать принципы честной игры.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Серьезное нарушение Правил игры и недисциплинированное поведение, включая недопустимые уровни физической агрессивности, являются нарушениями, наказуемые удалением с площадки в соответствии с Правилом 12.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-weight: 700;"><span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">Серьезное нарушение</span></span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Футболист виновен в серьезном нарушении, если применяет чрезмерную силу или грубость к сопернику в борьбе за мяч.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Любой футболист, атакующий соперника спереди, сбоку, или сзади одной или двумя ногами с чрезмерной силой, и подвергающий опасности соперника, виновен в серьезном нарушении Правил.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-weight: 700;"><span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">Недисциплинированное поведение</span></span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Недисциплинированное поведение возможно либо на площадке, либо за ее пределами, когда мяч в игре и не в игре. Футболист виновен в недисциплинированном поведении, если применяет чрезмерную силу или грубость к сопернику, когда не борется за мяч.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Кроме того, футболист виновен в недисциплинированном поведении, если применит чрезмерную силу или грубость к товарищу по команде или любому другому лицу.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-weight: 700;"><span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">Нарушения против вратарей</span></span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Напоминаем арбитрам, что: </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span></p>
	<ul>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">нарушением являются действия футболиста, мешающие вратарю произвести вбрасывание мяча в игру или освободиться от мяча, когда вратарь поймал мяч в руки с игры; </span></li>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">футболист должен быть наказан за опасную игру, если он бьет или попытается ударить по мячу в тот момент, когда вратарь вбрасывает мяч в игру; </span></li>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">нарушением является создание помех вратарю путем неправильной блокировки в момент выполнения углового удара.</span><br />
			<span style="font-size: 10pt; font-family: Verdana;"> </span></li>
	</ul>
	<p>
		<span style="font-weight: 700;"><span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">Прикрытие мяча</span></span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Если футболист, контролирующий мяч на игровом расстоянии, укрывает мяч от соперника корпусом, без использования рук, это не является нарушением.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Однако, если футболист мешает сопернику в борьбе за мяч, блокируя соперника, используя при этом кисть руки, руки, бедро или корпус, он должен быть наказан штрафным ударом или 6-ти метровым ударом, если совершил это нарушение в пределах своей штрафной площади.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-weight: 700;"><span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">Удар &laquo;ножницами&raquo;</span></span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Удар &laquo;ножницами&raquo; допустим при условии, что, по мнению арбитра, он не представляет опасности для соперников.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-weight: 700;"><span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">Умышленная игра рукой</span></span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Напоминаем арбитрам, что умышленная игра рукой обычно наказывается только штрафным ударом или ударом с 6-ти метровой отметки, если нарушение произошло в пределах штрафной площади.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Предупреждение или удаление обычно не выносится.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-weight: 700;"><span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">Лишение явной возможности взятия ворот</span></span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Тем не менее, футболист удаляется с площадки, если он предотвращает взятие ворот или явную возможность забить гол, умышленно сыграв в мяч рукой. Это наказание по Правилам вытекает не из того факта, что футболист умышленно играет рукой, а из того недопустимого и нечестного вмешательства, которое не дает сопернику забить гол.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-weight: 700;"><span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">Предупреждение за неспортивное поведение в виде умышленной игры рукой</span></span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Бывают обстоятельства, когда, вдобавок, к назначенному штрафному или свободному удару, футболисту нужно сделать предупреждение за неспортивное поведение, например, когда футболист: </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span></p>
	<ul>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">умышленно и явно играет рукой, чтобы помешать сопернику овладеть мячом; </span></li>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">пытается забить мяч, умышленно играя рукой.</span><br />
			<span style="font-size: 10pt; font-family: Verdana;"> </span></li>
	</ul>
	<p>
		<span style="font-weight: 700;"><span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">Задержка соперника</span></span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Распространена критика арбитров за их неспособность правильно определить и назначить наказание за задержку соперника. Неспособность правильно реагировать на ситуацию, когда футболиста хватают за футболку или за руку, может привести к развитию ситуации противостояния. Арбитров, в соответствии с Правилом 12, просят вмешиваться в ситуацию на раннем этапе и при этом вести себя решительно. Штрафной удар или 6-ти метровый удар &ndash; это обычно все, что требуется для наказания, но в определенных обстоятельствах бывает необходима дополнительная санкция, например: </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span></p>
	<ul>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">требуется вынести предупреждение за неспортивное поведение, когда футболист задерживает соперника, мешая ему завладеть мячом или занять удобную позицию; </span></li>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">футболиста нужно удалить с площадки, если он задерживает соперника, тем самим лишает его явной возможности забить гол.</span><br />
			<span style="font-size: 10pt; font-family: Verdana;"> </span></li>
	</ul>
	<p>
		<span style="font-weight: 700;"><span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">Принцип преимущества</span></span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Когда команда имеет пять командных фолов и совершила шестое нарушение, наказуемое штрафным ударом или 6-ти метровым ударом, арбитры должны наказать команду за это нарушение. В этом случае можно применить &laquo;принцип преимущества&raquo; только тогда, когда команда, против которой совершено нарушение, имеет явную возможность забить мяч.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Однако, если произошло нарушение, наказуемое штрафным ударом, согласно Правилу 12, арбитры могут попытаться продолжить игру, применив &laquo;принцип преимущества&raquo;, но только без ущерба команде против которой было совершено нарушение.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-weight: 700;"><span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">Выполнение штрафного или свободного ударов</span></span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Напоминаем арбитрам, что необходимо вынести предупреждение футболисту, если он: </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span></p>
	<ul>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">не соблюдает необходимое расстояние при возобновлении игры.</span><br />
			<span style="font-size: 10pt; font-family: Verdana;"> </span></li>
	</ul>
	<p>
		<span style="font-weight: 700;"><span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">6-ти метровый удар</span></span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Запрещено всем футболистам при пробитии 6-ти метрового удара находиться ближе пяти метров от 6-ти метровой отметки. Вратарь тоже нарушает Правила игры, если он сдвигается с линии ворот вперед до выполнения 6-ти метрового удара.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Арбитры должны гарантировать принятие соответствующих мер при нарушении данного Правила.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-weight: 700;"><span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">Удар с 10-ти метровой отметки и удар без использования стенки</span></span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Запрещено голкиперу, перед ударом, находиться ближе пяти метров от мяча, и стоять за пределами своей штрафной площади.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Все остальные футболисты, кроме футболиста, пробивающего удар, находятся на площадке позади воображаемой линии, проходящей через центр мяча, находящегося на точке, с которой пробивается удар без использования стенки, параллельно линии ворот. Эти футболисты должны находиться вне штрафной площади и не ближе 5 метров от мяча, они не имеют права создавать препятствия выполнению удара.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-weight: 700;"><span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">Нарушение Правил со стороны вратарей</span></span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Напоминаем арбитрам, если вратарь касается или контролирует мяч руками или ногами более четырех секунд в любой точке игровой площадки, за исключением чужой половины площадки, за такое нарушение вратаря наказывают свободным ударом* (см. стр. 3).</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-weight: 700;"><span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">Систематическое нарушение Правил</span></span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Арбитры должны быть внимательны к футболистам, систематически нарушающим Правила игры. В частности, необходимо знать, что даже если футболист допускает целый ряд различных нарушений, он все равно заслуживает предупреждения за систематическое нарушение Правил игры.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-weight: 700;"><span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">Отношение к арбитрам</span></span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">В соответствии с Правилами игры капитан не имеет особого статуса или привилегии, но он несет определенную долю ответственности за поведение своей команды.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Футболист, несогласный с решением арбитра и выражающий по этому поводу протест, должен быть предупрежден.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Любой футболист, который угрожает арбитру физическим воздействием, использует оскорбительные, обидные или нецензурные выражения и/или жесты, должен быть удален с площадки.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-weight: 700;"><span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">Симуляция</span></span><span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Любой футболист, который пытается ввести в заблуждение арбитра мнимой травмой или притворяется, что против него было совершено нарушение, виновен в симуляции и должен быть предупрежден за неспортивное поведение. Если матч был остановлен в результате этого нарушения, игра возобновляется свободным ударом с места нарушения* (см. стр. 3).</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-weight: 700;"><span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">Задержка возобновления игры</span></span><span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Арбитры должны выносить предупреждение футболистам, тактически задерживающим возобновление игры, как например: </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span></p>
	<ul>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">футболист выполняет штрафной или свободный удары не с места нарушения с единственным намерением заставить арбитра назначить повторное выполнение; </span></li>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">отбрасывает мяч или держит его у себя, после остановки игры арбитром.</span><br />
			<span style="font-size: 10pt; font-family: Verdana;"> </span></li>
	</ul>
	<p>
		<span style="font-weight: 700;"><span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">Празднование по поводу забитого мяча</span></span><span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Хотя футболисту разрешено выражать радость по поводу забитого мяча, празднование не должно быть чрезмерным.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">В циркуляре ФИФА № 579 уточняется, что разумные празднества разрешены. Практика празднеств с хореографическими элементами не поощряется, когда приводит к избыточным затратам времени, поэтому арбитры, в таких случаях, должны вмешиваться.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-weight: 700;"><span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">Футболисты должны быть предупреждены, если, по мнению арбитра:</span></span><span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span></p>
	<ul>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">они пользуются жестами, имеющими провокационный, комический или подстрекательный смысл; </span></li>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">покидают площадку и взбираются на трибуны отпраздновать вместе с болельщиками радость по поводу забитого мяча;</span></li>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">празднуя, натягивают футболку на свою голову.</span><br />
			<span style="font-size: 10pt; font-family: Verdana;"> </span></li>
	</ul>
	<p>
		<span style="font-size: 10pt; font-family: Verdana;">Тот факт, что футболисты покидают площадку по поводу празднования забитого мяча, сам по себе не заслуживает предупреждения, но важно, чтобы футболисты возвращались на площадку как можно скорее.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">От арбитров требуются профилактические действия и здравый смысл в ситуациях, когда выражается радость по поводу забитого мяча.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-weight: 700;"><span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">Освежительные напитки</span></span><span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Футболисты имеют право пить освежительные напитки во время остановки матча, но только находясь за боковой линией. Запрещается бросать на площадку пластиковые или любые другие контейнеры с водой.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-weight: 700;"><span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">Основная экипировка футболистов</span></span><span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">Вратарь:</span><span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span></p>
	<ul>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">одежда каждого вратаря по цвету должна отличаться от одежды других футболистов и арбитров; </span></li>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">если рубашки обоих вратарей одного цвета и не у одного из них нет другой футболки, чтобы переодеться, арбитр начинает игру.</span><br />
			<span style="font-size: 10pt; font-family: Verdana;"> </span></li>
	</ul>
	<p>
		<span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">Неосновная экипировка футболистов:</span><span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span></p>
	<ul>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">футболист не должен использовать в своей экипировке или носить какие-либо предметы, представляющие опасность как для себя самого, так и для другого футболиста; </span></li>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">футболисты могут пользоваться защитными приспособлениями, такими как наколенники или налокотники, маски на лице или повязки на голове при условии, если они не представляют опасности; </span></li>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">обычно считается, что современные спортивные очки, изготовленные из пластика или аналогичного материала, не представляют опасности и предположительно, арбитры должны разрешать их ношение при подобных обстоятельствах.</span><br />
			<span style="font-size: 10pt; font-family: Verdana;"> </span></li>
	</ul>
	<p>
		<span style="font-weight: 700;"><span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">Безопасность</span></span><span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;"> Футболист не должен использовать в своей экипировке или носить предметы (это относится также к ювелирным изделиям), представляющие опасность как для себя самого, так и для других футболистов.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-weight: 700;"><span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">Ювелирные изделия</span></span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Все виды ювелирных изделий потенциально опасны. Использование пластыря (ленты) для покрытия ювелирных изделий недопустимо.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Кольца, сережки, даже сделанные из кожи или резины, не являются необходимыми для футболистов и могут также служить причиной травмы.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Термин &laquo;опасный&raquo; в разное время является спорным и неоднозначным. Но, в интересах однородности и последовательности, футболисты, запасные и арбитры не должны носить любого вида ювелирные изделия или украшения.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Чтобы избежать проблемы &laquo;последней минуты&raquo;, арбитры должны проинформировать футболистов об этих требованиях заранее.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-weight: 700;"><span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">Вопросы, связанные с травмированными футболистами</span></span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Арбитры обязаны соблюдать следующие инструкции в вопросах, связанных с травмированными футболистами: </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span></p>
	<ul>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">игра может продолжаться до момента выхода мяча из игры, если футболист, по мнению арбитра, травмирован незначительно;</span></li>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">игра останавливается, если футболист, по его мнению, серьезно травмирован; </span></li>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">после беседы с травмированным футболистом арбитр вызывает одного или максимум двух врачей, которые выходят на площадку, чтобы определить вид травмы и обеспечить безопасную и быструю эвакуацию футболиста с площадки; </span></li>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">если необходимо, санитары с носилками должны выходить на площадку одновременно с врачами, чтобы обеспечить максимально быструю эвакуацию футболиста с площадки; </span></li>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">оказание медицинской помощи футболистам на площадке запрещено, любой футболист, с кровоточащей раной, должен покинуть площадку. Он не может возвратиться на площадку, пока арбитр не убедится, что кровотечение прекратилось; </span></li>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">как только врачи вышли на площадку, футболист должен покинуть площадку либо на носилках, либо своим ходом. Если футболист не выполняет эту инструкцию, ему выносится предупреждение за неспортивное поведение; </span></li>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">травмированный футболист может вернуться на площадку только после возобновления матча; </span></li>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">только арбитры имеют право разрешить травмированному футболисту вернуться на площадку, независимо от того, мяч в игре или не в игре; </span></li>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">когда мяч в игре, травмированный футболист может вернуться на площадку только через боковую линию; </span></li>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">если игру не остановили по другой причине или если травма футболиста не является результатом нарушения Правил игры, арбитры возобновляют игру, вбрасывая &laquo;спорный мяч&raquo; в месте, где был мяч, когда игра была прервана* (см. стр. 3).</span><br />
			<span style="font-size: 10pt; font-family: Verdana;"> </span></li>
	</ul>
	<p>
		<span style="font-weight: 700;"><span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">Исключения</span></span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Исключения из этого Правила делаются только в случаях: </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span></p>
	<ul>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">травмы вратаря; </span></li>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">столкновения вратаря и футболиста, которым необходима немедленная помощь; </span></li>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">серьезной травмы, например: западение языка, сотрясение, перелом ноги и т.д.</span></li>
	</ul>
	<p>
		<span style="font-size: 10pt; font-family: Verdana;">ое соревнование и физический контакт между футболистами является нормальной и приемлемой частью игры. Однако футболисты должны играть в рамках Правил игры и соблюдать принципы честной игры.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Серьезное нарушение Правил игры и недисциплинированное поведение, включая недопустимые уровни физической агрессивности, являются нарушениями, наказуемые удалением с площадки в соответствии с Правилом 12.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-weight: 700;"><span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">Серьезное нарушение</span></span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Футболист виновен в серьезном нарушении, если применяет чрезмерную силу или грубость к сопернику в борьбе за мяч.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Любой футболист, атакующий соперника спереди, сбоку, или сзади одной или двумя ногами с чрезмерной силой, и подвергающий опасности соперника, виновен в серьезном нарушении Правил.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-weight: 700;"><span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">Недисциплинированное поведение</span></span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Недисциплинированное поведение возможно либо на площадке, либо за ее пределами, когда мяч в игре и не в игре. Футболист виновен в недисциплинированном поведении, если применяет чрезмерную силу или грубость к сопернику, когда не борется за мяч.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Кроме того, футболист виновен в недисциплинированном поведении, если применит чрезмерную силу или грубость к товарищу по команде или любому другому лицу.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-weight: 700;"><span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">Нарушения против вратарей</span></span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Напоминаем арбитрам, что: </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span></p>
	<ul>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">нарушением являются действия футболиста, мешающие вратарю произвести вбрасывание мяча в игру или освободиться от мяча, когда вратарь поймал мяч в руки с игры; </span></li>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">футболист должен быть наказан за опасную игру, если он бьет или попытается ударить по мячу в тот момент, когда вратарь вбрасывает мяч в игру; </span></li>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">нарушением является создание помех вратарю путем неправильной блокировки в момент выполнения углового удара.</span><br />
			<span style="font-size: 10pt; font-family: Verdana;"> </span></li>
	</ul>
	<p>
		<span style="font-weight: 700;"><span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">Прикрытие мяча</span></span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Если футболист, контролирующий мяч на игровом расстоянии, укрывает мяч от соперника корпусом, без использования рук, это не является нарушением.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Однако, если футболист мешает сопернику в борьбе за мяч, блокируя соперника, используя при этом кисть руки, руки, бедро или корпус, он должен быть наказан штрафным ударом или 6-ти метровым ударом, если совершил это нарушение в пределах своей штрафной площади.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-weight: 700;"><span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">Удар &laquo;ножницами&raquo;</span></span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Удар &laquo;ножницами&raquo; допустим при условии, что, по мнению арбитра, он не представляет опасности для соперников.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-weight: 700;"><span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">Умышленная игра рукой</span></span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Напоминаем арбитрам, что умышленная игра рукой обычно наказывается только штрафным ударом или ударом с 6-ти метровой отметки, если нарушение произошло в пределах штрафной площади.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Предупреждение или удаление обычно не выносится.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-weight: 700;"><span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">Лишение явной возможности взятия ворот</span></span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Тем не менее, футболист удаляется с площадки, если он предотвращает взятие ворот или явную возможность забить гол, умышленно сыграв в мяч рукой. Это наказание по Правилам вытекает не из того факта, что футболист умышленно играет рукой, а из того недопустимого и нечестного вмешательства, которое не дает сопернику забить гол.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-weight: 700;"><span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">Предупреждение за неспортивное поведение в виде умышленной игры рукой</span></span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Бывают обстоятельства, когда, вдобавок, к назначенному штрафному или свободному удару, футболисту нужно сделать предупреждение за неспортивное поведение, например, когда футболист: </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span></p>
	<ul>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">умышленно и явно играет рукой, чтобы помешать сопернику овладеть мячом; </span></li>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">пытается забить мяч, умышленно играя рукой.</span><br />
			<span style="font-size: 10pt; font-family: Verdana;"> </span></li>
	</ul>
	<p>
		<span style="font-weight: 700;"><span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">Задержка соперника</span></span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Распространена критика арбитров за их неспособность правильно определить и назначить наказание за задержку соперника. Неспособность правильно реагировать на ситуацию, когда футболиста хватают за футболку или за руку, может привести к развитию ситуации противостояния. Арбитров, в соответствии с Правилом 12, просят вмешиваться в ситуацию на раннем этапе и при этом вести себя решительно. Штрафной удар или 6-ти метровый удар &ndash; это обычно все, что требуется для наказания, но в определенных обстоятельствах бывает необходима дополнительная санкция, например: </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span></p>
	<ul>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">требуется вынести предупреждение за неспортивное поведение, когда футболист задерживает соперника, мешая ему завладеть мячом или занять удобную позицию; </span></li>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">футболиста нужно удалить с площадки, если он задерживает соперника, тем самим лишает его явной возможности забить гол.</span><br />
			<span style="font-size: 10pt; font-family: Verdana;"> </span></li>
	</ul>
	<p>
		<span style="font-weight: 700;"><span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">Принцип преимущества</span></span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Когда команда имеет пять командных фолов и совершила шестое нарушение, наказуемое штрафным ударом или 6-ти метровым ударом, арбитры должны наказать команду за это нарушение. В этом случае можно применить &laquo;принцип преимущества&raquo; только тогда, когда команда, против которой совершено нарушение, имеет явную возможность забить мяч.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Однако, если произошло нарушение, наказуемое штрафным ударом, согласно Правилу 12, арбитры могут попытаться продолжить игру, применив &laquo;принцип преимущества&raquo;, но только без ущерба команде против которой было совершено нарушение.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-weight: 700;"><span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">Выполнение штрафного или свободного ударов</span></span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Напоминаем арбитрам, что необходимо вынести предупреждение футболисту, если он: </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span></p>
	<ul>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">не соблюдает необходимое расстояние при возобновлении игры.</span><br />
			<span style="font-size: 10pt; font-family: Verdana;"> </span></li>
	</ul>
	<p>
		<span style="font-weight: 700;"><span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">6-ти метровый удар</span></span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Запрещено всем футболистам при пробитии 6-ти метрового удара находиться ближе пяти метров от 6-ти метровой отметки. Вратарь тоже нарушает Правила игры, если он сдвигается с линии ворот вперед до выполнения 6-ти метрового удара.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Арбитры должны гарантировать принятие соответствующих мер при нарушении данного Правила.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-weight: 700;"><span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">Удар с 10-ти метровой отметки и удар без использования стенки</span></span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Запрещено голкиперу, перед ударом, находиться ближе пяти метров от мяча, и стоять за пределами своей штрафной площади.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Все остальные футболисты, кроме футболиста, пробивающего удар, находятся на площадке позади воображаемой линии, проходящей через центр мяча, находящегося на точке, с которой пробивается удар без использования стенки, параллельно линии ворот. Эти футболисты должны находиться вне штрафной площади и не ближе 5 метров от мяча, они не имеют права создавать препятствия выполнению удара.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-weight: 700;"><span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">Нарушение Правил со стороны вратарей</span></span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Напоминаем арбитрам, если вратарь касается или контролирует мяч руками или ногами более четырех секунд в любой точке игровой площадки, за исключением чужой половины площадки, за такое нарушение вратаря наказывают свободным ударом* (см. стр. 3).</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-weight: 700;"><span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">Систематическое нарушение Правил</span></span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Арбитры должны быть внимательны к футболистам, систематически нарушающим Правила игры. В частности, необходимо знать, что даже если футболист допускает целый ряд различных нарушений, он все равно заслуживает предупреждения за систематическое нарушение Правил игры.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-weight: 700;"><span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">Отношение к арбитрам</span></span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">В соответствии с Правилами игры капитан не имеет особого статуса или привилегии, но он несет определенную долю ответственности за поведение своей команды.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Футболист, несогласный с решением арбитра и выражающий по этому поводу протест, должен быть предупрежден.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Любой футболист, который угрожает арбитру физическим воздействием, использует оскорбительные, обидные или нецензурные выражения и/или жесты, должен быть удален с площадки.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-weight: 700;"><span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">Симуляция</span></span><span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Любой футболист, который пытается ввести в заблуждение арбитра мнимой травмой или притворяется, что против него было совершено нарушение, виновен в симуляции и должен быть предупрежден за неспортивное поведение. Если матч был остановлен в результате этого нарушения, игра возобновляется свободным ударом с места нарушения* (см. стр. 3).</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-weight: 700;"><span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">Задержка возобновления игры</span></span><span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Арбитры должны выносить предупреждение футболистам, тактически задерживающим возобновление игры, как например: </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span></p>
	<ul>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">футболист выполняет штрафной или свободный удары не с места нарушения с единственным намерением заставить арбитра назначить повторное выполнение; </span></li>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">отбрасывает мяч или держит его у себя, после остановки игры арбитром.</span><br />
			<span style="font-size: 10pt; font-family: Verdana;"> </span></li>
	</ul>
	<p>
		<span style="font-weight: 700;"><span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">Празднование по поводу забитого мяча</span></span><span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Хотя футболисту разрешено выражать радость по поводу забитого мяча, празднование не должно быть чрезмерным.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">В циркуляре ФИФА № 579 уточняется, что разумные празднества разрешены. Практика празднеств с хореографическими элементами не поощряется, когда приводит к избыточным затратам времени, поэтому арбитры, в таких случаях, должны вмешиваться.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-weight: 700;"><span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">Футболисты должны быть предупреждены, если, по мнению арбитра:</span></span><span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span></p>
	<ul>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">они пользуются жестами, имеющими провокационный, комический или подстрекательный смысл; </span></li>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">покидают площадку и взбираются на трибуны отпраздновать вместе с болельщиками радость по поводу забитого мяча;</span></li>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">празднуя, натягивают футболку на свою голову.</span><br />
			<span style="font-size: 10pt; font-family: Verdana;"> </span></li>
	</ul>
	<p>
		<span style="font-size: 10pt; font-family: Verdana;">Тот факт, что футболисты покидают площадку по поводу празднования забитого мяча, сам по себе не заслуживает предупреждения, но важно, чтобы футболисты возвращались на площадку как можно скорее.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">От арбитров требуются профилактические действия и здравый смысл в ситуациях, когда выражается радость по поводу забитого мяча.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-weight: 700;"><span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">Освежительные напитки</span></span><span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Футболисты имеют право пить освежительные напитки во время остановки матча, но только находясь за боковой линией. Запрещается бросать на площадку пластиковые или любые другие контейнеры с водой.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-weight: 700;"><span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">Основная экипировка футболистов</span></span><span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">Вратарь:</span><span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span></p>
	<ul>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">одежда каждого вратаря по цвету должна отличаться от одежды других футболистов и арбитров; </span></li>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">если рубашки обоих вратарей одного цвета и не у одного из них нет другой футболки, чтобы переодеться, арбитр начинает игру.</span><br />
			<span style="font-size: 10pt; font-family: Verdana;"> </span></li>
	</ul>
	<p>
		<span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">Неосновная экипировка футболистов:</span><span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span></p>
	<ul>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">футболист не должен использовать в своей экипировке или носить какие-либо предметы, представляющие опасность как для себя самого, так и для другого футболиста; </span></li>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">футболисты могут пользоваться защитными приспособлениями, такими как наколенники или налокотники, маски на лице или повязки на голове при условии, если они не представляют опасности; </span></li>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">обычно считается, что современные спортивные очки, изготовленные из пластика или аналогичного материала, не представляют опасности и предположительно, арбитры должны разрешать их ношение при подобных обстоятельствах.</span><br />
			<span style="font-size: 10pt; font-family: Verdana;"> </span></li>
	</ul>
	<p>
		<span style="font-weight: 700;"><span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">Безопасность</span></span><span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;"> Футболист не должен использовать в своей экипировке или носить предметы (это относится также к ювелирным изделиям), представляющие опасность как для себя самого, так и для других футболистов.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-weight: 700;"><span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">Ювелирные изделия</span></span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Все виды ювелирных изделий потенциально опасны. Использование пластыря (ленты) для покрытия ювелирных изделий недопустимо.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Кольца, сережки, даже сделанные из кожи или резины, не являются необходимыми для футболистов и могут также служить причиной травмы.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Термин &laquo;опасный&raquo; в разное время является спорным и неоднозначным. Но, в интересах однородности и последовательности, футболисты, запасные и арбитры не должны носить любого вида ювелирные изделия или украшения.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Чтобы избежать проблемы &laquo;последней минуты&raquo;, арбитры должны проинформировать футболистов об этих требованиях заранее.</span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-weight: 700;"><span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">Вопросы, связанные с травмированными футболистами</span></span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Арбитры обязаны соблюдать следующие инструкции в вопросах, связанных с травмированными футболистами: </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span></p>
	<ul>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">игра может продолжаться до момента выхода мяча из игры, если футболист, по мнению арбитра, травмирован незначительно;</span></li>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">игра останавливается, если футболист, по его мнению, серьезно травмирован; </span></li>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">после беседы с травмированным футболистом арбитр вызывает одного или максимум двух врачей, которые выходят на площадку, чтобы определить вид травмы и обеспечить безопасную и быструю эвакуацию футболиста с площадки; </span></li>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">если необходимо, санитары с носилками должны выходить на площадку одновременно с врачами, чтобы обеспечить максимально быструю эвакуацию футболиста с площадки; </span></li>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">оказание медицинской помощи футболистам на площадке запрещено, любой футболист, с кровоточащей раной, должен покинуть площадку. Он не может возвратиться на площадку, пока арбитр не убедится, что кровотечение прекратилось; </span></li>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">как только врачи вышли на площадку, футболист должен покинуть площадку либо на носилках, либо своим ходом. Если футболист не выполняет эту инструкцию, ему выносится предупреждение за неспортивное поведение; </span></li>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">травмированный футболист может вернуться на площадку только после возобновления матча; </span></li>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">только арбитры имеют право разрешить травмированному футболисту вернуться на площадку, независимо от того, мяч в игре или не в игре; </span></li>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">когда мяч в игре, травмированный футболист может вернуться на площадку только через боковую линию; </span></li>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">если игру не остановили по другой причине или если травма футболиста не является результатом нарушения Правил игры, арбитры возобновляют игру, вбрасывая &laquo;спорный мяч&raquo; в месте, где был мяч, когда игра была прервана* (см. стр. 3).</span><br />
			<span style="font-size: 10pt; font-family: Verdana;"> </span></li>
	</ul>
	<p>
		<span style="font-weight: 700;"><span style="font-size: 10pt; text-decoration: underline; font-family: Verdana;">Исключения</span></span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span><span style="font-size: 10pt; font-family: Verdana;">Исключения из этого Правила делаются только в случаях: </span><br />
		<span style="font-size: 10pt; font-family: Verdana;"> </span></p>
	<ul>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">травмы вратаря; </span></li>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">столкновения вратаря и футболиста, которым необходима немедленная помощь; </span></li>
		<li>
			<span style="font-size: 10pt; font-style: italic; font-family: Verdana;">серьезной травмы, например: западение языка, сотрясение, перелом ноги и т.д.</span></li>
	</ul>
	
	</div>
	<div class="clear"></div>
</div>