<div class=Section1>

<p class=MsoNormal><b><span style='font-family:"Arial","sans-serif"'>Футзал.
Кубок Украины</span></b></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>&nbsp;</span></b></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>Все обладатели Кубка</span></b></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>&nbsp;</span></b></p>

<table class=MsoTableGrid border=1 cellspacing=0 cellpadding=0
 style='border-collapse:collapse;border:none'>
 <tr>
  <td valign=top style='border:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><i><span style='font-size:10.0pt'>сезон</span></i></p>
  </td>

  <td valign=top style='border:solid windowtext 1.0pt;border-left:none;
  padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><i><span style='font-size:10.0pt'>победитель</span></i></p>
  </td>
 </tr>
 <tr>
  <td valign=top style='border:solid windowtext 1.0pt;border-top:none;
  padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>1992/1993</span></p>
  </td>

  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>СКИФ-Силекс (Киев)</span></p>
  </td>
 </tr>
 <tr>
  <td valign=top style='border:solid windowtext 1.0pt;border-top:none;
  padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>1993/1994</span></p>
  </td>

  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>Ника (Днепропетровск)</span></p>
  </td>
 </tr>
 <tr>
  <td valign=top style='border:solid windowtext 1.0pt;border-top:none;
  padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>1994/1995</span></p>
  </td>

  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>Механизатор
  (Днепропетровск)</span></p>
  </td>
 </tr>
 <tr>
  <td valign=top style='border:solid windowtext 1.0pt;border-top:none;
  padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>1995/1996</span></p>
  </td>

  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>Механизатор
  (Днепропетровск)</span></p>
  </td>
 </tr>
 <tr>
  <td valign=top style='border:solid windowtext 1.0pt;border-top:none;
  padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>1996/1997</span></p>
  </td>

  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>Локомотив (Одесса)</span></p>
  </td>
 </tr>
 <tr>
  <td valign=top style='border:solid windowtext 1.0pt;border-top:none;
  padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>1997/1998</span></p>
  </td>

  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>Локомотив (Одесса)</span></p>
  </td>
 </tr>
 <tr>
  <td valign=top style='border:solid windowtext 1.0pt;border-top:none;
  padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>1998/1999</span></p>
  </td>

  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>Виннер Форд Университет
  (Запорожье)</span></p>
  </td>
 </tr>
 <tr>
  <td valign=top style='border:solid windowtext 1.0pt;border-top:none;
  padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>1999/2000</span></p>
  </td>

  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>Интеркас (Киев)</span></p>
  </td>
 </tr>
 <tr>
  <td valign=top style='border:solid windowtext 1.0pt;border-top:none;
  padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>2000/2001</span></p>
  </td>

  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>ИнтерКрАЗ (Киев)</span></p>
  </td>
 </tr>
 <tr>
  <td valign=top style='border:solid windowtext 1.0pt;border-top:none;
  padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>2001/2002</span></p>
  </td>

  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>Днепроспецсталь (Запорожье)</span></p>
  </td>
 </tr>
 <tr>
  <td valign=top style='border:solid windowtext 1.0pt;border-top:none;
  padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>2002/2003</span></p>
  </td>

  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>МФК Шахтер (Донецк)</span></p>
  </td>
 </tr>
 <tr>
  <td valign=top style='border:solid windowtext 1.0pt;border-top:none;
  padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>2003/2004</span></p>
  </td>

  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>МФК Шахтер (Донецк)</span></p>
  </td>
 </tr>
 <tr>
  <td valign=top style='border:solid windowtext 1.0pt;border-top:none;
  padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>2004/2005</span></p>
  </td>

  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>Интеркас (Киев)</span></p>
  </td>
 </tr>
 <tr>
  <td valign=top style='border:solid windowtext 1.0pt;border-top:none;
  padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>2005/2006</span></p>
  </td>

  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>МФК Шахтер (Донецк)</span></p>
  </td>
 </tr>
 <tr>
  <td valign=top style='border:solid windowtext 1.0pt;border-top:none;
  padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>2006/2007</span></p>
  </td>

  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>Енакиевец (Енакиево)</span></p>
  </td>
 </tr>
 <tr>
  <td valign=top style='border:solid windowtext 1.0pt;border-top:none;
  padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>2007/2008</span></p>
  </td>

  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>ТВД (Львов)</span></p>
  </td>
 </tr>
 <tr>
  <td valign=top style='border:solid windowtext 1.0pt;border-top:none;
  padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>2008/2009</span></p>
  </td>

  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>Локомотив (Харьков)</span></p>
  </td>
 </tr>
 <tr>
  <td valign=top style='border:solid windowtext 1.0pt;border-top:none;
  padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>2009/2010</span></p>
  </td>

  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>Тайм (Львов)</span></p>
  </td>
 </tr>
</table>

<p class=MsoNormal><b><span style='font-size:10.0pt'>&nbsp;</span></b></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>&nbsp;</span></b></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>&nbsp;</span></b></p>

<p class=MsoNormal><b><span style='font-size:10.0pt;color:blue'>КУБОК УКРАИНЫ-
1992/1993</span></b></p>

<p class=MsoNormal><span style='font-size:10.0pt'>Финал</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>СКИФ-Силекс (Киев) – Надежда
(Запорожье) – 2:2 пен.5:4</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt;color:blue'>КУБОК
УКРАИНЫ-1993/1994</span></b></p>

<p class=MsoNormal><span style='font-size:10.0pt'>1/4 финала</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>29-31.01.1994</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>Группа А</span></p>

<table class=MsoTableGrid border=1 cellspacing=0 cellpadding=0
 style='border-collapse:collapse;border:none'>
 <tr>
  <td valign=top style='border:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>

  <p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>
  </td>
  <td valign=top style='border:solid windowtext 1.0pt;border-left:none;
  padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>
  </td>
  <td valign=top style='border:solid windowtext 1.0pt;border-left:none;
  padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>
  </td>
  <td valign=top style='border:solid windowtext 1.0pt;border-left:none;
  padding:0cm 5.4pt 0cm 5.4pt'>

  <p class=MsoNormal><span style='font-size:10.0pt'>и</span></p>
  </td>
  <td valign=top style='border:solid windowtext 1.0pt;border-left:none;
  padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>в</span></p>
  </td>
  <td valign=top style='border:solid windowtext 1.0pt;border-left:none;
  padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>н</span></p>

  </td>
  <td valign=top style='border:solid windowtext 1.0pt;border-left:none;
  padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>п</span></p>
  </td>
  <td valign=top style='border:solid windowtext 1.0pt;border-left:none;
  padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>м</span></p>
  </td>
  <td valign=top style='border:solid windowtext 1.0pt;border-left:none;
  padding:0cm 5.4pt 0cm 5.4pt'>

  <p class=MsoNormal><span style='font-size:10.0pt'>о</span></p>
  </td>
 </tr>
 <tr>
  <td valign=top style='border:solid windowtext 1.0pt;border-top:none;
  padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>1</span></p>
  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>

  <p class=MsoNormal><span style='font-size:10.0pt'>Надежда</span></p>
  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>Запорожье</span></p>
  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>3</span></p>

  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>2</span></p>
  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>0</span></p>
  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>

  <p class=MsoNormal><span style='font-size:10.0pt'>1</span></p>
  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>15-11</span></p>
  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>4</span></p>

  </td>
 </tr>
 <tr>
  <td valign=top style='border:solid windowtext 1.0pt;border-top:none;
  padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>2</span></p>
  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>Механизатор</span></p>

  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>Днепропетровск</span></p>
  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>3</span></p>
  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>

  <p class=MsoNormal><span style='font-size:10.0pt'>2</span></p>
  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>0</span></p>
  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>1</span></p>

  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>16-13</span></p>
  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>4</span></p>
  </td>
 </tr>

 <tr>
  <td valign=top style='border:solid windowtext 1.0pt;border-top:none;
  padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>3</span></p>
  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>Инга</span></p>
  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>

  <p class=MsoNormal><span style='font-size:10.0pt'>Харьков</span></p>
  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>3</span></p>
  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>1</span></p>

  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>0</span></p>
  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>2</span></p>
  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>

  <p class=MsoNormal><span style='font-size:10.0pt'>14-12</span></p>
  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>2</span></p>
  </td>
 </tr>
 <tr>
  <td valign=top style='border:solid windowtext 1.0pt;border-top:none;
  padding:0cm 5.4pt 0cm 5.4pt'>

  <p class=MsoNormal><span style='font-size:10.0pt'>4</span></p>
  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>Локомотив</span></p>
  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>Одесса</span></p>

  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>3</span></p>
  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>1</span></p>
  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>

  <p class=MsoNormal><span style='font-size:10.0pt'>0</span></p>
  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>2</span></p>
  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>9-18</span></p>

  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>2</span></p>
  </td>
 </tr>
</table>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>Группа А</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<table class=MsoTableGrid border=1 cellspacing=0 cellpadding=0
 style='border-collapse:collapse;border:none'>
 <tr>
  <td valign=top style='border:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>
  </td>
  <td valign=top style='border:solid windowtext 1.0pt;border-left:none;
  padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>
  </td>

  <td valign=top style='border:solid windowtext 1.0pt;border-left:none;
  padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>
  </td>
  <td valign=top style='border:solid windowtext 1.0pt;border-left:none;
  padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>и</span></p>
  </td>
  <td valign=top style='border:solid windowtext 1.0pt;border-left:none;
  padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>в</span></p>

  </td>
  <td valign=top style='border:solid windowtext 1.0pt;border-left:none;
  padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>н</span></p>
  </td>
  <td valign=top style='border:solid windowtext 1.0pt;border-left:none;
  padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>п</span></p>
  </td>
  <td valign=top style='border:solid windowtext 1.0pt;border-left:none;
  padding:0cm 5.4pt 0cm 5.4pt'>

  <p class=MsoNormal><span style='font-size:10.0pt'>м</span></p>
  </td>
  <td valign=top style='border:solid windowtext 1.0pt;border-left:none;
  padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>о</span></p>
  </td>
 </tr>
 <tr>
  <td valign=top style='border:solid windowtext 1.0pt;border-top:none;
  padding:0cm 5.4pt 0cm 5.4pt'>

  <p class=MsoNormal><span style='font-size:10.0pt'>1</span></p>
  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>Ника</span></p>
  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>Днепропетровск</span></p>

  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>3</span></p>
  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>3</span></p>
  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>

  <p class=MsoNormal><span style='font-size:10.0pt'>0</span></p>
  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>0</span></p>
  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>14-7</span></p>

  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>6</span></p>
  </td>
 </tr>
 <tr>
  <td valign=top style='border:solid windowtext 1.0pt;border-top:none;
  padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>2</span></p>

  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>Слид</span></p>
  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>Киев</span></p>
  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>

  <p class=MsoNormal><span style='font-size:10.0pt'>3</span></p>
  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>2</span></p>
  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>0</span></p>

  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>1</span></p>
  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>19-14</span></p>
  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>

  <p class=MsoNormal><span style='font-size:10.0pt'>4</span></p>
  </td>
 </tr>
 <tr>
  <td valign=top style='border:solid windowtext 1.0pt;border-top:none;
  padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>3</span></p>
  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>

  <p class=MsoNormal><span style='font-size:10.0pt'>ВОДЕЯР</span></p>
  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>Кременчуг</span></p>
  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>3</span></p>

  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>1</span></p>
  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>0</span></p>
  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>

  <p class=MsoNormal><span style='font-size:10.0pt'>2</span></p>
  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>10-15</span></p>
  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>2</span></p>

  </td>
 </tr>
 <tr>
  <td valign=top style='border:solid windowtext 1.0pt;border-top:none;
  padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>4</span></p>
  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>Шахтер</span></p>

  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>Донецк</span></p>
  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>3</span></p>
  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>

  <p class=MsoNormal><span style='font-size:10.0pt'>0</span></p>
  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>0</span></p>
  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>3</span></p>

  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>9-16</span></p>
  </td>
  <td valign=top style='border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal><span style='font-size:10.0pt'>0</span></p>
  </td>
 </tr>

</table>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>1/2 финала</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>01.02.1994</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>Надежда (Запорожье)</span></b><span
style='font-size:10.0pt'> – Слид (Киев) – 3:0</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>Ника (Днепропетровск)</span></b><span
style='font-size:10.0pt'> – Механизатор (Днепропетровск) – 5:4</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>Финал</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>02.02.1994</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>Ника (Днепропетровск)</span></b><span
style='font-size:10.0pt'> – Надежда (Запорожье) – 5:1</span></p>

<p class=MsoNormal><span style='font-size:10.0pt;color:blue'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt;color:blue'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt;color:blue'>&nbsp;</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt;color:blue'>КУБОК
УКРАИНЫ-1994/1995</span></b></p>

<p class=MsoNormal><span style='font-size:10.0pt'>1/4 финала</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>17 и 21.05.1995</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>Механизатор
(Днепропетровск)</span></b><span style='font-size:10.0pt'> – Локомотив (Одесса)
– 8:4, 6:3</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>18 и 20.05.1995</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>Шахтер (Донецк)</span></b><span
style='font-size:10.0pt'> – Случ (Ровно) – 3:1, 2:3</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>18 и 21.05.1995</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>Слид (Киев) – <b>Горняк
(Красногоровка)</b> – 8:9, 2:6</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>20 и 23.05.1995</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>Спорт (Ровно) – <b>Ника
(Днепропетровск)</b> – 2:10, -:+</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>1/2 финала</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>26 и 29.05.1995</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>Механизатор
(Днепропетровск)</span></b><span style='font-size:10.0pt'> – Шахтер (Донецк) –
6:1, 3:2</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>27 и 30.05.1995</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>Горняк (Красногоровка)</span></b><span
style='font-size:10.0pt'> – Ника (Днепропетровск) – 6:0, 3:1</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>Финал</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>14.06.1995 (Днепропетровск)</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>Механизатор
(Днепропетровск)</span></b><span style='font-size:10.0pt'> – Горняк
(Красногоровка) – 5:1</span></p>

<p class=MsoNormal><span style='font-size:10.0pt;color:blue'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt;color:blue'>КУБОК
УКРАИНЫ-1995/1996</span></b></p>

<p class=MsoNormal><span style='font-size:10.0pt'>1/4 финала</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>01 и 04.06.1996</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>Надежда (Запорожье) – <b>Случ
(Ровно)</b> – 6:6, 3:8</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>Шахтер (Донецк) – <b>Днепроспецсталь
(Запорожье)</b> – 4:4, 3:8</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>Кий-Политехник (Киев) – <b>Локомотив
(Одесса) </b>– 2:4, 2:4</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>КрАЗ (Кременчуг) – <b>Механизатор
(Днепропетровск)</b> – 5:7, <span style='color:red'>-:+ (?)</span></span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>1/2 финала</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>08 и 11.06.1996</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>Механизатор
(Днепропетровск)</span></b><span style='font-size:10.0pt'> – Случ (Ровно) –
12:0, 8:4</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>Днепроспецсталь (Запорожье) –
<b>Локомотив (Одесса)</b> – 4:3, 5:8</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>Финал</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>15.06.1996</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>Механизатор
(Днепропетровск)</span></b><span style='font-size:10.0pt'> – Локомотив (Одесса)
– 4:3</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt;color:blue'>КУБОК
УКРАИНЫ-1996/1997</span></b></p>

<p class=MsoNormal><span style='font-size:10.0pt'>1/4 финала</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>11 и 18.01.1997</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>Интеркас (Киев) – <b>Случ
(Ровно) </b>– 6:8, 4:2</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>УС Корпия (Киев)</span></b><span
style='font-size:10.0pt'> – Надежда-Запорожкокс (Запорожье) – 1:1, 4:4</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>Днепроспецсталь
(Запорожье)</span></b><span style='font-size:10.0pt'> – Механизатор (Днепропетровск)
– 10:3, 8:7</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>Уголек (Макеевка) – <b>Локомотив
(Одесса)</b> – 2:7, 0:13</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>1/2 финала</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>29.01 и 02.02.1997</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>Локомотив (Одесса)</span></b><span
style='font-size:10.0pt'> – Случ (Ровно) – 6:0, 2:1</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>Днепроспецсталь
(Запорожье)</span></b><span style='font-size:10.0pt'> – УС Корпия (Киев) – 9:2,
8:4</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>Финал</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>15.02.1997 (Киев)</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>Локомотив (Одесса)</span></b><span
style='font-size:10.0pt'> – Днепроспецсталь (Запорожье) – 5:3</span></p>

<p class=MsoNormal><span style='font-size:10.0pt;color:blue'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt;color:blue'>&nbsp;</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt;color:red'>КУБОК
УКРАИНЫ-1997/1998</span></b></p>

<p class=MsoNormal><span style='font-size:10.0pt'>Финал четырех (Запорожье)</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>1/2 финала</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>21.03.1998</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>Локомотив (Одесса)</span></b><span
style='font-size:10.0pt'> – Эталон-ЭХО (Харьков) – 4:1</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>Интеркас (Киев) </span></b><span
style='font-size:10.0pt'>– Виннер Форд Университет (Запорожье) – 4:2 дв</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>Финал</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>22.03.1998</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>Локомотив (Одесса)</span></b><span
style='font-size:10.0pt'> – Интеркас (Киев) – 6:4 дв</span></p>

<p class=MsoNormal><span style='font-size:10.0pt;color:blue'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt;color:blue'>&nbsp;</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt;color:blue'>КУБОК
УКРАИНЫ-1998/1999</span></b></p>

<p class=MsoNormal><span style='font-size:10.0pt'>1/4 финала</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>22 и 25.04.1999</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>Запорожкокс (Запорожье)</span></b><span
style='font-size:10.0pt'> – Шахтер (Донецк) – 11:2, 2:4</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>ФК Харьков (Харьков) – <b>Виннер
Форд Университет (Запорожье)</b> – 2:3, 0:8</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>УС Корпия (Киев)</span></b><span
style='font-size:10.0pt'> – Днепроспецсталь (Запорожье) – 6:3, 4:4</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>Интеркас (Киев)</span></b><span
style='font-size:10.0pt'> – Укрсплав (Донецк) – 13:3, 7:3</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>Финал четырех (Запорожье)</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>1/2 финала</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>01.05.1999</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>УС Корпия (Киев)</span></b><span
style='font-size:10.0pt'> – Интеркас (Киев) – 4:3</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>Виннер Форд Университет
(Запорожье)</span></b><span style='font-size:10.0pt'> – Запорожкокс (Запорожье)
– 3:3, пен. 4:3</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>Финал</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>Виннер Форд Университет (Запорожье)</span></b><span
style='font-size:10.0pt'> – УС Корпия (Киев) – 8:3</span></p>

<p class=MsoNormal><span style='font-size:10.0pt;color:blue'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt;color:blue'>&nbsp;</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt;color:blue'>КУБОК
УКРАИНЫ-1999/2000</span></b></p>

<p class=MsoNormal><span style='font-size:10.0pt'>1/4 финала</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>29.03 и 01.04.2000</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>Укрсплав (Донецк) – <b>Интеркас
(Киев)</b> – 2:3, 4:7</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>Корпия-Политех (Киев)</span></b><span
style='font-size:10.0pt'> – Телеком (Донецк) – 9:3, 3:4</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>Униспорт-Будстар (Киев) – <b>Днепроспец<a
name="OLE_LINK1">сталь (Запо</a>рожье)</b> – 0:4, -: +</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>Запорожкокс (Запорожье)</span></b><span
style='font-size:10.0pt'> – Море (Ильичевск) – 8:2, +: -</span></p>

<p class=MsoNormal><span style='font-size:10.0pt;color:blue'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>1/2 финала</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>05 и 08.04.2000</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>Корпия-Политех (Киев) – <b>Интеркас
(Киев)</b> – 2:2, 1:4</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>Днепроспецсталь (Запорожье) –
<b>Запорожкокс (Запорожье)</b> – 0:3, 0:1</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>Финал</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>15.04.2000 (Запорожье)</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>Интеркас (Киев</span></b><span
style='font-size:10.0pt'>) – Запорожкокс (Запорожье) – 4:1 дв</span></p>

<p class=MsoNormal><span style='font-size:10.0pt;color:blue'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt;color:blue'>&nbsp;</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt;color:blue'>КУБОК
УКРАИНЫ-2000/2001</span></b></p>

<p class=MsoNormal><span style='font-size:10.0pt'>1/4 финала</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>24 и 28.03.2001</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>Укрсплав (Донецк)</span></b><span
style='font-size:10.0pt'> – Вексель-ЗИГМУ (Запорожье) – 6:1, 7:1</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>ИнтерКрАЗ (Киев)</span></b><span
style='font-size:10.0pt'> – Университет-Академия (Запорожье) – 7:1, 5:4</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>Днепроспецсталь (Запорожье)</span></b><span
style='font-size:10.0pt'> – Море (Ильичевск) – 4:0, 3:5</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>Запорожкокс (Запорожье) – свободен
от игр</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>1/2 финала</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>19 и 23.05.2001</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>Укрсплав (Донецк)</span></b><span
style='font-size:10.0pt'> – Днепроспецсталь (Запорожье) – 4:3, 2:1</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>ИнтерКрАЗ (Киев)</span></b><span
style='font-size:10.0pt'> – Запорожкокс (Запорожье) – 4:2, 2:1</span></p>

<p class=MsoNormal><span style='font-size:10.0pt;color:blue'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>Финал</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>26.05.2001 (Донецк)</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>ИнтерКрАЗ (Киев) – Укрсплав
(Донецк) – 3:0</span></p>

<p class=MsoNormal><span style='font-size:10.0pt;color:blue'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt;color:blue'>&nbsp;</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt;color:blue'>КУБОК
УКРАИНЫ-2001/2002</span></b></p>

<p class=MsoNormal><span style='font-size:10.0pt'>1/4 финала</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>02.03 и 20.04.2002</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>Днепроспецсталь
(Запорожье)</span></b><span style='font-size:10.0pt'> – Била Крыныця
(Радомышль) – 4:1, 4:1</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>ФК Шахтер (Донецк)</span></b><span
style='font-size:10.0pt'> – Универ-ЭХО (Харьков) – 7:1, 5:1</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>05.03 и 20.04.2002</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>ИнтерКрАЗ (Киев)</span></b><span
style='font-size:10.0pt'> – Кий (Киев) – 3:0, 4:0</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>13.03 и 20.04.2002</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>Запорожкокс (Запорожье) – <b>ДДАУ-Бересфорд
(Днепропетровск)</b> – 8:4, -:+ («Запорожкокс» – отказ)</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>1/2 финала</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>04.05 и 16.05.2002</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>ИнтерКрАЗ (Киев)</span></b><span
style='font-size:10.0pt'> – ДДАУ-Бересфорд (Днепропетровск) – 6:2, 14:3</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>ФК Шахтер (Донецк) – <b>Днепроспецсталь
(Запорожье)</b> – 3:5, 2:2</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>Финал <span style='color:
red'>(?)</span></span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>Днепроспецсталь
(Запорожье)</span></b><span style='font-size:10.0pt'> – ИнтерКрАЗ (Киев) – 4:1</span></p>

<p class=MsoNormal><span style='font-size:10.0pt;color:blue'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt;color:blue'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt;color:blue'>&nbsp;</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt;color:blue'>КУБОК
УКРАИНЫ-2002/2003</span></b></p>

<p class=MsoNormal><span style='font-size:10.0pt'>1/4 финала</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>06.02 и 01.03.2003</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>ИнтерКРАЗ (Киев)</span></b><span
style='font-size:10.0pt'> – Униспорт (Киев) – 8:1, 6:0</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>08.02 и 01.03.2003</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>Универ-Локо (Харьков)</span></b><span
style='font-size:10.0pt'> – Море (Ильичевск) – 3:0, 4:5</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>Енакиевец (Енакиево) – <b>Александр
(Харьков)</b> – 3:5, 2:5</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>06.02 и 15.04.2003</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>Шахтер (Донецк)</span></b><span
style='font-size:10.0pt'> – Львовская пивоварня (Львов) – 5:0, 2:0</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>1/2 финала</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>22.04 и 17.05.2003</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>Шахтер (Донецк)</span></b><span
style='font-size:10.0pt'> – Александр (Харьков) – 3:2, 5:1</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>10 и 17.05.2003</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>ИнтерКРАЗ (Киев) – <b>Универ-Локо
(Харьков)</b> – 1:3, 1:1</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>Финал</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>24.05.2003 (Донецк)</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>ФК Шахтер (Донецк)</span></b><span
style='font-size:10.0pt'> – Универ-Локо (Харьков) – 4:3 дв</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt;color:blue'>КУБОК
УКРАИНЫ-2003/2004</span></b></p>

<p class=MsoNormal><span style='font-size:10.0pt'>1/4 финала</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>16 и 25.02.2004</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>Море (Ильичевск) – <b>Шахтер
(Донецк)</b> – 3:5, 2:6</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>18 и 25.02.2004</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>ИнтерКраАЗ (Киев) </span></b><span
style='font-size:10.0pt'>– СумыГаз – 2:0, 4:2</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>Александр (Харьков) – <b>Днепроспецсталь
(Запорожье)</b> – 4:3, 2:5</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>Универ-Локо (Харьков) – <b>Енакиевец
(Енакиево)</b> – 3:3, 2:3</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>1/2 финала</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>03.03 и 10.04.2004</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>Шахтер (Шахтер)</span></b><span
style='font-size:10.0pt'> – Енакиевец (Енакиево) – 4:0, 5:1</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>ИнтерКраАЗ (Киев) – <b>Днепроспецсталь
(Запорожье)</b> – 2:1, 0:4</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>Финал</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>24.04.2004 (Донецк)</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>Шахтер (Донецк)</span></b><span
style='font-size:10.0pt'> – Днепроспецсталь (Запорожье) – 6:1</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt;color:blue'>КУБОК УКРАИНЫ-2004/2005</span></b></p>

<p class=MsoNormal><span style='font-size:10.0pt'>1/4 финала</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>09.01 и 01.02.2005</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>Днепроспецсталь (Запорожье) –
<b>Енакиевец (Енакиево)</b> – 1:2, 3:3</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>Энергия (Львов) – <b>Интеркас
(Киев)</b> – 0:2, 3:6</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>Александр (Харьков) – <b>Киевская
Русь (Донецк)</b> – 5:3, 1:4</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>Шахтер (Донецк)</span></b><span
style='font-size:10.0pt'> – Ураган (Ивано-Франковск) – 5:0, 2:2</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>1/2 финала</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>02.03 и 06.04.2005</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>Енакиевец (Енакиево) – <b>Интеркас
(Киев)</b> – 0:0, 4:6</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>Киевская Русь (Донецк) – <b>Шахтер
(Донецк)</b> – 1:2, 2:4</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>Финал</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>16.04.2005 (Сумы)</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>Интеркас (Киев)</span></b><span
style='font-size:10.0pt'> – Шахтер (Донецк) – 2:1</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt;color:blue'>КУБОК
УКРАИНЫ-2005/2006</span></b></p>

<p class=MsoNormal><span style='font-size:10.0pt'>1/4 финала</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>20.12.2005 и 17.01.2006</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>Енакиевец (Енакиево) – <b>Шахтер
(Донецк)</b> – 2:3, 5:6</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>Энергия (Львов)</span></b><span
style='font-size:10.0pt'> – Киев-Униспорт (Киев) – 6:4, 3:4</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>ТВД (Львов)</span></b><span
style='font-size:10.0pt'> – ЛТК (Луганск) – 1:0, 6:5</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>Тайм (Львов)</span></b><span
style='font-size:10.0pt'> – Кардинал (Львов) – 4:0, 4:2</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>1/2 финала</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>11.02 и 12.03.2006</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>ТВД (Львов) – <b>Энергия (Львов)
–</b> 2:2, 3:4</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>12.02 и 15.03.2006</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>Тайм (Львов) – <b>Шахтер
(Донецк)</b> – 1:2, 4:11</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>Финал</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>27.05.2006 (Сумы)</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>Шахтер (Донецк)</span></b><span
style='font-size:10.0pt'> – Энергия (Львов) – 3:3, пен.5:4</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt;color:blue'>КУБОК
УКРАИНЫ-2006/2007</span></b></p>

<p class=MsoNormal><span style='font-size:10.0pt'>1/4 финала</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>10.01.2007 и 01.02.2007</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>ЛТК (Луганск) – <b>Тайм
(Львов)</b> – 2:4, 0:2</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>10.01.2007 и 02.02.2007</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>Енакиевец (Енакиево)</span></b><span
style='font-size:10.0pt'> – Энергия (Львов) – 6:0, 4:5</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>ТВД (Львов)</span></b><span
style='font-size:10.0pt'> – Метрополитен (Киев) – 1:0, 4:3</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>Будивел (Днепропетровск) – <b>Шахтер
(Донецк)</b> – 3:3, 1:3</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>1/2 финала</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>06 и 18.03.2007</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>ТВД (Львов)</span></b><span
style='font-size:10.0pt'> – Тайм (Львов) – 2:2, 5:5</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>Шахтер (Донецк) – <b>Енакиевец
(Енакиево)</b> – 2:0, 2:7</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>Финал</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>02.04.2007 (Сумы)</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>Енакиевец (Енакиево)</span></b><span
style='font-size:10.0pt'> – ТВД (Львов) – 2:2, пен.4:2</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt;color:blue'>КУБОК
УКРАИНЫ-2007/2008</span></b></p>

<p class=MsoNormal><span style='font-size:10.0pt'>1/4 финала</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>19.01 и 12.02.2008</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>Ураган (Ивано-Франковск) – <b>ЛТК
(Луганск)</b> – 3:1, 2:8</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>19.01 и 13.02.2008</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>Энергия (Львов) – <b>СумДУ
(Сумы)</b> – 5:4, 2:4</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>ТВД (Львов)</span></b><span
style='font-size:10.0pt'> – МФК Ровно (Ровно) – 5:1, 2:3</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>Планета-Мост (Киев) – <b>Енакиевец
(Енакиево) </b>– 2:2, 2:3</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>1/2 финала</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>13.03 и 19.04.2008</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>Енакиевец (Енакиево)</span></b><span
style='font-size:10.0pt'> – ЛТК (Луганск) – 3:0*, 2:2</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>СумДУ (Сумы) – <b>ТВД (Львов)</b>
– 2:3, 1:1</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>* – технический результат,
матч закончился со счетом 0:2.</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>Финал</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>09.05.2008 (Харьков)</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>ТВД (Львов)</span></b><span
style='font-size:10.0pt'> – Енакиевец (Енакиево) – 3:1</span></p>

<p class=MsoNormal><span style='font-size:10.0pt;color:blue'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt;color:blue'>&nbsp;</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt;color:blue'>КУБОК
УКРАИНЫ-2008/2009</span></b></p>

<p class=MsoNormal><span style='font-size:10.0pt'>1/4 финала</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>21.02 и 29.03.2009</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>Локомотив (Харьков)</span></b><span
style='font-size:10.0pt'> – Планета-Мост (Киев) – 1:1, 3:1</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>Шахтер (Донецк)</span></b><span
style='font-size:10.0pt'> – Сапар (Донецк) – 7:1, 4:3</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>Маррион (Одесса) – <b>Монолит
(Харьков)</b> – 1:2, 2:5</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>22.02 и 29.03.2009</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>ЛТК (Луганск) – <b>Тайм
(Львов)</b> – 1:2, 0:5</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>1/2 финала</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>07 и 25.04.2009</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>Монолит (Харьков) – <b>Локомотив
(Харьков)</b> – 1:1, 2:4</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>08 и 25.04.2009</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>Тайм (Львов) – <b>Шахтер
(Донецк)</b> – 3:2, 2:4</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>Финал</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>03.05.2009 (Донецк)</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>Локомотив (Харьков)</span></b><span
style='font-size:10.0pt'> – Шахтер (Донецк) – 2:0</span></p>

<p class=MsoNormal><span style='font-size:10.0pt;color:blue'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt;color:blue'>&nbsp;</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt;color:blue'>КУБОК
УКРАИНЫ-2009/2010</span></b></p>

<p class=MsoNormal><span style='font-size:10.0pt'>Финал восьми (Харьков)</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>1/4 финала</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>18.02.2010</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>ЛТК (Луганск)</span></b><span
style='font-size:10.0pt'> – Ураган (Ивано-Франковск) – 5:5, пен. 4:2</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>Тайм (Львов)</span></b><span
style='font-size:10.0pt'> – Энергия (Львов) – 4:3</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>Шахтер (Донецк)</span></b><span
style='font-size:10.0pt'> – Локомотив (Харьков) – 2:2, пен. 3:1</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>Енакиевец (Енакиево)</span></b><span
style='font-size:10.0pt'> – Ровно-ШВСМ-4 (Ровно) – 5:3</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>1/2 финала</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>19.02.2010</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>Тайм (Львов)</span></b><span
style='font-size:10.0pt'> – Шахтер (Донецк) – 5:0</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>Енакиевец (Енакиево)</span></b><span
style='font-size:10.0pt'> – ЛТК (Луганск) – 6:2</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>&nbsp;</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>Финал</span></p>

<p class=MsoNormal><span style='font-size:10.0pt'>21.02.2010</span></p>

<p class=MsoNormal><b><span style='font-size:10.0pt'>Тайм (Львов)</span></b><span
style='font-size:10.0pt'> – Енакиевец (Енакиево) – 1:0</span></p>

</div>
