<a class="sexybutton sexysimple" href="<?php echo $this->url(array('controller'=>'news'));?>">Управление новостями</a>
<a class="sexybutton sexysimple" href="<?php echo $this->url(array('controller'=>'teams'));?>">Управление командами</a>
<a class="sexybutton sexysimple" href="<?php echo $this->url(array('controller'=>'tours'));?>">Управление турами</a>
<a class="sexybutton sexysimple" href="<?php echo $this->url(array('controller'=>'games'));?>">Управление играми</a>
<a class="sexybutton sexysimple" href="<?php echo $this->url(array('controller'=>'polls'));?>">Управление опросами</a>
<a class="sexybutton sexysimple" href="<?php echo $this->url(array('controller'=>'newscategory'));?>">Управление категориями новостей</a>
<a class="sexybutton sexysimple" href="<?php echo $this->url(array('controller'=>'video'));?>">Управление видео</a>
<a class="sexybutton sexysimple" href="<?php echo $this->url(array('controller'=>'statistic'));?>">Управление страницами результатов</a>
<a class="sexybutton sexysimple" href="<?php echo $this->url(array('controller'=>'forwards'));?>">Управление бомбардирами</a>
<a class="sexybutton sexysimple" href="<?php echo $this->url(array('controller'=>'archiv'));?>">Управление архивом</a>
<a class="sexybutton sexysimple" href="<?php echo $this->url(array('controller'=>'photo-categories'));?>">Управление фотоальбомами</a>
<a class="sexybutton sexysimple" href="<?php echo $this->url(array('controller'=>'photo'));?>">Управление фотографиями</a>