 <div style="display:inline; position: relative">
	<div id="smoothmenu1" class="ddsmoothmenu">
		<ul style="margin-left:105px;">
			<li><a href="/"><b>Главная</b></a></li>


			<li><a href="javascript:void(0)"><b>Клуб</b></a>
				<ul>
					<li><a href="/team">О команде</a></li>
					<li><a href="/staff">Состав</a></li>
					<li><a href="/monolit-double">Монолит 2</a></li>
					<li><a href="/academy">Академия</a></li>
					<li><a href="/calendar">Календарь</a></li>
					<li><a href="http://monolit-fans.pp.ua">Фанклуб</a></li>
					<li><a href="/contacts">Контакты</a></li>
				</ul>
			</li>


			<li><a href="javascript:void(0)"><b>Украина</b></a>
				<ul>
					<li><a href="/tournaments/show/tournamentid/1/">Высшая лига</a></li>
					<li>
						<a href="javascript:void(0)">Первая лига</a>
						<ul>
							<li><a href="/tournaments/show/tournamentid/17/tag/7">Группа А</a></li>
							<li><a href="/tournaments/show/tournamentid/2/tag/7">Группа Б</a></li>
							
						</ul>
					
					</li>
					<li><a href="/tournaments/show/tournamentid/3/tag/10">Кубок Украины</a></li>
					<li><a href="/clubs">Клубы</a></li>
				</ul>
			</li>


			<li><a href="javascript:void(0)"><b>Турниры</b></a>
				<ul>
					<li>
						<a href="javascript:void(0)">Кубок Универ</a>
						<ul>
							<li><a href="/tournaments/show/tournamentid/6/tag/13">Суперлига</a></li>
							<li><a href="/tournaments/show/tournamentid/7/tag/13">Первая лига</a></li>
							<li><a href="/tournaments/show/tournamentid/8/tag/13">Вторая лига</a></li>
							<li><a href="/tournaments/show/tournamentid/9/tag/13">Третья лига</a></li>
							<li><a href="/tournaments/show/tournamentid/10/tag/13">Четвертая лига</a></li>
							<li><a href="/tournaments/show/tournamentid/11/tag/13">Пятая лига</a></li>
							<li><a href="/tournaments/show/tournamentid/12/tag/13">Шестая лига</a></li>
							<li><a href="/tournaments/show/tournamentid/13/tag/13">Седьмая лига</a></li>
							<li><a href="/tournaments/show/tournamentid/14/tag/13">Восьмая лига</a></li>
							
						</ul>
					</li>
					<li><a href="/tournaments/show/tournamentid/4/tag/15">АЖИ</a></li>
				</ul>
			</li>

			<?php

			function printMenu($groups, $parent, $years) {
			    foreach ($groups as $group) {
			        if ($parent == $group->idParent) {
			            echo '<li>';
			            if ($parent == 0) {
			                echo '<a href="javascript:void(0)"><b>' . $group->title . '</b></a>';
			            }
			            else {
			                echo '<a href="javascript:void(0)">' . $group->title . '</a>';
			            }
			            $hasChildGroups = false;
			            foreach ($groups as $g) {
			                if ($g->idParent == $group->id) {
			                    $hasChildGroups = true;
			                    break;
			                }
			            }
			            $hasChildYears = false;
			            foreach ($years as $y) {
			                if ($y->idStatGroup == $group->id) {
			                    $hasChildYears = true;
			                    break;
			                }
			            }


			            if ($hasChildGroups || $hasChildYears) {
			                echo '<ul>';
			                if ($hasChildGroups)
    	                        printMenu($groups, $group->id, $years);
    	                    if ($hasChildYears) {
    	                        foreach ($years as $y)
    	                        {
    	                            if ($y->idStatGroup == $group->id)
    	                            {
    	                                echo '<li><a href="/statistic/show/tour/' . $group->slug . '/year/' . $y->year . '/">' . $y->title . '</a></li>';
    	                            }
    	                        }
    	                    }
	                        echo '</ul>';
			            }
			            echo '</li>';
			        }
			    }
			}

			printMenu($this->statGroups, 0, $this->statYears);

			?>

			<li><a href="javascript:void(0)"><b>Мир</b></a>
				<ul>
					<li><a href="/tournaments/show/tournamentid/18/tag/17">Россия</a></li>
					<li><a href="/tournaments/show/tournamentid/19/tag/16">Испания</a></li>
				</ul> 
			</li>
			


			<li><a href="javascript:void(0)"><b>Документы</b></a>
				<ul>
					<li><a href="/pdf/reglament.pdf"  onclick="this.target='target'">Регламент</a></li>
					<li><a href="/rules/">Правила</a></li>
				</ul>
			</li>


			<li><a href="javascript:void(0)"><b>Мультимедиа</b></a>
				<ul>
					<li><a href="/photo">Фото</a></li>
					<li><a href="/video">Видео</a></li>
					<li><a href="/wallpaper">Обои</a></li>
				</ul>
			</li>


			<li>
				<a href="/partners"><b>Партнеры</b></a>
			</li>


		</ul>
		<div class="clear"></div>
		<!--  <br style="clear: left" />-->
	</div>
</div>