<div class="news_block_element videoblock">
	<h4 class="newshead">
		<span>Партнеры</span>
	</h4>
	<div class="partners-team">
		<?php /* ?><a onclick="this.target='target'" href="http://www.fctime.lviv.ua/">
			<img src="/i/teams/time.jpg"/>
		</a>
		<a onclick="this.target='target'" href="http://www.shakhtar5x5.dn.ua/">
			<img src="/i/teams/shakhtar.jpg"/>
		</a>
		<a onclick="this.target='target'" href="http://www.enakievec.com.ua/">
			<img src="/i/teams/enak.jpg"/>
		</a>
		<a onclick="this.target='target'" href="http://www.mfk-lokomotiv.com.ua/">
			<img src="/i/teams/lokomotiv.jpg"/>
		</a>
		<a onclick="this.target='target'" href="http://www.futsalltk.com/">
			<img src="/i/teams/ltk.jpg"/>
		</a>
		<a onclick="this.target='target'" href="http://www.mfc-cardinal.lviv.ua/">
			<img src="/i/teams/cardinal.jpg"/>
		</a>
		<a onclick="this.target='target'" href="http://www.uragan.if.ua/">
			<img src="/i/teams/uragan.jpg"/>
		</a>
		<a onclick="this.target='target'" href="http://www.energia.lviv.ua/">
			<img src="/i/teams/energy.jpg"/>
		</a>
		
		<a onclick="this.target='target'" href="/">
			<img src="/i/teams/tvd.jpg"/>
		</a> <?php */ ?>
		
		<a onclick="this.target='target'" href="http://fcsumdu.sumy.ua/">
			<img src="/i/teams/sumdu.jpg"/>
		</a>
		
		<a onclick="this.target='target'" href="http://www.sport.ua/">
			<img src="/i/teams/sportua.jpg"/>
		</a>
		
		<a onclick="this.target='target'" href="http://www.goal.net.ua/">
			<img src="/i/teams/goal.jpg"/>
		</a>
		
		<a onclick="this.target='target'" href="http://www.energia.lviv.ua/">
			<img src="/i/teams/energy_crop.jpg"/>
		</a>
	</div>
</div>