<div class=Section1>

<p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
text-align:center;line-height:normal'><a name="_GoBack"><b><span lang=EN-US
style='font-size:14.0pt;font-family:"Times New Roman","serif"'>ЧЕМПИОНАТ МИРА
1989</span></b></a></p>

<p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
text-align:center;line-height:normal'><b><span lang=EN-US style='font-size:
10.0pt;font-family:"Times New Roman","serif"'>5-15 января 1989 года</span></b></p>

<p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
text-align:center;line-height:normal'><b><span lang=EN-US style='font-size:
10.0pt;font-family:"Times New Roman","serif"'>НИДЕРЛАНДЫ</span></b></p>

<p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
text-align:center;line-height:normal'><b><span style='font-size:10.0pt;
font-family:"Times New Roman","serif"'><img width=177 height=218 id="Рисунок 1"
src="1989.files/image001.gif" alt="http://futsal.ucoz.ru/_pu/2/70975.gif"></span></b></p>

<div align=center>

<table class=MsoNormalTable border=0 cellpadding=0 width="100%"
 style='width:100.0%'>
 <tr>
  <td style='padding:1.5pt 1.5pt 1.5pt 1.5pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><span
  style='font-size:10.0pt;font-family:"Times New Roman","serif";color:steelblue'>Первый
  этап<br>

  Группа А<br>
  </span><b><span style='font-size:10.0pt;font-family:"Times New Roman","serif"'>5.1.89
  </span></b><span style='font-size:10.0pt;font-family:"Times New Roman","serif"'><br>
  НИДЕРЛАНДЫ - ДАНИЯ 4-2 (1-0) <br>
  ПАРАГВАЙ - АЛЖИР 5-0 (4-0)<br>
  <b>7.1.89 </b><br>
  ДАНИЯ - ПАРАГВАЙ 2-2 (0-1) <br>

  НИДЕРЛАНДЫ - АЛЖИР 4-1 (3-1) <br>
  <b>8.1.89 </b><br>
  НИДЕРЛАНДЫ - ПАРАГВАЙ 2-2 (1-1) <br>
  ДАНИЯ - АЛЖИР 8-4 (2-1) </span></p>
  <div align=center>
  <table class=MsoNormalTable border=1 cellspacing=0 cellpadding=0 width="50%"
   style='width:50.0%;border:solid black 1.0pt'>
   <tr>

    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    10.0pt;font-family:"Times New Roman","serif"'>М</span></b></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    10.0pt;font-family:"Times New Roman","serif"'>Команда</span></b></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    10.0pt;font-family:"Times New Roman","serif"'>И</span></b></p>

    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    10.0pt;font-family:"Times New Roman","serif"'>В</span></b></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    10.0pt;font-family:"Times New Roman","serif"'>Н</span></b></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    10.0pt;font-family:"Times New Roman","serif"'>П</span></b></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    10.0pt;font-family:"Times New Roman","serif"'>Мячи</span></b></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    10.0pt;font-family:"Times New Roman","serif"'>О</span></b></p>

    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    10.0pt;font-family:"Times New Roman","serif"'>НИДЕРЛАНДЫ </span></b></p>

    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>2</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>0</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>10-5</span></p>

    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>5</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>2</span></p>

    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    10.0pt;font-family:"Times New Roman","serif"'>ПАРАГВАЙ </span></b></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>2</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>0</span></p>

    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>9-4</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>4</span></p>
    </td>
   </tr>

   <tr>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>ДАНИЯ</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>1</span></p>

    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>12-10</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>4</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>АЛЖИР</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>0</span></p>

    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>0</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>7-17</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>0</span></p>
    </td>
   </tr>
  </table>
  </div>

  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><span style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'><br>
  </span><b><span style='font-size:10.0pt;font-family:"Times New Roman","serif";
  color:steelblue'>Группа </span></b><b><span lang=EN-US style='font-size:10.0pt;
  font-family:"Times New Roman","serif";color:steelblue'>B</span></b><span
  style='font-size:10.0pt;font-family:"Times New Roman","serif"'><br>
  <b>6.1.89</b><br>
  ВЕНГРИЯ - БРАЗИЛИЯ 3-2 (1-2) <br>
  САУДОВСКАЯ АРАВИЯ-ИСПАНИЯ 2-8 (2-5) <br>
  <b>7.1.89 </b><br>

  БРАЗИЛИЯ - САУДОВСКАЯ АРАВИЯ 8-0 (3-0) <br>
  ВЕНГРИЯ-ИСПАНИЯ 3-5 (1-2) <br>
  <b>8.1.89 </b><br>
  ВЕНГРИЯ-САУДОВСКАЯ АРАВИЯ 11-2 (7-0) <br>
  БРАЗИЛИЯ - ИСПАНИЯ 4-1 (2-0) </span></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><span lang=EN-US style='font-size:10.0pt;
  font-family:"Times New Roman","serif"'>&nbsp;</span></p>

  <div align=center>
  <table class=MsoNormalTable border=1 cellspacing=0 cellpadding=0 width="50%"
   style='width:50.0%;border:solid black 1.0pt'>
   <tr>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    10.0pt;font-family:"Times New Roman","serif"'>М</span></b></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    10.0pt;font-family:"Times New Roman","serif"'>Команда</span></b></p>

    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    10.0pt;font-family:"Times New Roman","serif"'>И</span></b></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    10.0pt;font-family:"Times New Roman","serif"'>В</span></b></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    10.0pt;font-family:"Times New Roman","serif"'>Н</span></b></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    10.0pt;font-family:"Times New Roman","serif"'>П</span></b></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    10.0pt;font-family:"Times New Roman","serif"'>Мячи</span></b></p>

    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    10.0pt;font-family:"Times New Roman","serif"'>О</span></b></p>
    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>1</span></p>

    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    10.0pt;font-family:"Times New Roman","serif"'>БРАЗИЛИЯ</span></b></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>2</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>0</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>1</span></p>

    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>14-4</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>4</span></p>
    </td>
   </tr>

   <tr>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>2</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    10.0pt;font-family:"Times New Roman","serif"'>ВЕНГРИЯ</span></b></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>2</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>0</span></p>

    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>17-9</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>4</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>ИСПАНИЯ</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>2</span></p>

    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>0</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>14-9</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>4</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>4</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>САУДОВСКАЯ АРАВИЯ</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>

    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>0</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>0</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>4-27</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>0</span></p>

    </td>
   </tr>
  </table>
  </div>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><span lang=EN-US style='font-size:10.0pt;
  font-family:"Times New Roman","serif";color:blue'>&nbsp;</span></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span style='font-size:10.0pt;
  font-family:"Times New Roman","serif";color:steelblue'>Группа </span></b><b><span
  lang=EN-US style='font-size:10.0pt;font-family:"Times New Roman","serif";
  color:steelblue'>C</span></b><span style='font-size:10.0pt;font-family:"Times New Roman","serif"'><br>
  <b>6.1.89 </b><br>

  ЯПОНИЯ - БЕЛЬГИЯ 0-3 (0-1) <br>
  КАНАДА - АРГЕНТИНА 1-3 (0-2) <br>
  <b>7.1.89 </b><br>
  БЕЛЬГИЯ - КАНАДА 2-0 (1-0) <br>
  ЯПОНИЯ - АРГЕНТИНА 1-2 (0-2) <br>
  <b>8.1.89 </b><br>

  ЯПОНИЯ - КАНАДА 2-6 (1-2) <br>
  БЕЛЬГИЯ - АРГЕНТИНА 3-1 (1-0) </span></p>
  <div align=center>
  <table class=MsoNormalTable border=1 cellspacing=0 cellpadding=0 width="50%"
   style='width:50.0%;border:solid black 1.0pt'>
   <tr>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    10.0pt;font-family:"Times New Roman","serif"'>М</span></b></p>

    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    10.0pt;font-family:"Times New Roman","serif"'>Команда</span></b></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    10.0pt;font-family:"Times New Roman","serif"'>И</span></b></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    10.0pt;font-family:"Times New Roman","serif"'>В</span></b></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    10.0pt;font-family:"Times New Roman","serif"'>Н</span></b></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    10.0pt;font-family:"Times New Roman","serif"'>П</span></b></p>

    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    10.0pt;font-family:"Times New Roman","serif"'>Мячи</span></b></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    10.0pt;font-family:"Times New Roman","serif"'>О</span></b></p>
    </td>
   </tr>

   <tr>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    10.0pt;font-family:"Times New Roman","serif"'>БЕЛЬГИЯ</span></b></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>0</span></p>

    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>0</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>8-1</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>6</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>2</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    10.0pt;font-family:"Times New Roman","serif"'>АРГИНТИНА</span></b></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>2</span></p>

    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>0</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>6-5</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>4</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>КАНАДА</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>

    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>0</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>2</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>7-7</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>2</span></p>

    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>4</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>ЯПОНИЯ</span></p>

    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>0</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>0</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>3-11</span></p>

    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>0</span></p>
    </td>
   </tr>
  </table>
  </div>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><span lang=EN-US style='font-size:10.0pt;
  font-family:"Times New Roman","serif";color:blue'>&nbsp;</span></p>

  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span style='font-size:10.0pt;
  font-family:"Times New Roman","serif";color:steelblue'>Группа </span></b><b><span
  lang=EN-US style='font-size:10.0pt;font-family:"Times New Roman","serif";
  color:steelblue'>D</span></b><span style='font-size:10.0pt;font-family:"Times New Roman","serif"'><br>
  <b>6.1.89 </b><br>
  ИТАЛИЯ-ЗИМБАБВЕ 5-1 (3-0) <br>
  США-АВСТРАЛИЯ 1-1 (0-0) <br>
  <b>7.1.89 </b><br>
  ЗИМБАБВЕ-США 1-5 (0-3) <br>

  ИТАЛИЯ-АВСТРАЛИЯ 6-1 (3-0) <br>
  <b>8.1.89 </b><br>
  ИТАЛИЯ-США 1-4 (0-2)<br>
  ЗИМБАБВЕ-АВСТРАЛИЯ 1-4 (0-1) </span></p>
  <div align=center>
  <table class=MsoNormalTable border=1 cellspacing=0 cellpadding=0 width="50%"
   style='width:50.0%;border:solid black 1.0pt'>
   <tr>

    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>М</span></b></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>Команда</span></b></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>И</span></b></p>

    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>В</span></b></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>Н</span></b></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>П</span></b></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>Мячи</span></b></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>О</span></b></p>

    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>США</span></b></p>

    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>2</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>0</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>10-3</span></p>

    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>5</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>2</span></p>

    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>ИТАЛИЯ</span></b></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>2</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>0</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>1</span></p>

    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>12-6</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>4</span></p>
    </td>
   </tr>

   <tr>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>АВСТРАЛИЯ</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>1</span></p>

    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>6-8</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>3</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>4</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>ЗИМБАБВЕ</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>0</span></p>

    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>0</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>3-14</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>0</span></p>
    </td>
   </tr>
  </table>
  </div>

  </td>
 </tr>
 <tr>
  <td style='padding:1.5pt 1.5pt 1.5pt 1.5pt'>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span style='font-size:10.0pt;
  font-family:"Times New Roman","serif";color:steelblue'>Второй этап<br>
  </span></b><b><span style='font-size:10.0pt;font-family:"Times New Roman","serif";
  color:blue'>Группа 1</span></b></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span style='font-size:10.0pt;
  font-family:"Times New Roman","serif";color:steelblue'><br>
  </span></b><b><span style='font-size:10.0pt;font-family:"Times New Roman","serif"'>10.1.89
  </span></b><span style='font-size:12.0pt;font-family:"Times New Roman","serif"'><br>

  </span><span style='font-size:10.0pt;font-family:"Times New Roman","serif"'>НИДЕРЛАНДЫ-ВЕНГРИЯ
  3-3 (3-1)<br>
  БЕЛЬГИЯ - ИТАЛИЯ 5-1 (2-1) <br>
  <b>11.1.89 </b><br>
  ВЕНГРИЯ-БЕЛЬГИЯ 2-2 (0-1) <br>
  НИДЕРЛАНДЫ-ИТАЛИЯ 4-1 (2-1) <br>
  <b>12.1.89 </b><br>

  ВЕНГРИЯ - ИТАЛИЯ 1-3 (1-2) <br>
  НИДЕРЛАНДЫ-БЕЛЬГИЯ 1-2 (1-1) </span></p>
  <div align=center>
  <table class=MsoNormalTable border=1 cellspacing=0 cellpadding=0 width="50%"
   style='width:50.0%;border:solid black 1.0pt'>
   <tr>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>М</span></b></p>

    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>Команда</span></b></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>И</span></b></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>В</span></b></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>Н</span></b></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>П</span></b></p>

    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>Мячи</span></b></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>О</span></b></p>
    </td>
   </tr>

   <tr>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>БЕЛЬГИЯ</span></b></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>2</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>1</span></p>

    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>0</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>9-4</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>5</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>2</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>НИДЕРЛАНДЫ</span></b></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>1</span></p>

    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>8-6</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>3</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>ВЕНГРИЯ</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>3</span></p>

    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>0</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>2</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>6-8</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>2</span></p>

    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>4</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>ИТАДИЯ</span></p>

    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>0</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>2</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>5-10</span></p>

    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:10.0pt;
    font-family:"Times New Roman","serif"'>2</span></p>
    </td>
   </tr>
  </table>
  </div>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><span lang=EN-US style='font-size:10.0pt;
  font-family:"Times New Roman","serif";color:blue'>&nbsp;</span></p>

  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span style='font-size:10.0pt;
  font-family:"Times New Roman","serif";color:steelblue'>Группа 2</span></b><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'><br>
  </span><b><span style='font-size:10.0pt;font-family:"Times New Roman","serif"'>10.1.89</span></b><span
  style='font-size:10.0pt;font-family:"Times New Roman","serif"'><br>
  БРАЗИЛИЯ - ПАРАГВАЙ 5-1 (3-0) <br>
  США - АРГЕНТИНА 3-1 (0-1) <br>
  <b>11.1.89</b><br>
  ПАРАГВАЙ - США 0-2 (0-1) <br>

  БРАЗИЛИЯ - АРГЕНТИНА 6-3 (2-0) <br>
  <b>12.1.89</b><br>
  БРАЗИЛИЯ - США 3-5 (0-2) <br>
  ПАРАГВАЙ - АРГЕНТИНА 4-3 (1-2) </span></p>
  <div align=center>
  <table class=MsoNormalTable border=1 cellspacing=0 cellpadding=0 width="50%"
   style='width:50.0%;border:solid black 1.0pt'>
   <tr>

    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>М</span></b></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>Команда</span></b></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>И</span></b></p>

    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>В</span></b></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>Н</span></b></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>П</span></b></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>Мячи</span></b></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>О</span></b></p>

    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>США</span></b></p>

    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>0</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>0</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>10-4</span></p>

    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>6</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>2</span></p>

    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>БРАЗИЛИЯ</span></b></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>2</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>0</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>1</span></p>

    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>14-9</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>4</span></p>
    </td>
   </tr>

   <tr>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>ПАРАГВАЙ</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>0</span></p>

    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>2</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>5-10</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>2</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>4</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>АРГЕНТИНА</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>0</span></p>

    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>0</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>7-13</span></p>
    </td>
    <td style='border:solid black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:10.0pt;font-family:"Times New Roman","serif"'>0</span></p>
    </td>
   </tr>
  </table>
  </div>

  </td>
 </tr>
 <tr>
  <td style='padding:1.5pt 1.5pt 1.5pt 1.5pt'>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span style='font-size:10.0pt;
  font-family:"Times New Roman","serif";color:steelblue'>Полуфиналы<br>
  </span></b><b><span style='font-size:10.0pt;font-family:"Times New Roman","serif"'>14.1.89</span></b><span
  style='font-size:10.0pt;font-family:"Times New Roman","serif"'><br>
  БЕЛЬГИЯ - БРАЗИЛИЯ 1-1 (1-0),3-3(доп.вр), 3-5(по пенальти) <br>

  США-НИДЕРЛАНДЫ 1-2 (0-1) </span></p>
  </td>
 </tr>
 <tr>
  <td style='padding:1.5pt 1.5pt 1.5pt 1.5pt'>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span style='font-size:10.0pt;
  font-family:"Times New Roman","serif";color:steelblue'>Матч за 3-е место</span></b><b><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'><br>
  15.1.89 БЕЛЬГИЯ-США 2-2 (2-1) ,2-3(доп.вр) </span></b></p>

  </td>
 </tr>
 <tr>
  <td style='padding:1.5pt 1.5pt 1.5pt 1.5pt'>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span lang=EN-US style='font-size:
  10.0pt;font-family:"Times New Roman","serif";color:steelblue'>Финал</span></b><span
  lang=EN-US style='font-size:12.0pt;font-family:"Times New Roman","serif"'><br>
  </span><b><span lang=EN-US style='font-size:10.0pt;font-family:"Times New Roman","serif"'>15.1.89
  БРАЗИЛИЯ - НИДЕРЛАНДЫ 2-1 (1-0)</span></b></p>
  </td>
 </tr>

</table>

</div>

<p class=MsoNormal><span lang=EN-US>&nbsp;</span></p>

<p class=MsoNormal><img width=512 height=342 id="Рисунок 2"
src="1989.files/image002.jpg" alt="http://futsal.ucoz.ru/_pu/2/65855585.jpg"></p>

</div>
