<div class=Section1>

<p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
text-align:center;line-height:normal'><a name="_GoBack"><b><span lang=EN-US
style='font-size:14.0pt;font-family:"Times New Roman","serif"'>ЧЕМПИОНАТ МИРА
1992</span></b></a></p>

<p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
text-align:center;line-height:normal'><b><span lang=EN-US style='font-size:
12.0pt;font-family:"Times New Roman","serif"'>15-28 ноября 1992 года</span></b></p>

<p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
text-align:center;line-height:normal'><span lang=EN-US><a
href="http://futsal.ucoz.ru/_pu/2/90674048.jpg"
title="&quot;Нажмите, для просмотра в полном размере...&quot; t "><span
lang=RU style='font-size:12.0pt;font-family:"Times New Roman","serif";
color:blue;text-decoration:none'><img border=0 width=400 height=263
id="Рисунок 3" src="1992.files/image001.jpg"
alt="http://futsal.ucoz.ru/_pu/2/s90674048.jpg"></span></a></span></p>

<p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
text-align:center;line-height:normal'><b><span lang=EN-US style='font-size:
12.0pt;font-family:"Times New Roman","serif"'>ГОНКОНГ</span></b></p>

<p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
text-align:center;line-height:normal'><b><span style='font-size:12.0pt;
font-family:"Times New Roman","serif"'><img border=0 width=227 height=200
id="Рисунок 2" src="1992.files/image002.jpg"
alt="http://futsal.ucoz.ru/_pu/2/33918.jpg"></span></b></p>

<p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
text-align:center;line-height:normal'><span lang=EN-US style='font-size:12.0pt;
font-family:"Times New Roman","serif"'>&nbsp;</span></p>

<div align=center>

<table class=MsoNormalTable border=1 cellpadding=0 width="100%"
 style='width:100.0%;border:outset black 1.5pt'>
 <tr>

  <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><span style='font-size:18.0pt;
  font-family:"Times New Roman","serif";color:crimson'>Первый этап</span><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'><br>
  </span><span style='font-size:14.0pt;font-family:"Times New Roman","serif";
  color:blue'>Группа А</span><span style='font-size:12.0pt;font-family:"Times New Roman","serif"'><br>
  <b>15.11.92 </b><br>
  АРГЕНТИНА - НИГЕРИЯ 6-2 (4-0) <br>
  ГОНКОНГ-ПОЛЬША 2-4 (1-2) <br>

  <b>17.11.92 </b><br>
  ПОЛЬША - НИГЕРИЯ 5-4 (3-1) <br>
  ГОНКОНГ - АРГЕНТИНА 1-2 (1-0) <br>
  <b>20.11.92 </b><br>
  ПОЛЬША - АРГЕНТИНА 2-3 (2-3) <br>
  ГОНКОНГ - НИГЕРИЯ 4-1 (0-0) </span></p>

  <div align=center>
  <table class=MsoNormalTable border=1 cellpadding=0 width="50%"
   style='width:50.0%;border:outset blue 1.5pt'>
   <tr>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    12.0pt;font-family:"Times New Roman","serif"'>М</span></b></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    12.0pt;font-family:"Times New Roman","serif"'>Команда</span></b></p>

    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    12.0pt;font-family:"Times New Roman","serif"'>И</span></b></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    12.0pt;font-family:"Times New Roman","serif"'>В</span></b></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    12.0pt;font-family:"Times New Roman","serif"'>Н</span></b></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    12.0pt;font-family:"Times New Roman","serif"'>П</span></b></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    12.0pt;font-family:"Times New Roman","serif"'>Мячи</span></b></p>

    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    12.0pt;font-family:"Times New Roman","serif"'>О</span></b></p>
    </td>
   </tr>
   <tr>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>1</span></p>

    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    12.0pt;font-family:"Times New Roman","serif"'>АРГЕНТИНА</span></b></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>0</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>0</span></p>

    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>11-5</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>6</span></p>
    </td>
   </tr>

   <tr>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    12.0pt;font-family:"Times New Roman","serif"'>ПОЛЬША</span></b></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>0</span></p>

    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>11-9</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>4</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>ГОНКОНГ</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>1</span></p>

    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>0</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>7-7</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>4</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>НИГЕРИЯ</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>

    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>0</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>0</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>7-15</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>0</span></p>

    </td>
   </tr>
  </table>
  </div>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><span style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'><br>
  </span><span style='font-size:14.0pt;font-family:"Times New Roman","serif";
  color:blue'>Группа </span><span lang=EN-US style='font-size:14.0pt;
  font-family:"Times New Roman","serif";color:blue'>B</span><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'><br>
  <b>16.11.92</b><br>

  НИДЕРЛАНДЫ-ИРАН 2-1 (2-0) <br>
  ПАРАГВАЙ - ИТАЛИЯ 5-7 (1-2) <br>
  <b>18.11.92 </b><br>
  ИРАН-ИТАЛИЯ 7-5 (4-1) <br>
  НИДЕРЛАНДЫ - ПАРАГВАЙ 1-3 (0-2) <br>
  <b>20.11.92 </b><br>

  НИДЕРЛАНДЫ-ИТАЛИЯ 4-3 (1-0) <br>
  ИРАН - ПАРАГВАЙ 10-6 (2-2) </span></p>
  <div align=center>
  <table class=MsoNormalTable border=1 cellpadding=0 width="50%"
   style='width:50.0%;border:outset blue 1.5pt'>
   <tr>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    12.0pt;font-family:"Times New Roman","serif"'>М</span></b></p>

    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    12.0pt;font-family:"Times New Roman","serif"'>Команда</span></b></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    12.0pt;font-family:"Times New Roman","serif"'>И</span></b></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    12.0pt;font-family:"Times New Roman","serif"'>В</span></b></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    12.0pt;font-family:"Times New Roman","serif"'>Н</span></b></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    12.0pt;font-family:"Times New Roman","serif"'>П</span></b></p>

    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    12.0pt;font-family:"Times New Roman","serif"'>Мячи</span></b></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    12.0pt;font-family:"Times New Roman","serif"'>О</span></b></p>
    </td>
   </tr>

   <tr>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    12.0pt;font-family:"Times New Roman","serif"'>ИРАН</span></b></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>0</span></p>

    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>18-13</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>4</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    12.0pt;font-family:"Times New Roman","serif"'>НИДЕРЛАНДЫ</span></b></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2</span></p>

    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>0</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>7-7</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>4</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>ИТАЛИЯ</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>

    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>0</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>15-16</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2</span></p>

    </td>
   </tr>
   <tr>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>4</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>ПАРАГВАЙ</span></p>

    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>0</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>14-18</span></p>

    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2</span></p>
    </td>
   </tr>
  </table>
  </div>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><span style='font-size:14.0pt;
  font-family:"Times New Roman","serif";color:blue'>Группа </span><span
  lang=EN-US style='font-size:14.0pt;font-family:"Times New Roman","serif";
  color:blue'>C</span><span style='font-size:12.0pt;font-family:"Times New Roman","serif"'><br>

  <b>16.11.92</b><br>
  БРАЗИЛИЯ - АВСТРАЛИЯ 3-0 (2-0) <br>
  КОСТА-РИКА-БЕЛЬГИЯ 2-6 (1-3) <br>
  <b>19.11.92 </b><br>
  АВСТРАЛИЯ-БЕЛЬГИЯ 1-2 (1-1) <br>
  БРАЗИЛИЯ - КОСТА-РИКА 15-1 (4-0) <br>

  <b>21.11.92 </b><br>
  БРАЗИЛИЯ - БЕЛЬГИЯ 5-0 (2-0) <br>
  АВСТРАЛИЯ-КОСТА-РИКА 8-6 (5-2) </span></p>
  <div align=center>
  <table class=MsoNormalTable border=1 cellpadding=0 width="50%"
   style='width:50.0%;border:outset blue 1.5pt'>
   <tr>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>М</span></b></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Команда</span></b></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>И</span></b></p>

    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>В</span></b></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Н</span></b></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>П</span></b></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Мячи</span></b></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>О</span></b></p>

    </td>
   </tr>
   <tr>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>БРАЗИЛИЯ</span></b></p>

    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>23-1</span></p>

    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>6</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>

    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>БЕЛЬГИЯ</span></b></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>

    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>8-8</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
    </td>
   </tr>

   <tr>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>АВСТРАЛИЯ</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>

    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>9-11</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>4</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>КОСТА-РИКА</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>0</span></p>

    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>0</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>9-29</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>0</span></p>
    </td>
   </tr>
  </table>
  </div>

  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><span style='font-size:14.0pt;
  font-family:"Times New Roman","serif";color:blue'>Группа </span><span
  lang=EN-US style='font-size:14.0pt;font-family:"Times New Roman","serif";
  color:blue'>D</span><span style='font-size:12.0pt;font-family:"Times New Roman","serif"'><br>
  <b>17.11.92 </b><br>
  КИТАЙ - ИСПАНИЯ 5-6 (2-2) <br>
  РОССИЯ-США 3-8 (0-3) <br>
  <b>19.11.92 </b><br>
  ИСПАНИЯ-США 5-3 (1-0) <br>

  КИТАЙ - РОССИЯ 1-10 (1-2) <br>
  <b>21.11.92 </b><br>
  КИТАЙ - США 1-7 (0-4) <br>
  ИСПАНИЯ-РОССИЯ 7-7 (2-1) </span></p>
  <div align=center>
  <table class=MsoNormalTable border=1 cellpadding=0 width="50%"
   style='width:50.0%;border:outset blue 1.5pt'>
   <tr>

    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>М</span></b></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Команда</span></b></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>И</span></b></p>

    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>В</span></b></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Н</span></b></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>П</span></b></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Мячи</span></b></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>О</span></b></p>

    </td>
   </tr>
   <tr>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>ИСПАНИЯ</span></b></p>

    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>18-15</span></p>

    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>5</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>

    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>США</span></b></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>

    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>18-9</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
    </td>
   </tr>

   <tr>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>РОССИЯ</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>

    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>20-16</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>КИТАЙ</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>

    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>7-23</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
    </td>
   </tr>
  </table>
  </div>

  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><span lang=EN-US><a
  href="http://futsal.ucoz.ru/_pu/2/47493241.jpg"
  title="&quot;Нажмите, для просмотра в полном размере...&quot; t "><span
  lang=RU style='font-size:12.0pt;font-family:"Times New Roman","serif";
  color:blue;text-decoration:none'><img border=0 width=400 height=334
  id="Рисунок 1" src="1992.files/image003.jpg"
  alt="http://futsal.ucoz.ru/_pu/2/s47493241.jpg"></span></a></span></p>
  </td>
 </tr>
 <tr>
  <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><span style='font-size:18.0pt;
  font-family:"Times New Roman","serif";color:crimson'>Второй этап</span><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'><br>
  </span><span style='font-size:14.0pt;font-family:"Times New Roman","serif";
  color:blue'>Группа </span><span lang=EN-US style='font-size:14.0pt;
  font-family:"Times New Roman","serif";color:blue'>E</span><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'><br>

  <b>23.11.92 </b><br>
  АРГЕНТИНА - НИДЕРЛАНДЫ 1-4 (0-0) <br>
  БРАЗИЛИЯ - США 2-2 (0-1) <br>
  <b>24.11.92 </b><br>
  АРГЕНТИНА - БРАЗИЛИЯ 1-5 (1-3) <br>
  НИДЕРЛАНДЫ-США 3-3 (1-2) <br>

  <b>25.11.92 </b><br>
  АРГЕНТИНА - США 3-6 (2-2) <br>
  НИДЕРЛАНДЫ - БРАЗИЛИЯ 1-6 (0-3) </span></p>
  <div align=center>
  <table class=MsoNormalTable border=1 cellpadding=0 width="50%"
   style='width:50.0%;border:outset blue 1.5pt'>
   <tr>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>М</span></b></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Команда</span></b></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>И</span></b></p>

    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>В</span></b></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Н</span></b></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>П</span></b></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Мячи</span></b></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>О</span></b></p>

    </td>
   </tr>
   <tr>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>БРАЗИЛИЯ</span></b></p>

    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>13-4</span></p>

    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>5</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2</span></p>

    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    12.0pt;font-family:"Times New Roman","serif"'>США</span></b></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>0</span></p>

    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>11-8</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>4</span></p>
    </td>
   </tr>

   <tr>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>НИДЕРЛАНДЫ</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>1</span></p>

    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>8-10</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>4</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>АРГЕНТИНА</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>0</span></p>

    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>0</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>5-15</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>0</span></p>
    </td>
   </tr>
  </table>
  </div>

  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><span style='font-size:14.0pt;
  font-family:"Times New Roman","serif";color:blue'>Группа </span><span
  lang=EN-US style='font-size:14.0pt;font-family:"Times New Roman","serif";
  color:blue'>F</span><span style='font-size:12.0pt;font-family:"Times New Roman","serif"'><br>
  <b>23.11.92</b><br>
  ИРАН-ПОЛЬША 2-0 (0-0) <br>
  ИСПАНИЯ-БЕЛЬГИЯ 5-3 (1-1) <br>
  <b>24.11.92 </b><br>
  ИРАН-ИСПАНИЯ 4-2 (0-1) <br>

  ПОЛЬША-БЕЛЬГИЯ 1-4 (0-3) <br>
  <b>25.11.92 </b><br>
  ИРАН-БЕЛЬГИЯ 4-2 (1-0) <br>
  ПОЛЬША-ИСПАНИЯ 3-7 (1-5) </span></p>
  <div align=center>
  <table class=MsoNormalTable border=1 cellpadding=0 width="50%"
   style='width:50.0%;border:outset blue 1.5pt'>
   <tr>

    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>М</span></b></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Команда</span></b></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>И</span></b></p>

    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>В</span></b></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Н</span></b></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>П</span></b></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Мячи</span></b></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>О</span></b></p>

    </td>
   </tr>
   <tr>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>ИРАН</span></b></p>

    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>10-4</span></p>

    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>6</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>

    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>ИСПАНИЯ</span></b></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>

    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>14-10</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
    </td>
   </tr>

   <tr>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>БЕЛЬГИЯ</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>

    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>9-10</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>ПОЛЬША</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>

    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4-13</span></p>
    </td>
    <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
    </td>
   </tr>
  </table>
  </div>

  </td>
 </tr>
 <tr>
  <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><span style='font-size:18.0pt;
  font-family:"Times New Roman","serif";color:crimson'>Полуфиналы</span><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'><br>
  <b>27.11.92</b><br>
  ИРАН-США 2-4 (1-1) <br>

  БРАЗИЛИЯ - ИСПАНИЯ 4-1 (3-0) </span></p>
  </td>
 </tr>
 <tr>
  <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><span style='font-size:18.0pt;
  font-family:"Times New Roman","serif";color:crimson'>Матч за 3-е место</span><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'><br>
  <b>28.11.92 ИСПАНИЯ-ИРАН 9-6 (6-4) </b></span></p>

  </td>
 </tr>
 <tr>
  <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><span lang=EN-US style='font-size:18.0pt;
  font-family:"Times New Roman","serif";color:crimson'>Финал</span><span
  lang=EN-US style='font-size:12.0pt;font-family:"Times New Roman","serif"'><br>
  <b>28.11.92 БРАЗИЛИЯ - США 4-1 (1-0) </b></span></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><span lang=EN-US style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'>&nbsp;</span></p>
  </td>

 </tr>
</table>

</div>

<p class=MsoNormal>&nbsp;</p>

</div>
