<div class=Section1>

<p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
normal'><span lang=EN-US style='font-size:12.0pt;font-family:"Times New Roman","serif"'>5
ЧЕМПИОНАТ МИРА 2004</span></p>

<table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 width="100%"
 style='width:100.0%'>
 <tr>
  <td style='padding:1.5pt 1.5pt 1.5pt 1.5pt'>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span lang=EN-US style='font-size:
  14.0pt;font-family:"Times New Roman","serif"'>ЧЕМПИОНАТ МИРА 2004</span></b></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span lang=EN-US style='font-size:
  12.0pt;font-family:"Times New Roman","serif"'>ТАЙВАНЬ</span></b></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'><img width=216 height=157
  id="Рисунок 1" src="2004.files/image001.jpg"
  alt="http://futsal.ucoz.ru/_pu/2/40101.jpg"></span></b></p>
  <div align=center>
  <table class=MsoNormalTable border=1 cellpadding=0 width="100%"
   style='width:100.0%;border:outset black 1.5pt'>

   <tr>
    <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:18.0pt;
    font-family:"Times New Roman","serif";color:crimson'>Первый этап</span><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'><br>
    </span><span style='font-size:14.0pt;font-family:"Times New Roman","serif";
    color:blue'>Группа А</span><b><span style='font-size:12.0pt;font-family:
    "Times New Roman","serif"'><br>
    21.11.2004 <br>
    Тайвань - Египет 0:12 (0:6)<br>
    Испания-Украина 2-0 (2-0) <br>

    23.11.2004<br>
    Тайвань - Испания 0-10 (0-3) <br>
    Египет-Украина 4-5 (2-0) <br>
    25.11.2004<br>
    Украина-Тайвань 7-2 (5-1) <br>
    Египет-Испания 0-7 (0-5) </span></b></p>

    <div align=center>
    <table class=MsoNormalTable border=1 cellpadding=0 width="50%"
     style='width:50.0%;border:outset blue 1.5pt'>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>М</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>Команда</span></b></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>И</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>В</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>Н</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>П</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>Мячи</span></b></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>О</span></b></p>
      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>1</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>Испания</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>0</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>19-0</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>9</span></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>Украина</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>0</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>12-8</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>6</span></p>
      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>Египет</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>1</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>16-12</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>Тайвань</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>3</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>2-29</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>0</span></p>

      </td>
     </tr>
    </table>
    </div>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    12.0pt;font-family:"Times New Roman","serif"'><br>
    </span></b><b><span style='font-size:14.0pt;font-family:"Times New Roman","serif";
    color:blue'>Группа </span></b><b><span lang=EN-US style='font-size:14.0pt;
    font-family:"Times New Roman","serif";color:blue'>B</span></b><b><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'><br>
    22.11.2004<br>

    Австралия - Бразилия 0-10 (0-4) <br>
    Чешская республика - Таиланд 2-1 (1-0) <br>
    24.11.2004 <br>
    Австралия-Чешская республика 0-5 (0-1) <br>
    Бразилия - Таиланд 9-1 (2-0) <br>
    26.11.2004<br>

    Таиланд - Австралия 2-1 (0-0) <br>
    Бразилия - Чешская республика 4-1 (2-1) </span></b></p>
    <div align=center>
    <table class=MsoNormalTable border=1 cellpadding=0 width="50%"
     style='width:50.0%;border:outset blue 1.5pt'>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>М</span></b></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Команда</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>И</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>В</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Н</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>П</span></b></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Мячи</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>О</span></b></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Бразилия</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>23-2</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>9</span></p>
      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Чешскаяреспублика</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>8-5</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>6</span></p>
      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Тайланд</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>5-13</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>

      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Австралия</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>2-18</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>
     </tr>
    </table>
    </div>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    14.0pt;font-family:"Times New Roman","serif";color:blue'>Группа </span></b><b><span
    lang=EN-US style='font-size:14.0pt;font-family:"Times New Roman","serif";
    color:blue'>C</span></b><b><span style='font-size:12.0pt;font-family:"Times New Roman","serif"'><br>

    Группа С<br>
    21.11.2004<br>
    Италия-США 6-3 (2-1)<br>
    Япония - Парагвай 4-5 (3-2) <br>
    23.11.2004 <br>
    Италия - Япония 5-0 (2-0)<br>

    США - Парагвай 3-1 (1-0) <br>
    25.11.2004<br>
    Парагвай - Италия 2-4 (1-2) <br>
    США - Япония 1-1 (1-0) </span></b></p>
    <div align=center>
    <table class=MsoNormalTable border=1 cellpadding=0 width="50%"
     style='width:50.0%;border:outset blue 1.5pt'>
     <tr>

      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>М</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>Команда</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>И</span></b></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>В</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>Н</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>П</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>Мячи</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>О</span></b></p>

      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>Италия</span></b></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>15-5</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>9</span></p>
      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>2</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>США</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>1</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>7-8</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>Парагвай</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>0</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>8-11</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>Япония</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>0</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>5-11</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
     </tr>
    </table>
    </div>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    14.0pt;font-family:"Times New Roman","serif";color:blue'>Группа </span></b><b><span
    lang=EN-US style='font-size:14.0pt;font-family:"Times New Roman","serif";
    color:blue'>D</span></b><b><span style='font-size:12.0pt;font-family:"Times New Roman","serif"'><br>
    22.11.2004 <br>
    Иран-Португалия 0-4 (0-2) <br>
    Куба - Аргентина 0-3 (0-0) <br>
    24.11.2004<br>
    Иран-Куба 8-3 (4-0) <br>

    Португалия - Аргентина 0-1 (0-1) <br>
    26.11.2004 <br>
    Аргентина - Иран 6-1 (1-1) <br>
    Португалия-Куба 5-0 (2-0) </span></b></p>
    <div align=center>
    <table class=MsoNormalTable border=1 cellpadding=0 width="50%"
     style='width:50.0%;border:outset blue 1.5pt'>
     <tr>

      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>М</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Команда</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>И</span></b></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>В</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Н</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>П</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Мячи</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>О</span></b></p>

      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Аргентина</span></b></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>10-1</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>9</span></p>
      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Португалия</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>9-1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>6</span></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Иран</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>9-13</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Куба</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3-16</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>
     </tr>
    </table>
    </div>

    </td>
   </tr>
   <tr>
    <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:18.0pt;
    font-family:"Times New Roman","serif";color:crimson'>Второй этап</span><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'><br>
    </span><span style='font-size:14.0pt;font-family:"Times New Roman","serif";
    color:blue'>Группа </span><span lang=EN-US style='font-size:14.0pt;
    font-family:"Times New Roman","serif";color:blue'>E</span><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'><br>
    <b>28.11.2004<br>

    Испания-Чешская республика 2-0 (0-0) <br>
    Италия-Португалия 0-0 (0-0) <br>
    29.11.2004<br>
    Испания-Италия 2-3 (1-3) <br>
    Чешская республика-Португалия 4-8 (3-3) <br>
    01.12.2004<br>

    Испания-Португалия 3-1 (2-1)<br>
    Чешская республика-Италия 0-3 (0-2) </b></span></p>
    <div align=center>
    <table class=MsoNormalTable border=1 cellpadding=0 width="50%"
     style='width:50.0%;border:outset blue 1.5pt'>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>М</span></b></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>Команда</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>И</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>В</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>Н</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>П</span></b></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>Мячи</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>О</span></b></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>Италия</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>1</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>6-2</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>7</span></p>
      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>Испания</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>2</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>7-4</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>6</span></p>
      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>Португалия</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>3</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>9-7</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>4</span></p>

      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>Чехия</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>4-13</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span style='font-size:
      12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>
     </tr>
    </table>
    </div>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><b><span style='font-size:
    14.0pt;font-family:"Times New Roman","serif";color:blue'>Группа </span></b><b><span
    lang=EN-US style='font-size:14.0pt;font-family:"Times New Roman","serif";
    color:blue'>F</span></b><b><span style='font-size:12.0pt;font-family:"Times New Roman","serif"'><br>

    28.11.2004 <br>
    Бразилия - Украина 6-0 (2-0) <br>
    Аргентина - США 2-1 (2-0) <br>
    29.11.2004<br>
    Бразилия - Аргентина 2-1 (2-1) <br>
    30 - </span></b><b><span lang=EN-US style='font-size:12.0pt;font-family:
    "Times New Roman","serif"'>NTU</span></b><b><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'> - 20:00 - Украина - США 3-1 (1-1) <br>

    01.12.2004 <br>
    Бразилия -США 8-5 (3-1) <br>
    Украина - Аргентина 0-0 (0-0) </span></b></p>
    <div align=center>
    <table class=MsoNormalTable border=1 cellpadding=0 width="50%"
     style='width:50.0%;border:outset blue 1.5pt'>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>М</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Команда</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>И</span></b></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>В</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Н</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>П</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Мячи</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>О</span></b></p>

      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Бразилия</span></b></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>16-6</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>9</span></p>
      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Аргентина</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3-3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Украина</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3-7</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>США</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>7-13</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>
     </tr>
    </table>
    </div>

    </td>
   </tr>
   <tr>
    <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:18.0pt;
    font-family:"Times New Roman","serif";color:crimson'>Полуфиналы</span><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'><br>
    <b>03.12.2004 <br>
    Бразилия - Испания 6-7(2-2; 2-2; 0-0) <br>

    Италия - Аргентина 7-4 (3-0) </b></span></p>
    </td>
   </tr>
   <tr>
    <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:18.0pt;
    font-family:"Times New Roman","serif";color:crimson'>Матч за 3-е место</span><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'><br>
    <b>05.12.2004 <br>

    Бразилия - Аргентина 7-4 (6-1) </b></span></p>
    </td>
   </tr>
   <tr>
    <td style='border:inset black 1.0pt;padding:1.5pt 1.5pt 1.5pt 1.5pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:18.0pt;font-family:"Times New Roman","serif";color:crimson'>Финал</span><span
    lang=EN-US style='font-size:12.0pt;font-family:"Times New Roman","serif"'><br>
    <b>05.12.2004 <br>

    Испания-Италия 2-1 (0-0)</b></span></p>
    </td>
   </tr>
  </table>
  </div>
  </td>
 </tr>
</table>

<p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
text-align:center;line-height:normal'><b><span lang=EN-US style='font-size:
12.0pt;font-family:"Times New Roman","serif"'>Примечания:</span></b></p>

<p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
text-align:center;line-height:normal'><span style='font-size:12.0pt;font-family:
"Times New Roman","serif"'><img width=350 height=291 id="Рисунок 2"
src="2004.files/image002.jpg" alt="http://futsal.ucoz.ru/_pu/2/50095.jpg"></span></p>

<p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
text-align:center;line-height:normal'><span lang=EN-US style='font-size:12.0pt;
font-family:"Times New Roman","serif"'>&nbsp;</span></p>

<p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
normal'><span lang=EN-US style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Group
1 (in Slovenia)<br>
05-11-03<br>
Serbia &amp; Mont.&nbsp;&nbsp;&nbsp;&nbsp; 6-3&nbsp; Georgia<br>

Slovenia&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 12-0&nbsp;
Moldova<br>
06-11-03 <br>
Moldova&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
4-6&nbsp; Serbia &amp; Mont.<br>
Slovenia&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 5-0&nbsp;

Georgia<br>
08-11-03&nbsp; <br>
Georgia&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
6-5&nbsp; Moldova<br>
Serbia &amp; Mont.&nbsp;&nbsp;&nbsp;&nbsp; 1-2&nbsp; Slovenia<br>

<br>
1 SLOVENIA&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3 3 0 0
19- 1&nbsp; 9<br>
2 Serbia &amp; Mont.&nbsp;&nbsp;&nbsp;&nbsp; 3 2 0 1 13- 9&nbsp; 6<br>
3 Georgia&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3 1
0 2&nbsp; 8-17&nbsp; 3<br>

4 Moldova&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3 0
0 3&nbsp; 5-23&nbsp; 0<br>
<br>
Group 2 (in Italy)<br>
07-11-03 <br>
Italy&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
8-0&nbsp; France<br>

Belgium&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
4-1&nbsp; Finland<br>
08-11-03 <br>
France&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
2-3&nbsp; Belgium<br>
Italy&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
12-0&nbsp; Finland<br>

10-11-03&nbsp; <br>
Finland&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
3-2&nbsp; France<br>
Belgium&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
0-2&nbsp; Italy<br>
<br>
1
ITALY&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

3 3 0 0 22- 0&nbsp; 9<br>
2 Belgium&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3 2
0 1&nbsp; 7- 5&nbsp; 6<br>
3 Finland&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3 1
0 2&nbsp; 4-18&nbsp; 3<br>

4
France&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
3 0 0 3&nbsp; 4-14&nbsp; 0<br>
<br>
Group 3 (in Bosnia-Herzegovina)<br>
05-11-03 <br>
Russia&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
6-4&nbsp; Macedonia FYR<br>

06-11-03 <br>
Bosnia-Herz.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3-2&nbsp; Russia<br>
07-11-03 <br>
Macedonia FYR&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 0-2&nbsp; Bosnia-Herz.<br>
<br>

1 BOSNIA-HERZ.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2 2 0 0&nbsp; 5- 2&nbsp; 6<br>
2
Russia&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
2 1 0 1&nbsp; 8- 7&nbsp; 3<br>
3 Macedonia FYR&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2 0 0 2&nbsp; 4- 8&nbsp; 0<br>

<br>
Group 4 (in Andorra)<br>
04-11-03 <br>
Kazakhstan&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1-3&nbsp; Ukraine<br>
05-11-03 <br>
Andorra&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
1-4&nbsp; Kazakhstan<br>

06-11-03 <br>
Ukraine&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
6-1&nbsp; Andorra<br>
<br>
1 UKRAINE&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2 2
0 0&nbsp; 9- 2&nbsp; 6<br>

2 Kazakhstan&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2 1 0 1&nbsp; 5-
4&nbsp; 3<br>
3 Andorra&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2 0
0 2&nbsp; 2-10&nbsp; 0<br>
<br>

Group 5 (in Lithuania)<br>
01-11-03 <br>
Netherlands&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 5-5&nbsp; Lithuania<br>
02-11-03 <br>
Belarus&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
4-1&nbsp; Netherlands<br>

03-11-03 <br>
Lithuania&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3-5&nbsp;
Belarus<br>
<br>
1 BELARUS&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2 2
0 0&nbsp; 9- 4&nbsp; 6<br>

2 Lithuania&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2 0 1 1&nbsp;
8-10&nbsp; 1<br>
3 Netherlands&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2 0 1 1&nbsp; 6-
9&nbsp; 1<br>
<br>

Group 6 (in Portugal)<br>
06-11-03 <br>
Greece&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
1-8&nbsp; Portugal<br>
07-11-03 <br>
Albania&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1-12
Greece<br>
08-11-03 <br>

Portugal&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 18-6&nbsp;
Albania<br>
<br>
1 PORTUGAL&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2 2 0 0
26- 7&nbsp; 6<br>
2
Greece&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
2 1 0 1 14-12&nbsp; 3<br>

3 Albania&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2 0
0 2 10-31&nbsp; 0<br>
<br>
Group 7 (in Cyprus)<br>
05-11-03 <br>
Poland&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
6-1&nbsp; Azerbaijan<br>

06-11-03 <br>
Cyprus&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
0-13 Poland<br>
07-11-03 <br>
Azerbaijan&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 4-4&nbsp; Cyprus<br>
<br>
1
POLAND&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

2 2 0 0 19- 1&nbsp; 6<br>
2 Azerbaijan&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2 0 1 1&nbsp; 5-10&nbsp;
1<br>
3
Cyprus&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
2 0 1 1&nbsp; 4-17&nbsp; 1<br>

<br>
Group 8 (in Croatia)<br>
06-11-03 <br>
Armenia&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
2-9&nbsp; Croatia<br>
07-11-03 <br>
Hungary&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
5-2&nbsp; Armenia<br>

08-11-03 <br>
Croatia&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
5-7&nbsp; Hungary<br>
<br>
1 HUNGARY&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2 2
0 0 12- 7&nbsp; 6<br>
2 Croatia&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2 1
0 1 14- 9&nbsp; 3<br>

3 Armenia&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2 0
0 1&nbsp; 4-14&nbsp; 0<br>
<br>
Group 9 (in Czech Republic)<br>
04-11-03 <br>
Czech Republic&nbsp;&nbsp;&nbsp;&nbsp; 5-3&nbsp; Romania<br>

05-11-03 <br>
Romania&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
1-5&nbsp; Israel<br>
06-11-03 <br>
Israel&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
2-5&nbsp; Czech Republic<br>
<br>

1 CZECH REPUBLIC&nbsp;&nbsp;&nbsp;&nbsp; 2 2 0 0 10- 5&nbsp; 6<br>
2 Israel&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
2 1 0 1&nbsp; 7- 6&nbsp; 3<br>
3 Romania&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2 0
0 2&nbsp; 4-10&nbsp; 0<br>

<br>
Group 10 (in Latvia)<br>
07-11-03 <br>
Spain&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
3-1&nbsp; Latvia<br>
08-11-03 <br>
Slovakia&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2-5&nbsp;

Spain<br>
09-11-03 <br>
Latvia&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
2-2&nbsp; Slovakia<br>
<br>
1
SPAIN&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
2 2 0 0&nbsp; 8- 3&nbsp; 6<br>

2 Latvia&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
2 0 1 1&nbsp; 3- 5&nbsp; 1<br>
3 Slovakia&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2 0 1
1&nbsp; 4- 7&nbsp; 1<br>
<br>

<br>
Play-offs<br>
10/17-12-03<br>
Bosnia-Herz.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 5-7&nbsp; CZECH REPUBLIC<br>
CZECH REPUBLIC&nbsp;&nbsp;&nbsp;&nbsp; 4-4&nbsp; Bosnia-Herz.<br>

<br>
10/17-12-03<br>
Poland&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
2-7&nbsp; PORTUGAL<br>
PORTUGAL&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 7-2&nbsp;
Poland<br>
<br>
10/17-12-03<br>

Slovenia&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1-4&nbsp;
SPAIN<br>
SPAIN&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
4-1&nbsp; Slovenia<br>
<br>
10/17-12-03<br>
Belarus&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

0-4&nbsp; UKRAINE<br>
UKRAINE&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
3-2&nbsp; Belarus<br>
<br>
11/17-12-03<br>
Hungary&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
0-4&nbsp; ITALY<br>

ITALY&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
7-0&nbsp; Hungary</span></p>

<p class=MsoNormal><a name="_GoBack"></a><span lang=EN-US>&nbsp;</span></p>

</div>
