<div class=Section1>

<p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
normal'><span lang=EN-US style='font-size:12.0pt;font-family:"Times New Roman","serif"'>6
<a name="_GoBack">ЧЕМПИОНАТ МИРА 2008</a></span></p>

<table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 width="100%"
 style='width:100.0%'>
 <tr>
  <td style='padding:1.5pt 1.5pt 1.5pt 1.5pt'>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  style='font-size:14.0pt;font-family:"Times New Roman","serif"'>6 ЧЕМПИОНАТ
  МИРА 2008</span></b></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'>Бразилия (Бразилиа,Рио-де-Жанейро)</span></b></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><span lang=EN-US style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'>&nbsp;</span></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span lang=EN-US style='font-size:
  12.0pt;font-family:"Times New Roman","serif"'>1-19 октября&nbsp;2008 года</span></b></p>

  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'><img
  width=156 height=180 id="Рисунок 9" src="2008.files/image001.jpg"
  alt="http://futsal.ucoz.ru/_pu/2/59128.jpg"></span></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  lang=EN-US style='font-size:12.0pt;font-family:"Times New Roman","serif"'>АРЕНА
  (БРАЗИЛИА)</span></b></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  lang=EN-US style='font-size:12.0pt;font-family:"Times New Roman","serif"'>The
  JornalistaNilson Nelson Sports Hall</span></b></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'><img
  width=300 height=155 id="Рисунок 8" src="2008.files/image002.jpg"
  alt="http://futsal.ucoz.ru/_pu/2/20924.jpg"></span></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'>ФИНАЛ:</span></b></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><span lang=EN-US style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'>&nbsp;</span></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'>19 октября:</span></b></p>

  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'>Бразилия-Испания 2:2 (0:0) по пенальти
  4:3</span></b></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><span lang=EN-US style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'>&nbsp;</span></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><span
  lang=EN-US><a href="http://futsal.ucoz.ru/_pu/2/95955.jpg"
  title="&quot;Нажмите, для просмотра в полном размере...&quot; t "><b><span
  lang=RU style='font-size:12.0pt;font-family:"Times New Roman","serif";
  text-decoration:none'><img border=0 width=400 height=300 id="Рисунок 7"
  src="2008.files/image003.jpg" alt="http://futsal.ucoz.ru/_pu/2/s95955.jpg"></span></b></a></span></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'>Матч за 3 место:</span></b></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><span lang=EN-US style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'>&nbsp;</span></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'>18 октября:</span></b></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><span lang=EN-US style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'>&nbsp;</span></p>

  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><span lang=EN-US><a
  href="http://futsal.ucoz.ru/CHEMP-MIRA/ChM-2008/PLAYOFF/3_mesto.txt"><b><span
  lang=RU style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Италия-Россия
  2:1 (1:0)</span></b></a></span></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'><br>
  </span></b><b><span lang=EN-US style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span></b></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'>Полуфиналы: </span></b></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><span lang=EN-US style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'>&nbsp;</span></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'>16 октября:</span></b></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Италия-Испания
  1:1 доп.время 1:2</span></b></p>

  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><span
  lang=EN-US><a
  href="http://futsal.ucoz.ru/CHEMP-MIRA/ChM-2008/PLAYOFF/1-2_finala.txt"><b><span
  lang=RU style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Россия-Бразилия
  2:4 (1:3)</span></b></a></span></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'>ЧЕТВЕРТЬФИНАЛЬНЫЙ
  ГРУППОВОЙ ЭТАП</span></b><span style='font-size:12.0pt;font-family:"Times New Roman","serif"'><br>
  <br>
  <b>Группа Е:</b></span></p>
  <div align=center>
  <table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 width="100%"
   style='width:100.0%;border-collapse:collapse'>
   <tr>

    <td style='border:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>м</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>группа Е</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>1</span></p>

    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>4</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>м</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>о</span></p>

    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>Бразилия</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US><a
    href="http://www.fifa.com/futsalworldcup/matches/round=250129/match=300055145/index.html"
    target=null><span lang=RU style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3:0</span></a></span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US><a
    href="http://www.fifa.com/futsalworldcup/matches/round=250129/match=300055147/index.html"
    target=null><span lang=RU style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1:0</span></a></span></p>
    </td>

    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US><a
    href="http://www.fifa.com/futsalworldcup/matches/round=250129/match=300055143/index.html"
    target=null><span lang=RU style='font-size:12.0pt;font-family:"Times New Roman","serif"'>5:3</span></a></span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>9-3</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>9</span></p>

    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>Италия</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US><a
    href="http://www.fifa.com/futsalworldcup/matches/round=250129/match=300055145/index.html"
    target=null><span lang=RU style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0:3</span></a></span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US><a
    href="http://www.fifa.com/futsalworldcup/matches/round=250129/match=300055142/index.html"
    target=null><span lang=RU style='font-size:12.0pt;font-family:"Times New Roman","serif"'>5:5</span></a></span></p>
    </td>

    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US><a
    href="http://www.fifa.com/futsalworldcup/matches/round=250129/match=300055146/index.html"
    target=null><span lang=RU style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4:0</span></a></span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>9-8</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>4</span></p>

    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>Иран</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US><a
    href="http://www.fifa.com/futsalworldcup/matches/round=250129/match=300055147/index.html"
    target=null><span lang=RU style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0:1</span></a></span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US><a
    href="http://www.fifa.com/futsalworldcup/matches/round=250129/match=300055142/index.html"
    target=null><span lang=RU style='font-size:12.0pt;font-family:"Times New Roman","serif"'>5:5</span></a></span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>

    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US><a
    href="http://www.fifa.com/futsalworldcup/matches/round=250129/match=300055144/index.html"
    target=null><span lang=RU style='font-size:12.0pt;font-family:"Times New Roman","serif"'>5:4</span></a></span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>10-10</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>4</span></p>

    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>4</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>Украина</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US><a
    href="http://www.fifa.com/futsalworldcup/matches/round=250129/match=300055143/index.html"
    target=null><span lang=RU style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3:5</span></a></span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US><a
    href="http://www.fifa.com/futsalworldcup/matches/round=250129/match=300055146/index.html"
    target=null><span lang=RU style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0:4</span></a></span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US><a
    href="http://www.fifa.com/futsalworldcup/matches/round=250129/match=300055144/index.html"
    target=null><span lang=RU style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4:5</span></a></span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>7-14</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>0</span></p>

    </td>
   </tr>
  </table>
  </div>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'><br>
  <b>Группа </b></span><b><span lang=EN-US style='font-size:12.0pt;font-family:
  "Times New Roman","serif"'>F</span></b><b><span style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'>: </span></b><b><span lang=EN-US
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span></b></p>
  <div align=center>

  <table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 width="100%"
   style='width:100.0%;border-collapse:collapse'>
   <tr>
    <td style='border:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>м</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>группа F</span></p>
    </td>

    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>

    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>м</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>о</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Испания</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US><a
    href="http://www.fifa.com/futsalworldcup/matches/round=250129/match=300055153/index.html"
    target=null><span style='font-size:12.0pt;font-family:"Times New Roman","serif"'>5:2</span></a></span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US><a
    href="http://www.fifa.com/futsalworldcup/matches/round=250129/match=300055150/index.html"
    target=null><span style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2:1</span></a></span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US><a
    href="http://www.fifa.com/futsalworldcup/matches/round=250129/match=300055148/index.html"
    target=null><span style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4:1</span></a></span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>11-4</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>9</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Россия</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US><a
    href="http://www.fifa.com/futsalworldcup/matches/round=250129/match=300055153/index.html"
    target=null><span style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2:5</span></a></span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US><a
    href="http://www.fifa.com/futsalworldcup/matches/round=250129/match=300055149/index.html"
    target=null><span style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2:2</span></a></span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US><a
    href="http://www.fifa.com/futsalworldcup/matches/round=250129/match=300055151/index.html"
    target=null><span style='font-size:12.0pt;font-family:"Times New Roman","serif"'>5:4</span></a></span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>9-11</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Аргентина</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US><a
    href="http://www.fifa.com/futsalworldcup/matches/round=250129/match=300055150/index.html"
    target=null><span style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1:2</span></a></span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US><a
    href="http://www.fifa.com/futsalworldcup/matches/round=250129/match=300055149/index.html"
    target=null><span style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2:2</span></a></span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US><a
    href="http://www.fifa.com/futsalworldcup/matches/round=250129/match=300055152/index.html"
    target=null><span style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3:3</span></a></span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>6-7</span></p>
    </td>

    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
    </td>

    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Парагвай</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US><a
    href="http://www.fifa.com/futsalworldcup/matches/round=250129/match=300055148/index.html"
    target=null><span style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1:4</span></a></span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US><a
    href="http://www.fifa.com/futsalworldcup/matches/round=250129/match=300055151/index.html"
    target=null><span style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4:5</span></a></span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US><a
    href="http://www.fifa.com/futsalworldcup/matches/round=250129/match=300055152/index.html"
    target=null><span style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3:3</span></a></span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>8-12</span></p>
    </td>

    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
    </td>
   </tr>
  </table>
  </div>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><span
  lang=EN-US style='font-size:12.0pt;font-family:"Times New Roman","serif"'><br>
  <b>ГРУППОВОЙ ЭТАП</b><br>

  <br>
  <b>Группа А</b></span></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><span
  lang=EN-US><a href="http://futsal.ucoz.ru/_pu/2/83827.jpg"
  title="&quot;Нажмите, для просмотра в полном размере...&quot; t "><span
  lang=RU style='font-size:12.0pt;font-family:"Times New Roman","serif";
  text-decoration:none'><img border=0 width=400 height=283 id="Рисунок 6"
  src="2008.files/image004.jpg" alt="http://futsal.ucoz.ru/_pu/2/s83827.jpg"></span></a></span></p>
  <p class=MsoNormal style='line-height:normal'><span lang=EN-US
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span></p>
  <table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 width="100%"
   style='width:100.0%;border-collapse:collapse'>
   <tr>
    <td style='border:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>Группа А</span></p>

    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>4</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>5</span></p>

    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>м</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>о</span></p>
    </td>
   </tr>

   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>Бразилия</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>7:0</span></p>
    </td>

    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>12:1</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>9:0</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>21:0</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>49-1</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>12</span></p>
    </td>
   </tr>

   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Россия</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>0:7</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>

    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>9:1</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>10:5</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>31:2</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>50-15</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>9</span></p>
    </td>
   </tr>

   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>Япония</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>1:12</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>1:9</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>4:1</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>7:2</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>13-24</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>6</span></p>
    </td>
   </tr>

   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>Куба</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>0:9</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>5:10</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>1:4</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>10:2</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>16-23</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
   </tr>

   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>Соломоновы о-ва</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>0:21</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2:31</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2:7</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2:10</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>6-69</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>0</span></p>
    </td>

   </tr>
  </table>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Группа В</span></b></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><span
  lang=EN-US><a href="http://futsal.ucoz.ru/_pu/2/75370.jpg"
  title="&quot;Нажмите, для просмотра в полном размере...&quot; t "><span
  lang=RU style='font-size:12.0pt;font-family:"Times New Roman","serif";
  text-decoration:none'><img border=0 width=400 height=300 id="Рисунок 5"
  src="2008.files/image005.jpg" alt="http://futsal.ucoz.ru/_pu/2/s75370.jpg"></span></a></span></p>
  <p class=MsoNormal style='line-height:normal'><span lang=EN-US
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span></p>
  <table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 width="100%"
   style='width:100.0%;border-collapse:collapse'>
   <tr>
    <td style='border:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>Группа В</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2</span></p>

    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>4</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>5</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>м</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>о</span></p>

    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>Парагвай</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>4:2</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2:3</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>8:0</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>5:0</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>19-5</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>9</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>Италия</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2:4</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3:1</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>1:0</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>6:1</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>12-6</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>9</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>Португалия</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3:2</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>1:3</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3:2</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>8:1</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>15-8</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>9</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>Тайланд</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>0:8</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>0:1</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2:3</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>5:3</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>7-15</span></p>
    </td>

    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>США</span></p>
    </td>

    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>0:5</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>1:6</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>1:8</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3:5</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>5-24</span></p>
    </td>

    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>0</span></p>
    </td>
   </tr>
  </table>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'>Группа С</span></b></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><span
  lang=EN-US><a href="http://futsal.ucoz.ru/_pu/2/97347.jpg"
  title="&quot;Нажмите, для просмотра в полном размере...&quot; t "><span
  lang=RU style='font-size:12.0pt;font-family:"Times New Roman","serif";
  text-decoration:none'><img border=0 width=400 height=299 id="Рисунок 4"
  src="2008.files/image006.jpg" alt="http://futsal.ucoz.ru/_pu/2/s97347.jpg"></span></a></span></p>
  <p class=MsoNormal style='line-height:normal'><span lang=EN-US
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span></p>

  <table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 width="100%"
   style='width:100.0%;border-collapse:collapse'>
   <tr>
    <td style='border:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>Группа </span><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>C</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>1</span></p>

    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>4</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>5</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>м</span></p>

    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>о</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>Украина</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2:2</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>6:2</span></p>
    </td>

    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>5:1</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>4:2</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>17-7</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>10</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>Аргентина</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2:2</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2:1</span></p>
    </td>

    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>4:2</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>5:0</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>13-5</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>10</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>Гватемала</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2:6</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>1:2</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>

    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>1:0</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>10:1</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>14-9</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>6</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>Египет</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>1:5</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2:4</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>0:1</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>6:2</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>9-12</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>Китай</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2:4</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>0:5</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>1:10</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2:6</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>5-25</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>0</span></p>
    </td>
   </tr>
  </table>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Группа </span></b><b><span
  lang=EN-US style='font-size:12.0pt;font-family:"Times New Roman","serif"'>D</span></b></p>

  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><span
  lang=EN-US><a href="http://futsal.ucoz.ru/_pu/2/61069.jpg"
  title="&quot;Нажмите, для просмотра в полном размере...&quot; t "><span
  lang=RU style='font-size:12.0pt;font-family:"Times New Roman","serif";
  text-decoration:none'><img border=0 width=400 height=300 id="Рисунок 3"
  src="2008.files/image007.jpg" alt="http://futsal.ucoz.ru/_pu/2/s61069.jpg"></span></a></span></p>
  <div align=center>
  <table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 width="100%"
   style='width:100.0%;border-collapse:collapse'>
   <tr>
    <td style='border:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Группа D</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>

    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>5</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>м</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>о</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Испания</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3:3</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4:0</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3:0</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3:0</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>13-3</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>10</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Иран</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3:3</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3:2</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4:2</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4:2</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>14-9</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>10</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Чехия</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0:4</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2:3</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4:2</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4:1</span></p>
    </td>

    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>10-10</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>6</span></p>
    </td>
   </tr>
   <tr>

    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Либия</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0:3</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2:4</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2:4</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3:3</span></p>
    </td>

    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>7-14</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
    </td>
   </tr>
   <tr>

    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Уругвай</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0:3</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2:4</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1:4</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3:3</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>

    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>6-14</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
    </td>
   </tr>
  </table>

  </div>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><span lang=EN-US style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'>&nbsp;</span></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><span lang=EN-US><a
  href="http://futsal.ucoz.ru/_pu/2/33248.jpg"
  title="&quot;Нажмите, для просмотра в полном размере...&quot; t "><b><span
  lang=RU style='font-size:12.0pt;font-family:"Times New Roman","serif";
  text-decoration:none'><img border=0 width=400 height=300 id="Рисунок 2"
  src="2008.files/image008.jpg" alt="http://futsal.ucoz.ru/_pu/2/s33248.jpg"></span></b></a></span></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span lang=EN-US style='font-size:
  12.0pt;font-family:"Times New Roman","serif"'>БРАЗИЛИЯ</span></b></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><span lang=EN-US style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'>&nbsp;</span></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span lang=EN-US style='font-size:
  12.0pt;font-family:"Times New Roman","serif"'>Бомбардир:</span></b></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  lang=EN-US style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Пула
  (Россия)-16 мячей</span></b></p>

  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><span
  lang=EN-US><a href="http://futsal.ucoz.ru/_pu/2/33833.jpg"
  title="&quot;Нажмите, для просмотра в полном размере...&quot; t "><b><span
  lang=RU style='font-size:12.0pt;font-family:"Times New Roman","serif";
  text-decoration:none'><img border=0 width=400 height=300 id="Рисунок 1"
  src="2008.files/image009.jpg" alt="http://futsal.ucoz.ru/_pu/2/s33833.jpg"></span></b></a></span></p>
  </td>
 </tr>
</table>

<p class=MsoNormal><span lang=EN-US>&nbsp;</span></p>

</div>
