<div class=Section1>

<p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
normal'><a name="_GoBack"><span lang=EN-US style='font-size:12.0pt;font-family:
"Times New Roman","serif"'>ЧЕМПИОНАТ ЕВРОПЫ 1996 (экспериментальный)</span></a></p>

<table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 width="100%"
 style='width:100.0%'>
 <tr>
  <td style='padding:1.5pt 1.5pt 1.5pt 1.5pt'>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span lang=EN-US style='font-size:
  14.0pt;font-family:"Times New Roman","serif"'>ЧЕМПИОНАТ ЕВРОПЫ 1996</span></b></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span lang=EN-US style='font-size:
  12.0pt;font-family:"Times New Roman","serif"'>ИСПАНИЯ</span></b></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><span style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'><img width=101 height=117
  id="Рисунок 2"
  src="_________%20______%201996%20(_________________).files/image001.gif"
  alt="http://futsal.ucoz.ru/_pu/2/51026.gif"></span></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><span lang=EN-US style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'>&nbsp;</span></p>
  <div align=center>

  <table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 width="100%"
   style='width:100.0%'>
   <tr>
    <td style='padding:3.0pt 3.0pt 3.0pt 3.0pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:14.0pt;font-family:"Times New Roman","serif";color:crimson'>Предварительныйраунд</span></p>
    </td>
   </tr>
   <tr>
    <td style='padding:3.0pt 3.0pt 3.0pt 3.0pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:14.0pt;
    font-family:"Times New Roman","serif";color:blue'>Группа 1</span><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'><br>
    <b>23.10.95</b><br>
    СЛОВАКИЯ-ХОРВАТИЯ 2-5<br>
    ЧЕШСКАЯ РЕСПУБЛИКА-НИДЕРЛАНДЫ 4-7<br>
    АЗЕРБАЙДЖАН-ПОЛЬША 6-4 <br>
    <b>24.10.95</b><br>

    ХОРВАТИЯ-ЧЕШСКАЯ РЕСПУБЛИКА 6-4<br>
    НИДЕРЛАНДЫ-АЗЕРБАЙДЖАН 3-1<br>
    ПОЛЬША-СЛОВАКИЯ 0-0<br>
    <b>25.10.95</b><br>
    СЛОВАКИЯ-ЧЕШСКАЯ РЕСПУБЛИКА 5-3<br>
    ПОЛЬША-НИДЕРЛАНДЫ 1-3<br>

    ХОРВАТИЯ-АЗЕРБАЙДЖАН 6-3<br>
    <b>27.10.95</b><br>
    СЛОВАКИЯ-АЗЕРБАЙДЖАН 2-0<br>
    НИДЕРЛАНДЫ-ХОРВАТИЯ 6-4<br>
    ЧЕШСКАЯ РЕСПУБЛИКА-ПОЛЬША 1-3<br>
    <b>28.10.95</b><br>

    ХОРВАТИЯ-ПОЛЬША 7-4<br>
    ЧЕШСКАЯ РЕСПУБЛИКА-АЗЕРБАЙДЖАН 10-2<br>
    СЛОВАКИЯ-НИДЕРЛАНДЫ 3-3 </span></p>
    <div align=center>
    <table class=MsoNormalTable border=1 cellspacing=1 cellpadding=0 width="50%"
     style='width:50.0%;border:outset blue 1.5pt'>
     <tr>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>М</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Команда</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>И</span></b></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>В</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Н</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>П</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Мячи</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>О</span></b></p>

      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>НИДЕРЛАНДЫ</span></b></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>5</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>21-13</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>13</span></p>
      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>ХОРВАТИЯ </span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>5</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>28-19</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>12</span></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>СЛОВАКИЯ </span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>5</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>12-11</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>8</span></p>
      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>ПОЛЬША </span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>5</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>12-16</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>5</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>ЧЕШСКАЯ
      РЕСПУБЛИКА </span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>5</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>22-23</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>

      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>6</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>АЗЕРБАЙДЖАН
      </span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>5</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>12-25</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
     </tr>
    </table>
    </div>
    </td>

   </tr>
   <tr>
    <td style='padding:3.0pt 3.0pt 3.0pt 3.0pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:14.0pt;
    font-family:"Times New Roman","serif";color:blue'>Группа 2</span><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'><br>
    <b>23.10.95</b><br>
    ИТАЛИЯ-ГРУЗИЯ 3-1<br>
    ПОРТУГАЛИЯ-ВЕНГРИЯ 1-3<br>

    ЮГОСЛАВИЯ-УКРАИНА 5-9<br>
    <b>24.10.95</b><br>
    ВЕНГРИЯ-ЮГОСЛАВИЯ 1-8<br>
    ГРУЗИЯ-ПОРТУГАЛИЯ 4-6<br>
    УКРАИНА-ИТАЛИЯ 4-7<br>
    <b>25.10.95</b><br>

    ВЕНГРИЯ-ИТАЛИЯ 4-6<br>
    ПОРТУГАЛИЯ-ЮГОСЛАВИЯ 4-7<br>
    ГРУЗИЯ-УКРАИНА 10-7<br>
    <b>27.10.95</b><br>
    ПОРТУГАЛИЯ-ИТАЛИЯ 1-3<br>
    ЮГОСЛАВИЯ-ГРУЗИЯ 7-3<br>

    УКРАИНА-ВЕНГРИЯ 8-3<br>
    <b>28.10.95</b><br>
    ВЕНГРИЯ-ГРУЗИЯ 14-3<br>
    ПОРТУГАЛИЯ-УКРАИНА 4-8<br>
    ЮГОСЛАВИЯ-ИТАЛИЯ 3-4</span></p>
    <div align=center>

    <table class=MsoNormalTable border=1 cellspacing=1 cellpadding=0 width="50%"
     style='width:50.0%;border:outset blue 1.5pt'>
     <tr>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>М</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Команда</span></b></p>
      </td>

      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>И</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>В</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Н</span></b></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>П</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Мячи</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>О</span></b></p>
      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>ИТАЛИЯ </span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>5</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>5</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>23-13</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>15</span></p>
      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>УКРАИНА</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>5</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>36-29</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>9</span></p>

      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>ЮГОСЛАВИЯ </span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>5</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>30-21</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>9</span></p>
      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>ВЕНГРИЯ </span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>5</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>25-26</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>6</span></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>5</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>ПОРТУГАЛИЯ
      </span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>5</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>16-25</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>6</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>ГРУЗИЯ</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>5</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>22-37</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
     </tr>
    </table>
    </div>

    </td>
   </tr>
   <tr>
    <td style='padding:3.0pt 3.0pt 3.0pt 3.0pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:14.0pt;
    font-family:"Times New Roman","serif";color:blue'>Группа 3</span><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'><br>
    <b>23.10.95</b><br>
    БЕЛЬГИЯ-РОССИЯ 5-6<br>

    БЕЛОРУССИЯ - СЛОВЕНИЯ 2-3<br>
    <b>24.10.95</b><br>
    МОЛДОВА-БЕЛЬГИЯ 1-14<br>
    РОССИЯ - БЕЛОРУССИЯ 8-1 <br>
    <b>25.10.95</b><br>
    БЕЛЬГИЯ-СЛОВЕНИЯ 5-2<br>

    РОССИЯ-МОЛДОВА 31-0<br>
    <b>27.10.95</b><br>
    БЕЛЬГИЯ - БЕЛОРУССИЯ 6-2<br>
    СЛОВЕНИЯ-МОЛДОВА 12-2<br>
    <b>28.10.95</b><br>
    БЕЛОРУССИЯ - МОЛДОВА 14-1<br>

    РОССИЯ-СЛОВЕНИЯ 7-3</span></p>
    <div align=center>
    <table class=MsoNormalTable border=1 cellspacing=1 cellpadding=0 width="50%"
     style='width:50.0%;border:outset blue 1.5pt'>
     <tr>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>М</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Команда</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>И</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>В</span></b></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Н</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>П</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Мячи</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>О</span></b></p>
      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>РОССИЯ </span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>52-9</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>12</span></p>

      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>БЕЛЬГИЯ</span></b></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>30-11</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>9</span></p>
      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>СЛОВЕНИЯ </span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>20-16</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>6</span></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>БЕЛОРУССИЯ
      </span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>19-18</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>5</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>МОЛДОВА </span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4-71</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>
     </tr>
    </table>
    </div>

    </td>
   </tr>
   <tr>
    <td style='padding:3.0pt 3.0pt 3.0pt 3.0pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:14.0pt;
    font-family:"Times New Roman","serif";color:blue'>Группа А</span><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'><br>
    08.01.96 ИСПАНИЯ-БЕЛЬГИЯ 2-1 (1-0) <br>
    09.01.96 НИДЕРЛАНДЫ-БЕЛЬГИЯ 0-2 (0-1) <br>

    10.01.96 ИСПАНИЯ-НИДЕРЛАНДЫ 2-2 (2-0) </span></p>
    <div align=center>
    <table class=MsoNormalTable border=1 cellspacing=1 cellpadding=0 width="50%"
     style='width:50.0%;border:outset blue 1.5pt'>
     <tr>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>М</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Команда</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>И</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>В</span></b></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Н</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>П</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Мячи</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>О</span></b></p>
      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>ИСПАНИЯ</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4-3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4</span></p>

      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>БЕЛЬГИЯ</span></b></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3-2</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>НИДЕРЛАНДЫ</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2-4</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
     </tr>

    </table>
    </div>
    </td>
   </tr>
   <tr>
    <td style='padding:3.0pt 3.0pt 3.0pt 3.0pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:14.0pt;
    font-family:"Times New Roman","serif";color:blue'>Группа В</span><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'><br>
    08.01.96 РОССИЯ-УКРАИНА 3-2 (2-0) <br>

    09.01.96 ИТАЛИЯ-УКРАИНА 6-3 (2-1) <br>
    10.01.96 РОССИЯ-ИТАЛИЯ 5-1 (4-0) </span></p>
    <div align=center>
    <table class=MsoNormalTable border=1 cellspacing=1 cellpadding=0 width="50%"
     style='width:50.0%;border:outset blue 1.5pt'>
     <tr>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>М</span></b></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Команда</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>И</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>В</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Н</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>П</span></b></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Мячи</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>О</span></b></p>
      </td>
     </tr>

     <tr>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>РОССИЯ</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>8-3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>6</span></p>
      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><b><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>ИТАЛИЯ</span></b></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>7-8</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
     </tr>
     <tr>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>УКРАИНА</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>

      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>

      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>5-9</span></p>
      </td>
      <td style='border:inset blue 1.0pt;padding:.75pt .75pt .75pt .75pt'>
      <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
      .0001pt;text-align:center;line-height:normal'><span lang=EN-US
      style='font-size:12.0pt;font-family:"Times New Roman","serif"'>0</span></p>

      </td>
     </tr>
    </table>
    </div>
    </td>
   </tr>
   <tr>
    <td style='padding:3.0pt 3.0pt 3.0pt 3.0pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:14.0pt;
    font-family:"Times New Roman","serif";color:blue'>Полуфиналы</span><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'><br>

    <b>12.1.96 РОССИЯ-БЕЛЬГИЯ 6-2 (3-2) <br>
    12.01.96 ИСПАНИЯ-ИТАЛИЯ 4-1 (2-0) </b></span></p>
    </td>
   </tr>
   <tr>
    <td style='padding:3.0pt 3.0pt 3.0pt 3.0pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:14.0pt;
    font-family:"Times New Roman","serif";color:blue'>Матч за 3-е место</span><span
    style='font-size:12.0pt;font-family:"Times New Roman","serif"'><br>

    <b>13.01.96 БЕЛЬГИЯ-ИТАЛИЯ (1-1; 2-2) 3-2 * <br>
    </b>* в дополнительное время </span></p>
    </td>
   </tr>
   <tr>
    <td style='padding:3.0pt 3.0pt 3.0pt 3.0pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US
    style='font-size:14.0pt;font-family:"Times New Roman","serif";color:blue'>Финал</span><span
    lang=EN-US style='font-size:12.0pt;font-family:"Times New Roman","serif"'><br>

    <b>14.01.96 ИСПАНИЯ-РОССИЯ 5-3 (2-1)</b></span></p>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US><a
    href="http://futsal.ucoz.ru/_pu/2/38560131.jpg"
    title="&quot;Нажмите, для просмотра в полном размере...&quot; t "><b><span
    lang=RU style='font-size:12.0pt;font-family:"Times New Roman","serif";
    color:blue;text-decoration:none'><img border=0 width=400 height=266
    id="Рисунок 1"
    src="_________%20______%201996%20(_________________).files/image002.jpg"
    alt="http://futsal.ucoz.ru/_pu/2/s38560131.jpg"></span></b></a></span><b><span
    lang=EN-US style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span></b></p>
    </td>
   </tr>
  </table>
  </div>
  </td>
 </tr>

</table>

<p class=MsoNormal><span lang=EN-US>&nbsp;</span></p>
