<div class=Section1>

<p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
normal'><a name="_GoBack"><span lang=EN-US style='font-size:12.0pt;font-family:
"Times New Roman","serif"'>ЧЕМПИОНАТ ЕВРОПЫ 2005</span></a></p>

<table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 width="100%"
 style='width:100.0%'>
 <tr>
  <td style='padding:1.5pt 1.5pt 1.5pt 1.5pt'>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span lang=EN-US style='font-size:
  14.0pt;font-family:"Times New Roman","serif"'>ЧЕМПИОНАТ ЕВРОПЫ 2005</span></b></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><span lang=EN-US style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'>&nbsp;</span></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span lang=EN-US style='font-size:
  12.0pt;font-family:"Times New Roman","serif"'>ЧЕХИЯ</span></b></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><span lang=EN-US style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'>&nbsp;</span></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><span style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'><img width=140 height=210
  id="Рисунок 1" src="http://futsal.ucoz.ru/_pu/2/31231.jpg"
  alt="http://futsal.ucoz.ru/_pu/2/31231.jpg"></span></p>

  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'>ФИНАЛ</span></b></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'>РОССИЯ-ИСПАНИЯ
  </span></b><span lang=EN-US><a
  href="http://ru.uefa.com/competitions/futsal/history/season=2005/round=1905/match=80099/index.html"
  target=null><b><span lang=RU style='font-size:12.0pt;font-family:"Times New Roman","serif"'>1:2</span></b></a></span></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'>МАТЧ ЗА 3
  МЕСТО:</span></b></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'>ИТАЛИЯ-УКРАИНА
  </span></b><span lang=EN-US><a
  href="http://ru.uefa.com/competitions/futsal/history/season=2005/round=1904/match=80098/index.html"
  target=null><b><span lang=RU style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3:1</span></b></a></span></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'>ПОЛУФИНАЛЫ:</span></b></p>

  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'>РОССИЯ-ИТАЛИЯ </span></b><span
  lang=EN-US><a
  href="http://ru.uefa.com/competitions/futsal/history/season=2005/round=1903/match=80097/index.html"
  target=null><b><span lang=RU style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4:2</span></b></a></span></p>
  <p class=MsoNormal align=center style='text-align:center;line-height:normal'><b><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'>ИСПАНИЯ-УКРАИНА
  </span></b><span lang=EN-US><a
  href="http://ru.uefa.com/competitions/futsal/history/season=2005/round=1903/match=80096/index.html"
  target=null><b><span lang=RU style='font-size:12.0pt;font-family:"Times New Roman","serif"'>5:0</span></b></a></span></p>
  <p class=MsoNormal align=center style='margin-bottom:12.0pt;text-align:center;
  line-height:normal'><b><span style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Группа
  А</span></b></p>
  <table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 width="100%"
   style='width:100.0%;border-collapse:collapse'>
   <tr>
    <td style='border:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>м</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>группа А</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>1</span></p>

    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>4</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>м</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>о</span></p>

    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>Украина</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2:1</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>4:1</span></p>
    </td>

    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>1:2</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>6</span></p>
    </td>
   </tr>

   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>Россия</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>1:2</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>5:3</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>4:1</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>6</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>Голландия</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>1:4</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3:5</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>4:3</span></p>
    </td>

    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>4</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>Чехия</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2:1</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>1:4</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3:4</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
   </tr>
  </table>
  <p class=MsoNormal style='margin-bottom:12.0pt;line-height:normal'><span
  style='font-size:12.0pt;font-family:"Times New Roman","serif"'>&nbsp;</span></p>
  <p class=MsoNormal align=center style='margin-bottom:12.0pt;text-align:center;
  line-height:normal'><b><span style='font-size:12.0pt;font-family:"Times New Roman","serif"'>Группа
  В</span></b></p>
  <div align=center>
  <table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 width="100%"
   style='width:100.0%;border-collapse:collapse'>

   <tr>
    <td style='border:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>м</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>группа В</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>

    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>4</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>м</span></p>
    </td>
    <td style='border:solid black 1.0pt;border-left:none;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>о</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>1</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>Италия</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3:1</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US><a
    href="http://ru.uefa.com/competitions/futsal/history/season=2005/round=1902/match=79676/index.html"
    target=null><span lang=RU style='font-size:12.0pt;font-family:"Times New Roman","serif"'>8:3</span></a></span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>5:0</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>9</span></p>
    </td>

   </tr>
   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>2</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>Испания</span></p>
    </td>

    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>1:3</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3:1</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US><a
    href="http://ru.uefa.com/competitions/futsal/history/season=2005/round=1902/match=79677/index.html"
    target=null><span lang=RU style='font-size:12.0pt;font-family:"Times New Roman","serif"'>4:2</span></a></span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>6</span></p>
    </td>
   </tr>
   <tr>

    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>Португалия</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US><a
    href="http://ru.uefa.com/competitions/futsal/history/season=2005/round=1902/match=79676/index.html"
    target=null><span lang=RU style='font-size:12.0pt;font-family:"Times New Roman","serif"'>3:8</span></a></span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>1:3</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>5:3</span></p>
    </td>

    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3</span></p>
    </td>
   </tr>
   <tr>
    <td style='border:solid black 1.0pt;border-top:none;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>4</span></p>

    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>Венгрия</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>0:5</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span lang=EN-US><a
    href="http://ru.uefa.com/competitions/futsal/history/season=2005/round=1902/match=79677/index.html"
    target=null><span lang=RU style='font-size:12.0pt;font-family:"Times New Roman","serif"'>2:4</span></a></span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>
    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>3:5</span></p>
    </td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'></td>
    <td style='border-top:none;border-left:none;border-bottom:solid black 1.0pt;
    border-right:solid black 1.0pt;padding:.75pt .75pt .75pt .75pt'>

    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
    .0001pt;text-align:center;line-height:normal'><span style='font-size:12.0pt;
    font-family:"Times New Roman","serif"'>0</span></p>
    </td>
   </tr>
  </table>
  </div>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><span style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'><br/>
  Примечания.</span></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><span lang=EN-US style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'>&nbsp;</span></p>

  <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
  normal'><span lang=EN-US style='font-size:12.0pt;font-family:"Times New Roman","serif"'>FINAL
  TOURNAMENT<br/>
  <br/>
  played between 14 February - 20 February 2005 in Czech Republic<br/>
  <br/>
  Group A<br/>
  Feb 14: Czech Republic&nbsp; 2-1&nbsp; Ukraine<br/>

  [M.Mareљ 18, Rajnoch 34; Kudlay 12]<br/>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  Russia&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 5-3&nbsp;
  Netherlands<br/>
  [Markin 16, 38, Hulshorst 17own, Shayakhmetev 38, 39; Hulshorst 24,<br/>
  &nbsp; Merlino 35, Tjaden 39]<br/>

  Feb 15: Czech Republic&nbsp; 1-4&nbsp; Russia<br/>
  [Љluka 16; Ivanov 6, Shayakhmetev 19, Maevski 25, Abyshev 36]<br/>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  Ukraine&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 4-1&nbsp; Netherlands<br/>

  [Pylypiv 12, Sytin 18, 38, Koridze 40; Thies 23]<br/>
  Feb 17: Netherlands&nbsp;&nbsp;&nbsp;&nbsp; 4-3&nbsp; Czech Republic<br/>
  [Merlino 3, Makhoukhi 8, Љluka 10own, Hulshorst 14; Dlouhэ 9,<br/>
  &nbsp; M.Mareљ 15, Rajnoch 24]<br/>

  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  Ukraine&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2-1&nbsp; Russia<br/>
  [Sytin 9, Markin 23own; Khamadiyev 37]<br/>
  <br/>
  1. UKRAINE&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3&nbsp; 2&nbsp;

  0&nbsp; 1&nbsp;&nbsp; 7- 4&nbsp; 6<br/>
  2. RUSSIA&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3&nbsp;
  2&nbsp; 0&nbsp; 1&nbsp; 10- 6&nbsp; 6<br/>

  3. Netherlands&nbsp;&nbsp;&nbsp;&nbsp; 3&nbsp; 1&nbsp; 0&nbsp; 2&nbsp;&nbsp;
  8-12&nbsp; 3<br/>
  4. Czech Republic&nbsp; 3&nbsp; 1&nbsp; 0&nbsp; 2&nbsp;&nbsp; 6- 9&nbsp; 3<br/>

  <br/>
  Group B<br/>
  Feb 14: Italy&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  8-3&nbsp; Portugal<br/>
  [Jubanski 3, Fabiano 17, 22, Grana 18, 19, 35, Bertoni 25,<br/>
  &nbsp; Montovanelli 31; Gonзalo Бlves 13, Joel Queirуs 29, Andrи Lima 36]<br/>

  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  Hungary&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2-4&nbsp; Spain<br/>
  [Simon 28, Frank 33; Jordi Torras 27, Javi Rodrнguez 35, 36, Daniel 38]<br/>
  Feb 15: Italy&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  5-0&nbsp; Hungary<br/>

  [Foglia 1, Grana 12, 22, Scala 17, 19]<br/>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  Portugal&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1-3&nbsp; Spain<br/>
  [Marcelinho 35; Javi Rodrнguez 7, Daniel 11, Kike 39]<br/>
  Feb 17: Spain&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

  1-3&nbsp; Italy<br/>
  [Jordi Torras 26; Vinicius 4, Scala 22, Bertoni 29]<br/>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  Portugal&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 5-3&nbsp; Hungary<br/>

  [Gonзalo Бlves 25, 26, 39, Andrи Lima 38, Joel Queirуs 38;<br/>
  &nbsp; Lуdi 17, 26, S.Tуth 35]<br/>
  <br/>
  1. ITALY&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3&nbsp;
  3&nbsp; 0&nbsp; 0&nbsp; 16- 4&nbsp; 9<br/>

  2. SPAIN&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3&nbsp;
  2&nbsp; 0&nbsp; 1&nbsp;&nbsp; 8- 6&nbsp; 6<br/>
  3. Portugal&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3&nbsp; 1&nbsp; 0&nbsp;

  2&nbsp;&nbsp; 9-14&nbsp; 3<br/>
  4. Hungary&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3&nbsp; 0&nbsp;
  0&nbsp; 3&nbsp;&nbsp; 5-14&nbsp; 0<br/>

  <br/>
  <br/>
  Semifinals [18 Feb]<br/>
  Ukraine 0-5 Spain<br/>
  [Andreu 9, 37, Daniel 30, Fran Serrejуn 31, 34]<br/>
  Italy&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  2-4 Russia<br/>

  [Zanetti 3, 24; Shayakhmetev 14, 32, Ivanov 36, Levin 37]<br/>
  <br/>
  Third Place [20 Feb]<br/>
  Ukraine&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  1-3 Italy<br/>
  [Sytin 9; Grana 6, Fabiano 16, Zanetti 21]<br/>

  <br/>
  Final [20 Feb]<br/>
  Spain&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  2-1 Russia<br/>
  [Andreu 9, Cogorro 21; Douchkevitch 31]<br/>
  <br/>
  Goalscorers:<br/>

  6 - Fernando Grana (Italy);<br/>
  5 - Vladislav Shayakhmetev (Russia);<br/>
  4 - Gonзalo Бlves (Portugal), Serhiy Sytin (Ukraine);<br/>
  3 - Assad Fabiano, Carlos Scala, Sandro Reno Zanetti (Italy),<br/>
  &nbsp;&nbsp;&nbsp; Andreu, Daniel, Javi Rodrнguez (Spain);<br/>
  2 - Michal Mareљ, Daniel Rajnoch (Czech Republic), Tamбs Lуdi (Hungary),<br/>

  &nbsp;&nbsp;&nbsp; Edgar Bertoni (Italy), Dick Hulshorst, Antoine Merlino
  (Netherlands),<br/>
  &nbsp;&nbsp;&nbsp; Andrй Lima, Joel Queirуs (Portugal), Sergei Ivanov,<br/>
  &nbsp;&nbsp;&nbsp; Mikhail Markin (Russia), Fran Serrejуn, Jordi Torras
  (Spain);<br/>
  1 - Martнn Dlouhэ, Tomбљ Љluka (Czech Republic), Tamбs Frank,<br/>
  &nbsp;&nbsp;&nbsp; Balбzs Simon, Szabolcs Tуth (Hungary), Adriano Foglia,<br/>

  &nbsp;&nbsp;&nbsp; Jocimar Jubanski, Carlos Montovanelli, Bacaro Vinicius
  (Italy),<br/>
  &nbsp;&nbsp;&nbsp; Samir Makhoukhi, Maximiliaan Tjaden, Kees Thies
  (Netherlands),<br/>
  &nbsp;&nbsp;&nbsp; Marcelinho (Portugal), Denis Abyshev, Damir Khamadiyev,<br/>
  &nbsp;&nbsp;&nbsp; Aleksandr Levin, Konstantin Maevski, Konstantin
  Douchkevitch (Russia),<br/>
  &nbsp;&nbsp;&nbsp; Kike, Alberto Cogorro (Spain), Serhiy Koridze, Olexiy
  Kudlay,<br/>

  &nbsp;&nbsp;&nbsp; Fedir Pylypiv (Ukraine).<br/>
  own goals<br/>
  1 - Tomбљ Љluka (Czech Republic), Dick Hulshorst (Netherlands),<br/>
  &nbsp;&nbsp;&nbsp; Mikhail Markin (Russia).<br/>
  <br/>
  Squad Lists (Final Round)<br/>

  <br/>
  Czech Republic<br/>
  Coach: Michal Strнz.<br/>
  1-Petr Krayzel, 2-Vit Blazej, 3-Daniel Rajnoch, 4-David Levcнk,<br/>
  5-Tomбљ Љluka, 6-Roman Mareљ, 7-Martнn Dlouhэ, 8-Radek Polasek,<br/>
  9-David Fric, 10-Josef Havel, 11-Michal Mareљ, 12-Jan Klнma,<br/>

  13-Zdenek Slбm, 14-Jaroslav Kamenickэ.<br/>
  <br/>
  Hungary<br/>
  Coach: Mihбly Kozma.<br/>
  1-Zoltбn Balбzs, 2-Szabolcs Tуth, 3-Gбbor Somogyi, 4-Balбzs Simon,<br/>
  5-Tamбs Szimcsбk, 6-Gбbor Csernai, 7-Tamбs Lуdi, 8-Pбl Baranyai,<br/>

  9-Zoltan Szabo, 10-Tamбs Frank, 11-Jбnos Madarбsz, 12-Бkos Mбrkus,<br/>
  13-Zsolt Gyurcsбnyi, 14-Miklуs Tуth.<br/>
  <br/>
  Italy<br/>
  Coach: Alessandro Nuccorini.<br/>
  1-Alexander Feller, 2-Fernando Grana, 3-Anderson Vasconcelos,<br/>

  4-Carlos Montovanelli, 5-Jocimar Jubanski, 6-Edgar Bertoni,<br/>
  7-Bacaro Vinicius, 8-Carlos Scala, 9-Assad Fabiano,<br/>
  10-Adriano Foglia, 11-Carlos Morgado, 12-Goncalves Farina,<br/>
  13-Sandro Reno Zanetti, 14-Tadeu Sartori.<br/>
  <br/>
  Netherlands<br/>

  Coach: Vic Hermans.<br/>
  1-Patrick Thomassen, 2-Antoine Merlino, 3-Dick Hulshorst,<br/>
  4-Zaid El Morabiti, 5-Kees Thies, 6-Samir Makhoukhi,<br/>
  7-Maximiliaan Tjaden, 8-Calvin Blankendal, 9-Edwin Grьnholz,<br/>
  10-Ferdy Kaleveld, 11-Joey Ngarigota, 12-Remco Bos,<br/>
  13-Frank Brands, 14-Abdellah Idlaasri.<br/>

  <br/>
  Portugal<br/>
  Coach: Orlando Duarte.<br/>
  1-Joгo Benedito, 2-Luis Estrela, 3-Leo, 4-Marcelinho,<br/>
  5-Ivan, 6-Joel Queirуs, 7-Andrй Lima, 8-Miguel Almeida<br/>
  9-Gonзalo Alves, 10-Josй Maria, 11-Israel Alves,<br/>

  12-Sandro Barradas, 13-Zйzito, 14-Sнlvio.<br/>
  <br/>
  Russia<br/>
  Coach: Oleg Ivanov.<br/>
  1-Pavel Stepanov, 2-Vladislav Shayakhmetev, 3-Aleksandr Foukine,<br/>
  4-Mikhail Markin, 5-Konstantin Maevski, 6-Sergei Malyshev,<br/>

  7-Damir Khamadiyev, 8-Konstantin Douchkevitch, 9-Sergei Ivanov,<br/>
  10-Denis Abyshev, 11-Maxim Gorbounov, 12-Sergei Zouev,<br/>
  13-Aleksandr Levin, 14-Iouri Korol.<br/>
  <br/>
  Spain<br/>
  Coach: Javier Lozano.<br/>

  1-Luis Amado, 2-Julio, 3-Jordi Torras, 4-Fran Serrejуn,<br/>
  5-Orol, 6-Marcelo, 7-Javi Rodrнguez, 8-Kike, 9-Andreu,<br/>
  10-Javi Limones, 11-Alberto Cogorro, 12-Rafa,<br/>
  13-Francisco Antolin, 14 Daniel.<br/>
  <br/>
  Ukraine<br/>

  Coach: Gennadiy Lysenchuk.<br/>
  1-Olexiy Popov, 2-Mykhaylo Romanov, 3-Vitaliy Nesteruk,<br/>
  4-Serhiy Koridze, 5-Oleh Shaytanov, 6-Vitaliy Brunko,<br/>
  7-Yevgen Rogachov, 8-Olexiy Kudlay, 9-Valeriy Zamyatin,<br/>
  10-Serhiy Sytin, 11-Fedir Pylypiv, 12-Vasyl Sukhomlinov,<br/>
  13-Artem Kovalyov, 14-Kostyantyn Vlasenko.<br/>

  <br/>
  Referees<br/>
  <br/>
  Anton Averianov (Russia)<br/>
  Silvo Borosak (Slovenia)<br/>
  Massimo Cumbo (Italy)<br/>
  Antonio Jose Fernandes Cardoso (Portugal)<br/>

  Jyrki Filppu (Finland)<br/>
  Pedro Бngel Galбn Nieto (Spain)<br/>
  Christian Hauben (Belgium)<br/>
  Zbigniew Kosmala (Poland)<br/>
  Radek Lobo (Czech Republic)<br/>
  Ivan Novak (Croatia)<br/>

  Kбroly Tцrцk (Hungaria)<br/>
  Antonius van Eekelen (Netherlands)</span></p>
  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><span lang=EN-US style='font-size:12.0pt;
  font-family:"Times New Roman","serif"'>&nbsp;</span></p>
  <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
  normal'><span lang=EN-US style='font-size:12.0pt;font-family:"Times New Roman","serif"'>QUALIFYING
  TOURNAMENT<br/>
  <br/>
  Preliminary Round<br/>
  <br/>

  played between 6 January - 11 January 2004<br/>
  <br/>
  Group A (in Varna, Bulgaria)<br/>
  Jan&nbsp; 8: Bulgaria&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 0-12 Romania<br/>
  [Lupu 1, 10, Csoma 3, 10, 32, Matei 24, 40, Moraru 31, Vintila 33,<br/>

  &nbsp; Stanciu 35, Kacso 36, Molomfalean 39]<br/>
  Jan&nbsp; 9: Romania&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3-3
  Armenia<br/>
  [Matei 18, Stanciu 25, Kacso 35; Nazaryan 3, Abazyan 4, Avetisyan 20]<br/>
  Jan&nbsp; 9: Bulgaria&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 5-6
  Kazakhstan<br/>

  [Dochev 4, 40, Nestorov 26, 30, Stantshev 30; Karimov 2, 2,<br/>
  &nbsp; Batov 18, 40, Kenetaev 36, Bondarev 39]<br/>
  Jan 10: Armenia&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2-2
  Kazakhstan<br/>
  [Nazaryan 14, Petrosyan 33; Yussupov 4, Ershanov 18]<br/>
  Jan 11: Kazakhstan&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1-5 Romania<br/>

  [Karimov 16; Matei 9, 26, Stanciu 18, Lupu 32, 39]<br/>
  Jan 11: Armenia&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 4-2 Bulgaria<br/>
  [Nazaryan 3, Niazyan 11, Avetisyan 35, Gyulambaryan 39; Kalchev 2, 33]<br/>
  <br/>
  1.ROMANIA&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3&nbsp; 2&nbsp;

  1&nbsp; 0&nbsp; 20- 4&nbsp; 7<br/>
  2.Armenia&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3&nbsp; 1&nbsp;
  2&nbsp; 0&nbsp;&nbsp; 9- 7&nbsp; 5<br/>

  3.Kazakhstan&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3&nbsp; 1&nbsp; 1&nbsp;
  1&nbsp;&nbsp; 9-12&nbsp; 4<br/>
  4.Bulgaria&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3&nbsp; 0&nbsp; 0&nbsp;

  3&nbsp;&nbsp; 7-22&nbsp; 0<br/>
  <br/>
  Group B (in Vlorл, Albania)<br/>
  Jan&nbsp; 6: Albania&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

  8-6&nbsp; England<br/>
  [Nenaj 9, Wood 10own, Mullaj 14, 36, 37, Dama 24, 39, Spahiu 40,<br/>
  &nbsp; Axcell 10, 19, 38, Sykes 13, Berry 26, Wood 29]<br/>
  Jan&nbsp; 7: England&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

  4-8&nbsp; Cyprus<br/>
  [Walker 2, 35, Sykes 22, Wood 39; Lambrou 1, 17, Poliviou 2, 29,<br/>
  &nbsp; Aggelides 3, 34, Chrysostomou 15, Agathocleous 20]<br/>
  Jan&nbsp; 8: Cyprus&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

  1-1&nbsp; Albania<br/>
  [Poliviou 37; Mullaj 30]<br/>
  <br/>
  1.CYPRUS&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2&nbsp;
  1&nbsp; 1&nbsp; 0&nbsp;&nbsp; 9- 5&nbsp; 4<br/>

  2.Albania&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2&nbsp; 1&nbsp;
  1&nbsp; 0&nbsp;&nbsp; 9- 7&nbsp; 4<br/>
  3.England&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2&nbsp; 0&nbsp;

  0&nbsp; 2&nbsp; 10-16&nbsp; 0<br/>
  <br/>
  <br/>
  <br/>
  Qualification Round<br/>

  <br/>
  played between 27 January - 1 February 2004<br/>
  <br/>
  Group 1 (in Hasselt, Belgium)<br/>
  Jan 27: Netherlands&nbsp;&nbsp;&nbsp; 11-1&nbsp; Israel<br/>

  [Makhoukhi 7, Merlino 8, 18, Grunholz 13, 26, 26, 27, 38, Idlaasri 22,<br/>
  &nbsp; Letemahulu 23, Ngarigota 36; Kalif 27]<br/>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  Belgium&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2-0&nbsp; France<br/>
  [Vergauwen 25, Bachar 26]<br/>

  Jan 28: Netherlands&nbsp;&nbsp;&nbsp; 10-2&nbsp; France<br/>
  [Grunholz 1, 12, 27, 29, 37, Makhoukhi 11, 12, 35, Ngarigota 24, Van Veen 39;<br/>
  &nbsp; Markovic 28pen, Da Cruz 28]<br/>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  Israel&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 0-1&nbsp;

  Belgium<br/>
  [El Haoual 25]<br/>
  Jan 30: France&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  3-2&nbsp; Israel<br/>
  [Basson 23, Da Cruz 28, Markovic 38; Ben Tura 25, 31]<br/>

  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  Belgium&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 0-3&nbsp; Netherlands<br/>
  [Idlaasri 21, Maduro 27, Makhoukhi 39]<br/>
  <br/>
  1.NETHERLANDS&nbsp;&nbsp;&nbsp;&nbsp; 3&nbsp; 3&nbsp; 0&nbsp; 0&nbsp; 24-
  3&nbsp; 9<br/>

  2.Belgium&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3&nbsp; 2&nbsp;
  0&nbsp; 1&nbsp;&nbsp; 3- 3&nbsp; 6<br/>
  3.France&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3&nbsp;

  1&nbsp; 0&nbsp; 2&nbsp;&nbsp; 5-14&nbsp; 3<br/>
  4.Israel&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3&nbsp;
  0&nbsp; 0&nbsp; 3&nbsp;&nbsp; 3-15&nbsp; 0<br/>

  <br/>
  Group 2 (in Trnava, Slovakia)<br/>
  Jan 28: Ukraine&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 6-2&nbsp;
  Slovakia<br/>
  [Pylypiv 16, Koridze 16, Moskvychov 18, 28, Sytin 23, 27; Jalakљa 19, 21]<br/>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

  Belarus&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 4-1&nbsp; Romania<br/>
  [Kouznetsov 20, Levus 23, Ivaniutsin 25, Lushkouski 25; Stanciu 38]<br/>
  Jan 29: Ukraine&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 8-2&nbsp;
  Romania<br/>

  [Koridze 7, 18, 27, Pylypiv 15, 23, Melnikov 17, Kosenko 25, Sytin 37;<br/>
  &nbsp; Stanciu 16, Matei 28]<br/>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  Slovakia&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3-3&nbsp; Belarus<br/>
  [Pavlovic 10, Kunka 14, Cambal 40; Kadakov 9, Lushkouski 20, Chernik 33]<br/>

  Jan 31: Belarus&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1-4&nbsp;
  Ukraine<br/>
  [Ivaniutsin 27; Koridze 2, Mansurov 26, Moskvychov 29, Kosenko 30]<br/>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  Romania&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1-7&nbsp; Slovakia<br/>

  [Lupu 38; Berky 2, 9, Varady 6, Pavlovic 8, 32, Cambal 12, Kaљickэ 27]<br/>
  <br/>
  1.UKRAINE&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3&nbsp; 3&nbsp;
  0&nbsp; 0&nbsp; 18- 5&nbsp; 9<br/>

  2.Slovakia&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3&nbsp; 1&nbsp; 1&nbsp;
  1&nbsp; 12-10&nbsp; 4<br/>
  3.Belarus&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3&nbsp; 1&nbsp;

  1&nbsp; 1&nbsp;&nbsp; 8- 8&nbsp; 4<br/>
  4.Romania&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3&nbsp; 0&nbsp;
  0&nbsp; 3&nbsp;&nbsp; 4-19&nbsp; 0<br/>

  <br/>
  Group 3 (in Andorra La Vella, Andorra)<br/>
  Jan 27: Portugal&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 6-1&nbsp; Moldova<br/>
  [Andrй Lima 6, Israel 20, Joгo Marзal 20, Gonзalo Бlves 26, Ivan 33,<br/>
  &nbsp; Majу 35; Todorov 15]<br/>

  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Andorra&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  4-2&nbsp; Cyprus<br/>
  [Blazquez Cerdeira 5, Sola Peralba 21, 40, Nunez Romero 23;<br/>
  &nbsp; Andreou 30, Poliviou 34]<br/>
  Jan 28: Portugal&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 8-0&nbsp; Cyprus<br/>

  [Ivan 4, Andrй Lima 5, Majу 19, 20, 21, Leo 20, Zйzito 35, Eduardo Fernandes
  35]<br/>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  Moldova&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 11-3&nbsp; Andorra<br/>
  [Zabolotnii 4, 37, Todorov 6, 14, 26, 34, Arlet 10, 18, Tacot 15,<br/>
  &nbsp; Romaniuc 17, Druta 31; Llort Samso 10, 40, Ramнrez 35]<br/>

  Jan 30: Cyprus&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  1-2&nbsp; Moldova<br/>
  [Agathocleous 21; Romaniuc 10, Arlet 22]<br/>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  Andorra&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 0-8&nbsp; Portugal<br/>

  [Majу 11, 19, 32, Arnaldo 18, 18, 30, Eduardo Fernandes 24, Andrй Lima 38]<br/>
  <br/>
  1.PORTUGAL&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3&nbsp; 3&nbsp; 0&nbsp;
  0&nbsp; 22- 1&nbsp; 9<br/>

  2.Moldova&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3&nbsp; 2&nbsp;
  0&nbsp; 1&nbsp; 14-10&nbsp; 6<br/>
  3.Andorra&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3&nbsp; 1&nbsp;

  0&nbsp; 2&nbsp;&nbsp; 7-21&nbsp; 3<br/>
  4.Cyprus&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3&nbsp;
  0&nbsp; 0&nbsp; 3&nbsp;&nbsp; 3-14&nbsp; 0<br/>

  <br/>
  Group 4 (in Las Rozas, Spain)<br/>
  Jan 29: Spain&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  13-0&nbsp; Finland<br/>
  [Serrejуn 1, Cogorro 6, 7, 9, Limones 13, Jordi Torras 28, 32, 34, 36,<br/>
  &nbsp; Rodrнguez 29, 31, Julio 31, Andreu 38]<br/>

  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  Slovenia&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 7-3&nbsp; Lithuania<br/>
  [Dzafic 3, Simic 8, Melink 17, 25, Kurtic 32, Simeunovic 36, Zorc 37;<br/>
  Bakus 29, Rudzionis 35, Rimkevicius 38]<br/>
  Jan 31: Finland&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1-5&nbsp;

  Slovenia<br/>
  [Huusko 35; Љnofl 4, Dzafic 19, Drobnic 26, Kurtic 33, Ibrisimovic 37]<br/>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  Spain&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 4-0&nbsp;
  Lithuania<br/>
  [Serrejуn 4, Sбnchez Piris 22, Orol 23, Jordi Torras 37]<br/>

  Feb&nbsp; 1: Lithuania&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 7-1&nbsp; Finland<br/>
  [Bakus 14, 31, Markevicius 16, 23, Rimkevicius 16, Maciulis 33,<br/>
  &nbsp; Rudzionis 33pen; Salmi 8]<br/>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

  Slovenia&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3-3&nbsp; Spain<br/>
  [Lakoseljac 12, Љnofl 26, 35; Marcelo 7, Serrejуn 12, Andreu 20]<br/>
  <br/>
  1.SPAIN&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3&nbsp;

  2&nbsp; 1&nbsp; 0&nbsp; 20- 3&nbsp; 7<br/>
  2.Slovenia&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3&nbsp; 2&nbsp; 0&nbsp;

  1&nbsp; 11-12&nbsp; 7<br/>
  3.Lithuania&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3&nbsp; 1&nbsp; 0&nbsp;
  2&nbsp; 10-12&nbsp; 3<br/>

  4.Finland&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3&nbsp; 0&nbsp;
  0&nbsp; 3&nbsp;&nbsp; 2-25&nbsp; 0<br/>
  <br/>

  Group 5 (in Zrenjanin, Serbia &amp; Montenegro)<br/>
  Jan 27: Serbia &amp; Mont.&nbsp; 9-2&nbsp; Georgia<br/>
  [Bojanovic 7, Miљcevic 9, 13, 29, Spadijer 15, Benic 16, Rajic 22, 38,<br/>

  &nbsp; Cvetanovic 37; Mizandari 17, Kupatadze 34]<br/>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  Russia&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 5-0&nbsp;
  Azerbaijan<br/>
  [Moskalenko 13, 33 Maevski 22, 25, Abyshev 24]<br/>

  Jan 28: Russia&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 11-2&nbsp;
  Georgia<br/>
  [Tchistopolov 3, 39, Maevski 3, Chtchoutchko 10, 40, Moskalenko 15,<br/>
  &nbsp; Abyshev 15, 35, Ivanov 35, Antipov 38, Chirotchenkov 39; Khutsishvili
  17, 27]<br/>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

  Azerbaijan&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1-2&nbsp; Serbia &amp; Mont.<br/>
  [Mammadkarimov 3; Miљcevic 2, 10]<br/>
  Jan 30: Georgia&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3-7&nbsp;

  Azerbaijan<br/>
  [Kbiladze 17, Seperteladze 22, Mizandari 35; Mammadkarimov 5, 17,<br/>
  &nbsp; Mamedkerimov 12, Ramazanov 13, Azimov 22, 36, Nuriev 38]<br/>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Serbia &amp; Mont.&nbsp; 2-5&nbsp;

  Russia<br/>
  [Bojanovic 8, Miљcevic 33; Tchistopolov 2, 19, Ivanov 16pen, Malyshev 37, 39]<br/>
  <br/>
  1.RUSSIA&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3&nbsp;
  3&nbsp; 0&nbsp; 0&nbsp; 21- 4&nbsp; 9<br/>

  2.Serbia &amp; Mont.&nbsp; 3&nbsp; 2&nbsp; 0&nbsp; 1&nbsp; 13- 8&nbsp; 6<br/>

  3.Azerbaijan&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3&nbsp; 1&nbsp; 0&nbsp;
  2&nbsp;&nbsp; 8-10&nbsp; 3<br/>
  4.Georgia&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3&nbsp; 0&nbsp;

  0&nbsp; 3&nbsp;&nbsp; 7-27&nbsp; 0<br/>
  <br/>
  Group 6 (in Budapest, Hungary)<br/>
  Jan 29: Croatia&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1-1&nbsp;

  Greece<br/>
  [K.Drndic 37; Arvanitis 34]<br/>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  Hungary&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 4-2&nbsp; Latvia<br/>
  [Madarбsz 2, 18, Somogyi 11, Gyurcsбnyi 13; Idionovs 20, Glazovs 36]<br/>

  Jan 30: Croatia&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 6-2&nbsp;
  Latvia<br/>
  [Grdovic 8, Љkerbic 10, Lisjakovs 25own, Drndic 35, Drndic 38,<br/>
  &nbsp; Bonkovic 39; Matvejevs 7, Slepovs 26]<br/>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

  Greece&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2-4&nbsp;
  Hungary<br/>
  [Litos 17, Soilemes 29; M.Tуth 23, Lуdi 27, Baranyai 27, 36]<br/>
  Feb&nbsp; 1: Hungary&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  4-2&nbsp; Croatia<br/>

  [Somogyi 7, S.Tуth 13, Szalay 16, Simon 17; Dulvat 34, 40]<br/>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  Latvia&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2-2&nbsp; Greece<br/>
  [Idionovs 19, Ivanovs 24; Soilemes 13, Litos 32]<br/>
  <br/>

  1.HUNGARY&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3&nbsp; 3&nbsp;
  0&nbsp; 0&nbsp; 12- 6&nbsp; 9<br/>
  2.Croatia&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3&nbsp; 1&nbsp;

  1&nbsp; 1&nbsp;&nbsp; 9- 7&nbsp; 6<br/>
  3.Greece&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3&nbsp;
  0&nbsp; 2&nbsp; 1&nbsp;&nbsp; 5- 7&nbsp; 2<br/>

  4.Latvia&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3&nbsp;
  0&nbsp; 1&nbsp; 2&nbsp;&nbsp; 6-12&nbsp; 1<br/>
  <br/>

  Group 7 (in Sarajevo, Bosnia-Herzegovina)<br/>
  Jan 27: Italy&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  5-0&nbsp; Macedonia FYR<br/>
  [Bertoni 6, Fabiano 11, 18, 20, Vinicius 14]<br/>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  Poland&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3-5&nbsp;

  Bosnia-Herz.<br/>
  [Kalkowski 25, 34, Korczynski 30; Duvnjak 9, 20, 30, 37, Krezo 38]<br/>
  Jan 28: Macedonia FYR&nbsp;&nbsp; 1-1&nbsp; Poland<br/>
  [Janevski 37; Kuchciak 34]<br/>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

  Italy&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3-1&nbsp;
  Bosnia-Herz.<br/>
  [Grana 12, Bertoni 31, Foglia 34; Krezo 24]<br/>
  Jan 30: Poland&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2-11
  Italy<br/>
  [Kalkowski 4, Hirsz 36; Bertoni 9, Grana 9, 10, De Nichile 13, 31, 33,<br/>

  &nbsp; Foglia 19, Vasconcelos 27, Montovanelli 30, Vinicius 36, Fabiano 40]<br/>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Bosnia-Herz.&nbsp;&nbsp;&nbsp;
  8-5&nbsp; Macedonia FYR<br/>
  [Duvnjak 2, 3, Kvesic 20, Dizdarevic 24, Lalic 25, 33, 34, Ramic 40;<br/>
  &nbsp; Nenad 7, Janevski 22, Trajkovski 24, Mitev 30, Љakirovic 39]<br/>

  <br/>
  1.ITALY&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3&nbsp;
  3&nbsp; 0&nbsp; 0&nbsp; 19- 3&nbsp; 9<br/>

  2.Bosnia-Herz.&nbsp;&nbsp;&nbsp; 3&nbsp; 2&nbsp; 0&nbsp; 1&nbsp; 14-11&nbsp;
  6<br/>
  3.Macedonia FYR&nbsp;&nbsp; 3&nbsp; 1&nbsp; 0&nbsp; 2&nbsp;&nbsp; 6-14&nbsp;

  1<br/>
  4.Poland&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3&nbsp;
  0&nbsp; 0&nbsp; 3&nbsp;&nbsp; 6-17&nbsp; 1</span></p>

  </td>
 </tr>
</table>

<p class=MsoNormal><span lang=EN-US>&nbsp;</span></p>

</div>
