<table>
	<tr>
		<th>Название</th>
		<th>&nbsp;</th>
	</tr>
	<?php
	foreach ($this->teams as $item)
	{
		?>
		<tr>
			<td><?php echo $this->escape($item['title']);?></td>
			<td>
				<div class="table_actions">
					<a href="<?php echo $this->url(array('action'=>'edit', 'id'=>$item['id']), null);?>" class="sexybutton sexysimple"><span class="edit">Править</span></a>
					<a href="<?php echo $this->url(array('action'=>'delete', 'id'=>$item['id']), null);?>" class="sexybutton sexysimple"><span class="delete">Удалить</span></a>
				</div>
			</td>
		</tr>
		<?php
	}
	?>
</table>
<a href="<?php echo $this->url(array('action'=>'create'), null);?>" class="sexybutton sexysimple"><span class="add">Добавить команду</span></a>