<form method="post">
<div class="grid_2"><label for="question">Текст опроса:</label></div>
<div class="grid_4"><input type="text" name="question" id="question"
	value="<?php echo $this->escape($this->poll->question);?>" /></div>
<div class="clear"></div>

<div class="grid_2"><label for="active">Включен:</label></div>
<div class="grid_4"><input type="checkbox" name="active" id="active"
	<?php echo $this->poll->active?'checked="checked"':'';?> /></div>
<div class="clear"></div>

<div class="grid_2 prefix_2">
<button class="sexybutton sexysimple"><span class="save">Сохранить</span></button>
</div>
<div class="clear"></div>
</form>