<table>
	<tr>
		<th>#</th>
		<th>Заголовок новости</th>
		<th>Дата</th>
		<th>&nbsp;</th>
	</tr>
	<?php
	foreach ($this->news as $item)
	{
		?>
		<tr>
			<td><?php echo $item['id'];?></td>
			<td><?php echo $this->escape($item['title']);?></td>
			<td><?php echo FW_Date::convert($item['created_ts'], FW_Date::MYSQL_DATETIME, FW_Date::SITE_DATE);?></td>
			<td>
				<div class="table_actions">
					<a href="<?php echo $this->url(array('action'=>'edit', 'id'=>$item['id']), null);?>" class="sexybutton sexysimple"><span class="edit">Править</span></a>
					<a href="<?php echo $this->url(array('action'=>'delete', 'id'=>$item['id']), null);?>" class="sexybutton sexysimple"><span class="delete">Удалить</span></a>
				</div>
			</td>
		</tr>
		<?php
	}
	?>
</table>
<?php echo $this->paginationControl($this->news, 'Sliding', 'pagination.phtml'); ?>
<a href="<?php echo $this->url(array('action'=>'create'), null);?>" class="sexybutton sexysimple"><span class="add">Добавить новость</span></a>
<a href="<?php echo $this->url(array('controller'=>'newscategory', 'action'=>'index'), null);?>" class="sexybutton sexysimple"><span class="add">Добавить Категорию</span></a>