<div class="innerpage lineelement">
	<h4 class="newshead">
		<span>Голосования</span>
	</h4>
	<div class="innerpage-content">
		<?php foreach($this->polls as $poll) : ?>
			<div class="poll-question"><?php echo $poll->question ?></div>
			<?php if(array_key_exists($poll->id, $this->votedPolls) || $poll->active != true) : ?>
				<ul class="poll">
				<?php foreach($this->pollsVariants as $variant) : ?>
				    <?php if($variant->idPoll==$poll->id) : ?>
						<li>
							<span class="lineelement poll-variant"><?php echo $this->escape($variant->text);?></span>
							<span class="lineelement poll-result"><?php echo $variant->votes; ?></span>
							<div class="clear"></div>
						</li>
				    <?php endif; ?>
			    <?php endforeach; ?>
			    </ul>
			<?php else : ?>
				<form action="/polls" method="post">
    				<ul class="poll">
        			    <?php foreach($this->pollsVariants as $variant) : ?>
        				    <?php if($variant->idPoll==$poll->id) : ?>
    							<li><input type="radio" name="answer" id="c_name_<?php echo $variant->id; ?>" value="<?php echo $variant->id; ?>"/><label for="c_name_<?php echo $variant->id;?>"><?php echo $this->escape($variant->text);?></label></li>
        				    <?php endif; ?>
        			    <?php endforeach; ?>
    			    </ul>
    			    <button>Отправить</button>
			    </form>
		    <?php endif; ?>
		 <?php endforeach; ?>
		 <div class="clear"></div>
		 <a href="/" class="menutype-button gotoindex">Вернуться на главную</a>
		 <div class="clear"></div>
	</div>
	<div class="innerpage-footer"></div>
</div>
<div class="inner-usercoll users-coll lineelement">

	<?php echo $this->render('includes/tournament-table.phtml'); ?>

</div>
<div class="clear"></div>