<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?php
//echo (isset($this->title)?'<title>'.$this->title.'</title>':'');
	echo $this->headTitle($this->siteName);
	
	echo $this->headLink();
	
	echo $this->headScript();
 ?>
	<meta name="Description" content="Монолит / минифутбол, футзал, спорт, обзоры, анонсы, форум, фото, видео и многое другое"/>
	<meta name="Keywords" content="Монолит / минифутбол, футзал, спорт, обзоры, анонсы, форум, фото, видео и многое другое"/>
 
 
  
 <script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-16998611-3']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</head>
<body>
	<div class="bgcontainer">
		<div class="container_12 maincontainer">
			<div class="user-menu">
				<div class="addititonal-menu">
					<a href="/"><img src="/i/homeicon.png"/></a>
					<a href="/contacts"><img src="/i/mailicon.png"/></a>
				</div>
				<?php 
					if($this->loggedUser)
						echo $this->render('includes/logged-menu.phtml');
					else
						echo $this->render('includes/no-logged-menu.phtml');
				?>
			</div>
			<?php
				echo $this->render("includes/topBaner.phtml");
				echo $this->render("includes/mainmenu.phtml");
				echo $this->render("includes/bigBaner.phtml");
				echo $this->layout()->content;
			?>
			<div class="news_block_element videoblock">
				<h4 class="newshead monolit">
					<span>Для пользователей</span>
				</h4>
				<div class="counters lineelement">
					
					<div class="geo">
					
						<a href="http://s07.flagcounter.com/more/KO"><img src="http://s07.flagcounter.com/count/KO/bg=FFFFFF/txt=000000/border=CCCCCC/columns=2/maxflags=12/viewers=0/labels=1/" alt="Free counters!" border="0"></a>
					
					</div>
					
					<div class="hotlog">
					
						<!-- HotLog -->
							<script type="text/javascript" language="javascript">
							hotlog_js="1.0"; hotlog_r=""+Math.random()+"&s=2108301&im=501&r="+
							escape(document.referrer)+"&pg="+escape(window.location.href);
							</script>
							<script type="text/javascript" language="javascript1.1">
							hotlog_js="1.1"; hotlog_r+="&j="+(navigator.javaEnabled()?"Y":"N");
							</script>
							<script type="text/javascript" language="javascript1.2">
							hotlog_js="1.2"; hotlog_r+="&wh="+screen.width+"x"+screen.height+"&px="+
							(((navigator.appName.substring(0,3)=="Mic"))?screen.colorDepth:screen.pixelDepth);
							</script>
							<script type="text/javascript" language="javascript1.3">
							hotlog_js="1.3";
							</script>
							<script type="text/javascript" language="javascript">
							hotlog_r+="&js="+hotlog_js;
							document.write('<a href="http://click.hotlog.ru/?2108301" target="_blank"><img '+
							'src="http://hit36.hotlog.ru/cgi-bin/hotlog/count?'+
							hotlog_r+'" border="0" width="88" height="31" alt="HotLog"><\/a>');
							</script>
							<noscript>
							<a href="http://click.hotlog.ru/?2108301" target="_blank"><img
							src="http://hit36.hotlog.ru/cgi-bin/hotlog/count?s=2108301&im=501" border="0"
							width="88" height="31" alt="HotLog"/></a>
							</noscript>
						<!-- /HotLog -->
					
					</div>
					
					<div class="openstat">
						<!--Openstat--><span id="openstat2135001"></span><script type="text/javascript">
							var openstat = { counter: 2135001, image: 5041, next: openstat }; document.write(unescape("%3Cscript%20src=%22http" +
							(("https:" == document.location.protocol) ? "s" : "") +
							"://openstat.net/cnt.js%22%20defer=%22defer%22%3E%3C/script%3E"));
							</script>
						<!--/Openstat--> 
					</div>
					
					<div class="bigmir">
					
						<!--bigmir)net TOP 100-->
							<script type="text/javascript" language="javascript"><!--
							bmN=navigator,bmD=document,bmD.cookie='b=b',i=0,bs=[],bm={v:16874055,s:16874055,t:19,c:bmD.cookie?1:0,n:Math.round((Math.random()* 1000000)),w:0};
							for(var f=self;f!=f.parent;f=f.parent)bm.w++;
							try{if(bmN.plugins&&bmN.mimeTypes.length&&(x=bmN.plugins['Shockwave Flash']))bm.m=parseInt(x.description.replace(/([a-zA-Z]|\s)+/,''));
							else for(var f=3;f<20;f++)if(eval('new ActiveXObject("ShockwaveFlash.ShockwaveFlash.'+f+'")'))bm.m=f}catch(e){;}
							try{bm.y=bmN.javaEnabled()?1:0}catch(e){;}
							try{bmS=screen;bm.v^=bm.d=bmS.colorDepth||bmS.pixelDepth;bm.v^=bm.r=bmS.width}catch(e){;}
							r=bmD.referrer.slice(7);if(r&&r.split('/')[0]!=window.location.host){bm.f=escape(r);bm.v^=r.length}
							bm.v^=window.location.href.length;for(var x in bm) if(/^[vstcnwmydrf]$/.test(x)) bs[i++]=x+bm[x];
							bmD.write('<a href="http://www.bigmir.net/" target="_blank" onClick="img=new Image();img.src=&quot;http://www.bigmir.net/?cl=16874055&quot;;"><img src="http://c.bigmir.net/?'+bs.join('&')+'"  width="88" height="63" border="0" alt="bigmir)net TOP 100" title="bigmir)net TOP 100"></a>');
							//-->
							</script>
							<noscript>
							<a href="http://www.bigmir.net/" target="_blank"><img src="http://c.bigmir.net/?v16874055&s16874055&t19" width="88" height="63" alt="bigmir)net TOP 100" title="bigmir)net TOP 100" border="0" /></a>
							</noscript>
						<!--bigmir)net TOP 100-->
					
					</div>
				</div>
				<div class="lineelement users">
					<a href="#">Размещение рекламы</a>
				</div>
				<div class="clear"></div>
				<div class="created-by">
					Разработано <a class="vipsites" onclick="this.target='target'" href="http://www.sites-vip.com">Vip Sites Company</a> при участии <a class="artvision" onclick="this.target='target'" href="http://www.artvision.net.ua">Artvision Studio</a> 
				</div>				
			</div>
		</div>
	</div>
	<?php // echo $this->render("includes/footer_menu.phtml"); ?>
</body>
</html>
