<div class="innerpage lineelement">
	<h4 class="newshead">
		<span>Состав команды</span>
	</h4>
	<div class="innerpage-content">
		<div class="president-line">
			<div class="president-block lineelement">
				<div class="president-posititon">
					Президент и Главный тренер
				</div>
				<img src="/i/staff/peradze.jpg"/>
				<div class="president-name">
					Перадзе<br/>Роман Тариелович
				</div>
			</div>
			<div class="president-block lineelement">
				<div class="president-posititon">
					Начальник команды
				</div>
				<img src="/i/staff/pugunec.jpg"/>
				<div class="president-name">
					Пугунец<br/>Тимур Сергеевич
				</div>
			</div>
			<div class="clear"></div>
		</div>
		<div class="player-line">
			<div class="player-block lineelement">
				<img src="/i/staff/baev.jpg" width="128"/>
				<div class="player-name">
					Владислав Баев
				</div>
			</div>
			<div class="player-block lineelement">
				<img src="/i/staff/avetisyan.jpg" width="128"/>
				<div class="player-name">
					Максим Аветисян
				</div>
			</div>
			<div class="player-block lineelement">
				<img src="/i/staff/gurko.jpg" width="128"/>
				<div class="player-name">
					Иван Гурко
				</div>
			</div>
			<div class="player-block lineelement">
				<img src="/i/staff/skolotiy.jpg" width="128"/>
				<div class="player-name">
					Константин Сколотий
				</div>
			</div>
			
			<div class="player-block lineelement">
				<img src="/i/staff/tkachenko.jpg" width="128"/>
				<div class="player-name">
					Сергей Ткаченко
				</div>
			</div>
			<div class="player-block lineelement">
				<img src="/i/staff/minaev.jpg" width="128"/>
				<div class="player-name">
					Александр Минаев
				</div>
			</div>
			
			<div class="player-block lineelement">
				<img src="/i/staff/kulik.jpg" width="128"/>
				<div class="player-name">
					Эдуард Кулик
				</div>
			</div>
			<div class="player-block lineelement">
				<img src="/i/staff/kolesnikov.jpg" width="128"/>
				<div class="player-name">
					Александр Колесников
				</div>
			</div>
			
			<div class="player-block lineelement">
				<img src="/i/staff/dolgov.jpg" width="128"/>
				<div class="player-name">
					Дмитрий Долгов
				</div>
			</div>
			
			<div class="player-block lineelement">
				<img src="/i/staff/chabanov.jpg" width="128"/>
				<div class="player-name">
					Павел Чабанов
				</div>
			</div>
			
			<div class="player-block lineelement">
				<img src="/i/staff/podzolkov.jpg" width="128"/>
				<div class="player-name">
					Антон Подзолков
				</div>
			</div>
			
			<div class="player-block lineelement">
				<img src="/i/staff/suhomlinov.jpg" width="128"/>
				<div class="player-name">
					Василий Сухомлинов
				</div>
			</div>
			
			<div class="player-block lineelement">
				<img src="/i/staff/unakov.jpg" width="128"/>
				<div class="player-name">
					Евгений Юнаков
				</div>
			</div> 
			
			<div class="clear"></div>
		</div>
	</div>
	<div class="player-list">
		<div class="goalkeepers">
			<div class="lineelement player-position">Вратари</div>
			<div class="lineelement player-infos">
				
				<div class="player-info">
					<div class="lineelement number">№3</div>
					<div class="lineelement player-name">Иван Гурко</div>
					<div class="lineelement player-date">27.07.1987</div>
					<div class="clear"></div>
				</div>
				
				<?php /* ?><div class="player-info">
					<div class="lineelement number">&nbsp;</div>
					<div class="lineelement player-name">Роман Мякота</div>
					<div class="lineelement player-date">28.04.1993</div>
					<div class="clear"></div>
				</div> <?php */ ?>
				
				<div class="player-info">
					<div class="lineelement number">№31</div>
					<div class="lineelement player-name">Павел Чабанов</div>
					<div class="lineelement player-date">04.04.1990</div>
					<div class="clear"></div>
				</div>
				
				<div class="player-info">
					<div class="lineelement number">№1</div>
					<div class="lineelement player-name">Василий Сухомлинов</div>
					<div class="lineelement player-date">20.05.1976</div>
					<div class="clear"></div>
				</div>
				
				
			</div>
			<div class="clear"></div>
		</div>
		
		<div class="fieldplayers">
			<div class="lineelement player-position">Универсалы</div>
			<div class="lineelement player-infos">
			
				<div class="player-info">
					<div class="lineelement number">№20</div>
					<div class="lineelement player-name">Владислав Баев</div>
					<div class="lineelement player-date">20.04.1991</div>
					<div class="clear"></div>
				</div>
				<div class="player-info">
					<div class="lineelement number">№7</div>
					<div class="lineelement player-name">Максим Аветисян</div>
					<div class="lineelement player-date">03.01.1991</div>
					<div class="clear"></div>
				</div>
			
				<div class="player-info">
					<div class="lineelement number">№12</div>
					<div class="lineelement player-name">Константин Сколотий</div>
					<div class="lineelement player-date">17.11.1983</div>
					<div class="clear"></div>
				</div>
				<div class="player-info">
					<div class="lineelement number">№10</div>
					<div class="lineelement player-name">Сергей Ткаченко</div>
					<div class="lineelement player-date">09.08.1975</div>
					<div class="clear"></div>
				</div>
				<div class="player-info">
					<div class="lineelement number">№5</div>
					<div class="lineelement player-name">Александр Минаев</div>
					<div class="lineelement player-date">26.01.1978</div>
					<div class="clear"></div>
				</div>
				<div class="player-info">
					<div class="lineelement number">№11</div>
					<div class="lineelement player-name">Александр Колесников</div>
					<div class="lineelement player-date">24.05.1988</div>
					<div class="clear"></div>
				</div>
				<div class="player-info">
					<div class="lineelement number">№13</div>
					<div class="lineelement player-name">Эдуард Кулик</div>
					<div class="lineelement player-date">05.03.1981</div>
					<div class="clear"></div>
				</div>
				<div class="player-info">
					<div class="lineelement number">№17</div>
					<div class="lineelement player-name">Дмитрий Долгов</div>
					<div class="lineelement player-date">14.07.1990</div>
					<div class="clear"></div>
				</div>
				<div class="player-info">
					<div class="lineelement number">№9</div>
					<div class="lineelement player-name">Евгений Юнаков</div>
					<div class="lineelement player-date">24.10.1982</div>
					<div class="clear"></div>
				</div>
				<div class="player-info">
					<div class="lineelement number">№8</div>
					<div class="lineelement player-name">Антон Подзолков</div>
					<div class="lineelement player-date">09.10.1986</div>
					<div class="clear"></div>
				</div>
			</div>
			<div class="clear"></div>
		</div>
		
	</div>
	<div class="innerpage-footer"></div>
</div>
<div class="inner-usercoll users-coll lineelement">
	
	<?php echo $this->render('includes/tournament-table.phtml'); ?>

	<div class="last-monolit-news news_block_element">
		<h4 class="newshead">
			<span>Новости</span>
		</h4>
		<ul>
			<?php foreach($this->lastMonolitNews as $lastMonolitNew) 
			{?>
				<li>
					<a href="/index/view/id/<?php echo $lastMonolitNew->id; ?>"><?php echo $lastMonolitNew->title; ?></a>
				</li>
			<?php } ?>
		</ul>
	</div>
	<div class="left-coll-footer"></div>
</div>
<div class="clear"></div>