<form method="post" action="#">
	<div class="grid_2"><label for="name">Имя:</label></div>
	<div class="grid_4"><input type="text" name="name" id="name" value="" /></div>
	<div class="clear"></div>
	
	<div class="grid_2"><label for="team">Команда:</label></div>
	<div class="grid_4"><input type="text" name="team" id="team" value="" /></div>
	<div class="clear"></div>
	
	<div class="grid_2"><label for="goals">Голы:</label></div>
	<div class="grid_4"><input type="text" name="goals" id="goals" value="" /></div>
	<div class="clear"></div>
	
	<div class="grid_2"><label for="pen">C пенальти:</label></div>
	<div class="grid_4"><input type="text" name="pen" id="pen" value="" /></div>
	<div class="clear"></div>
	
	<div class="grid_2 prefix_2">
	<button class="sexybutton sexysimple"><span class="save">Сохранить</span></button>
	</div>
	<div class="clear"></div>
</form>