<div class="news_block_element">
	<h4 class="newshead">
		<span>Изменить фотографию</span>
	</h4>
	
	<div class="profile-content">
		<div class="photoblock lineelement">
			<img src=<?php echo $this->loggedUser->photo?'/i/users/'.$this->loggedUser->photo:'/i/no-user-photo.jpg' ?>>
			
			<div class="edit-links">
				<a href="/profile/edit-data">Изменить личные данные</a>
				<?php if($this->loggedUser->photo) { ?>
					<a href="/profile/edit-photo">Изменить фотографию</a>
					<a href="/profile/delete-photo">Удалить фотографию</a>
				<?php } else { ?>
					<a href="/profile/edit-photo">Добавить фотографию</a>
				<?php } ?>
				<a href="/profile/edit-password">Изменить пароль</a>
			</div>
			
		</div>
		<div class="infoblock lineelement">
			<div class="register-form">
				<?php echo $this->form; ?>
			</div>
		</div>
		<div class="clear"></div>
	</div>
	<div class="clear"></div>
</div>